/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.21.12
 * source: coretex/agent/v1/buspacket.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./../../../google/protobuf/timestamp";
import * as dependency_2 from "./job";
import * as dependency_3 from "./heartbeat";
import * as dependency_4 from "./alert";
import * as pb_1 from "google-protobuf";
export namespace coretex.agent.v1 {
    export class BusPacket extends pb_1.Message {
        #one_of_decls: number[][] = [[10, 11, 12, 13]];
        constructor(data?: any[] | ({
            trace_id?: string;
            sender_id?: string;
            created_at?: dependency_1.google.protobuf.Timestamp;
            protocol_version?: number;
            signature?: Uint8Array;
        } & (({
            job_request?: dependency_2.coretex.agent.v1.JobRequest;
            job_result?: never;
            heartbeat?: never;
            alert?: never;
        } | {
            job_request?: never;
            job_result?: dependency_2.coretex.agent.v1.JobResult;
            heartbeat?: never;
            alert?: never;
        } | {
            job_request?: never;
            job_result?: never;
            heartbeat?: dependency_3.coretex.agent.v1.Heartbeat;
            alert?: never;
        } | {
            job_request?: never;
            job_result?: never;
            heartbeat?: never;
            alert?: dependency_4.coretex.agent.v1.SystemAlert;
        })))) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("trace_id" in data && data.trace_id != undefined) {
                    this.trace_id = data.trace_id;
                }
                if ("sender_id" in data && data.sender_id != undefined) {
                    this.sender_id = data.sender_id;
                }
                if ("created_at" in data && data.created_at != undefined) {
                    this.created_at = data.created_at;
                }
                if ("protocol_version" in data && data.protocol_version != undefined) {
                    this.protocol_version = data.protocol_version;
                }
                if ("job_request" in data && data.job_request != undefined) {
                    this.job_request = data.job_request;
                }
                if ("job_result" in data && data.job_result != undefined) {
                    this.job_result = data.job_result;
                }
                if ("heartbeat" in data && data.heartbeat != undefined) {
                    this.heartbeat = data.heartbeat;
                }
                if ("alert" in data && data.alert != undefined) {
                    this.alert = data.alert;
                }
                if ("signature" in data && data.signature != undefined) {
                    this.signature = data.signature;
                }
            }
        }
        get trace_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set trace_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get sender_id() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set sender_id(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get created_at() {
            return pb_1.Message.getWrapperField(this, dependency_1.google.protobuf.Timestamp, 3) as dependency_1.google.protobuf.Timestamp;
        }
        set created_at(value: dependency_1.google.protobuf.Timestamp) {
            pb_1.Message.setWrapperField(this, 3, value);
        }
        get has_created_at() {
            return pb_1.Message.getField(this, 3) != null;
        }
        get protocol_version() {
            return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
        }
        set protocol_version(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        get job_request() {
            return pb_1.Message.getWrapperField(this, dependency_2.coretex.agent.v1.JobRequest, 10) as dependency_2.coretex.agent.v1.JobRequest;
        }
        set job_request(value: dependency_2.coretex.agent.v1.JobRequest) {
            pb_1.Message.setOneofWrapperField(this, 10, this.#one_of_decls[0], value);
        }
        get has_job_request() {
            return pb_1.Message.getField(this, 10) != null;
        }
        get job_result() {
            return pb_1.Message.getWrapperField(this, dependency_2.coretex.agent.v1.JobResult, 11) as dependency_2.coretex.agent.v1.JobResult;
        }
        set job_result(value: dependency_2.coretex.agent.v1.JobResult) {
            pb_1.Message.setOneofWrapperField(this, 11, this.#one_of_decls[0], value);
        }
        get has_job_result() {
            return pb_1.Message.getField(this, 11) != null;
        }
        get heartbeat() {
            return pb_1.Message.getWrapperField(this, dependency_3.coretex.agent.v1.Heartbeat, 12) as dependency_3.coretex.agent.v1.Heartbeat;
        }
        set heartbeat(value: dependency_3.coretex.agent.v1.Heartbeat) {
            pb_1.Message.setOneofWrapperField(this, 12, this.#one_of_decls[0], value);
        }
        get has_heartbeat() {
            return pb_1.Message.getField(this, 12) != null;
        }
        get alert() {
            return pb_1.Message.getWrapperField(this, dependency_4.coretex.agent.v1.SystemAlert, 13) as dependency_4.coretex.agent.v1.SystemAlert;
        }
        set alert(value: dependency_4.coretex.agent.v1.SystemAlert) {
            pb_1.Message.setOneofWrapperField(this, 13, this.#one_of_decls[0], value);
        }
        get has_alert() {
            return pb_1.Message.getField(this, 13) != null;
        }
        get signature() {
            return pb_1.Message.getFieldWithDefault(this, 14, new Uint8Array(0)) as Uint8Array;
        }
        set signature(value: Uint8Array) {
            pb_1.Message.setField(this, 14, value);
        }
        get payload() {
            const cases: {
                [index: number]: "none" | "job_request" | "job_result" | "heartbeat" | "alert";
            } = {
                0: "none",
                10: "job_request",
                11: "job_result",
                12: "heartbeat",
                13: "alert"
            };
            return cases[pb_1.Message.computeOneofCase(this, [10, 11, 12, 13])];
        }
        static fromObject(data: {
            trace_id?: string;
            sender_id?: string;
            created_at?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
            protocol_version?: number;
            job_request?: ReturnType<typeof dependency_2.coretex.agent.v1.JobRequest.prototype.toObject>;
            job_result?: ReturnType<typeof dependency_2.coretex.agent.v1.JobResult.prototype.toObject>;
            heartbeat?: ReturnType<typeof dependency_3.coretex.agent.v1.Heartbeat.prototype.toObject>;
            alert?: ReturnType<typeof dependency_4.coretex.agent.v1.SystemAlert.prototype.toObject>;
            signature?: Uint8Array;
        }): BusPacket {
            const message = new BusPacket({});
            if (data.trace_id != null) {
                message.trace_id = data.trace_id;
            }
            if (data.sender_id != null) {
                message.sender_id = data.sender_id;
            }
            if (data.created_at != null) {
                message.created_at = dependency_1.google.protobuf.Timestamp.fromObject(data.created_at);
            }
            if (data.protocol_version != null) {
                message.protocol_version = data.protocol_version;
            }
            if (data.job_request != null) {
                message.job_request = dependency_2.coretex.agent.v1.JobRequest.fromObject(data.job_request);
            }
            if (data.job_result != null) {
                message.job_result = dependency_2.coretex.agent.v1.JobResult.fromObject(data.job_result);
            }
            if (data.heartbeat != null) {
                message.heartbeat = dependency_3.coretex.agent.v1.Heartbeat.fromObject(data.heartbeat);
            }
            if (data.alert != null) {
                message.alert = dependency_4.coretex.agent.v1.SystemAlert.fromObject(data.alert);
            }
            if (data.signature != null) {
                message.signature = data.signature;
            }
            return message;
        }
        toObject() {
            const data: {
                trace_id?: string;
                sender_id?: string;
                created_at?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
                protocol_version?: number;
                job_request?: ReturnType<typeof dependency_2.coretex.agent.v1.JobRequest.prototype.toObject>;
                job_result?: ReturnType<typeof dependency_2.coretex.agent.v1.JobResult.prototype.toObject>;
                heartbeat?: ReturnType<typeof dependency_3.coretex.agent.v1.Heartbeat.prototype.toObject>;
                alert?: ReturnType<typeof dependency_4.coretex.agent.v1.SystemAlert.prototype.toObject>;
                signature?: Uint8Array;
            } = {};
            if (this.trace_id != null) {
                data.trace_id = this.trace_id;
            }
            if (this.sender_id != null) {
                data.sender_id = this.sender_id;
            }
            if (this.created_at != null) {
                data.created_at = this.created_at.toObject();
            }
            if (this.protocol_version != null) {
                data.protocol_version = this.protocol_version;
            }
            if (this.job_request != null) {
                data.job_request = this.job_request.toObject();
            }
            if (this.job_result != null) {
                data.job_result = this.job_result.toObject();
            }
            if (this.heartbeat != null) {
                data.heartbeat = this.heartbeat.toObject();
            }
            if (this.alert != null) {
                data.alert = this.alert.toObject();
            }
            if (this.signature != null) {
                data.signature = this.signature;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.trace_id.length)
                writer.writeString(1, this.trace_id);
            if (this.sender_id.length)
                writer.writeString(2, this.sender_id);
            if (this.has_created_at)
                writer.writeMessage(3, this.created_at, () => this.created_at.serialize(writer));
            if (this.protocol_version != 0)
                writer.writeInt32(4, this.protocol_version);
            if (this.has_job_request)
                writer.writeMessage(10, this.job_request, () => this.job_request.serialize(writer));
            if (this.has_job_result)
                writer.writeMessage(11, this.job_result, () => this.job_result.serialize(writer));
            if (this.has_heartbeat)
                writer.writeMessage(12, this.heartbeat, () => this.heartbeat.serialize(writer));
            if (this.has_alert)
                writer.writeMessage(13, this.alert, () => this.alert.serialize(writer));
            if (this.signature.length)
                writer.writeBytes(14, this.signature);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): BusPacket {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new BusPacket();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.trace_id = reader.readString();
                        break;
                    case 2:
                        message.sender_id = reader.readString();
                        break;
                    case 3:
                        reader.readMessage(message.created_at, () => message.created_at = dependency_1.google.protobuf.Timestamp.deserialize(reader));
                        break;
                    case 4:
                        message.protocol_version = reader.readInt32();
                        break;
                    case 10:
                        reader.readMessage(message.job_request, () => message.job_request = dependency_2.coretex.agent.v1.JobRequest.deserialize(reader));
                        break;
                    case 11:
                        reader.readMessage(message.job_result, () => message.job_result = dependency_2.coretex.agent.v1.JobResult.deserialize(reader));
                        break;
                    case 12:
                        reader.readMessage(message.heartbeat, () => message.heartbeat = dependency_3.coretex.agent.v1.Heartbeat.deserialize(reader));
                        break;
                    case 13:
                        reader.readMessage(message.alert, () => message.alert = dependency_4.coretex.agent.v1.SystemAlert.deserialize(reader));
                        break;
                    case 14:
                        message.signature = reader.readBytes();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): BusPacket {
            return BusPacket.deserialize(bytes);
        }
    }
}
