// source: coretex/agent/v1/buspacket.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var coretex_agent_v1_job_pb = require('../../../coretex/agent/v1/job_pb.js');
goog.object.extend(proto, coretex_agent_v1_job_pb);
var coretex_agent_v1_heartbeat_pb = require('../../../coretex/agent/v1/heartbeat_pb.js');
goog.object.extend(proto, coretex_agent_v1_heartbeat_pb);
var coretex_agent_v1_alert_pb = require('../../../coretex/agent/v1/alert_pb.js');
goog.object.extend(proto, coretex_agent_v1_alert_pb);
goog.exportSymbol('proto.coretex.agent.v1.BusPacket', null, global);
goog.exportSymbol('proto.coretex.agent.v1.BusPacket.PayloadCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.coretex.agent.v1.BusPacket = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.coretex.agent.v1.BusPacket.oneofGroups_);
};
goog.inherits(proto.coretex.agent.v1.BusPacket, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.coretex.agent.v1.BusPacket.displayName = 'proto.coretex.agent.v1.BusPacket';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.coretex.agent.v1.BusPacket.oneofGroups_ = [[10,11,12,13]];

/**
 * @enum {number}
 */
proto.coretex.agent.v1.BusPacket.PayloadCase = {
  PAYLOAD_NOT_SET: 0,
  JOB_REQUEST: 10,
  JOB_RESULT: 11,
  HEARTBEAT: 12,
  ALERT: 13
};

/**
 * @return {proto.coretex.agent.v1.BusPacket.PayloadCase}
 */
proto.coretex.agent.v1.BusPacket.prototype.getPayloadCase = function() {
  return /** @type {proto.coretex.agent.v1.BusPacket.PayloadCase} */(jspb.Message.computeOneofCase(this, proto.coretex.agent.v1.BusPacket.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.coretex.agent.v1.BusPacket.prototype.toObject = function(opt_includeInstance) {
  return proto.coretex.agent.v1.BusPacket.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.coretex.agent.v1.BusPacket} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.coretex.agent.v1.BusPacket.toObject = function(includeInstance, msg) {
  var f, obj = {
traceId: jspb.Message.getFieldWithDefault(msg, 1, ""),
senderId: jspb.Message.getFieldWithDefault(msg, 2, ""),
createdAt: (f = msg.getCreatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
protocolVersion: jspb.Message.getFieldWithDefault(msg, 4, 0),
jobRequest: (f = msg.getJobRequest()) && coretex_agent_v1_job_pb.JobRequest.toObject(includeInstance, f),
jobResult: (f = msg.getJobResult()) && coretex_agent_v1_job_pb.JobResult.toObject(includeInstance, f),
heartbeat: (f = msg.getHeartbeat()) && coretex_agent_v1_heartbeat_pb.Heartbeat.toObject(includeInstance, f),
alert: (f = msg.getAlert()) && coretex_agent_v1_alert_pb.SystemAlert.toObject(includeInstance, f),
signature: msg.getSignature_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.coretex.agent.v1.BusPacket}
 */
proto.coretex.agent.v1.BusPacket.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.coretex.agent.v1.BusPacket;
  return proto.coretex.agent.v1.BusPacket.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.coretex.agent.v1.BusPacket} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.coretex.agent.v1.BusPacket}
 */
proto.coretex.agent.v1.BusPacket.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTraceId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSenderId(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedAt(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setProtocolVersion(value);
      break;
    case 10:
      var value = new coretex_agent_v1_job_pb.JobRequest;
      reader.readMessage(value,coretex_agent_v1_job_pb.JobRequest.deserializeBinaryFromReader);
      msg.setJobRequest(value);
      break;
    case 11:
      var value = new coretex_agent_v1_job_pb.JobResult;
      reader.readMessage(value,coretex_agent_v1_job_pb.JobResult.deserializeBinaryFromReader);
      msg.setJobResult(value);
      break;
    case 12:
      var value = new coretex_agent_v1_heartbeat_pb.Heartbeat;
      reader.readMessage(value,coretex_agent_v1_heartbeat_pb.Heartbeat.deserializeBinaryFromReader);
      msg.setHeartbeat(value);
      break;
    case 13:
      var value = new coretex_agent_v1_alert_pb.SystemAlert;
      reader.readMessage(value,coretex_agent_v1_alert_pb.SystemAlert.deserializeBinaryFromReader);
      msg.setAlert(value);
      break;
    case 14:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setSignature(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.coretex.agent.v1.BusPacket.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.coretex.agent.v1.BusPacket.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.coretex.agent.v1.BusPacket} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.coretex.agent.v1.BusPacket.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTraceId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSenderId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getCreatedAt();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getProtocolVersion();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getJobRequest();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      coretex_agent_v1_job_pb.JobRequest.serializeBinaryToWriter
    );
  }
  f = message.getJobResult();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      coretex_agent_v1_job_pb.JobResult.serializeBinaryToWriter
    );
  }
  f = message.getHeartbeat();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      coretex_agent_v1_heartbeat_pb.Heartbeat.serializeBinaryToWriter
    );
  }
  f = message.getAlert();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      coretex_agent_v1_alert_pb.SystemAlert.serializeBinaryToWriter
    );
  }
  f = message.getSignature_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      14,
      f
    );
  }
};


/**
 * optional string trace_id = 1;
 * @return {string}
 */
proto.coretex.agent.v1.BusPacket.prototype.getTraceId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.coretex.agent.v1.BusPacket} returns this
 */
proto.coretex.agent.v1.BusPacket.prototype.setTraceId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string sender_id = 2;
 * @return {string}
 */
proto.coretex.agent.v1.BusPacket.prototype.getSenderId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.coretex.agent.v1.BusPacket} returns this
 */
proto.coretex.agent.v1.BusPacket.prototype.setSenderId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional google.protobuf.Timestamp created_at = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.coretex.agent.v1.BusPacket.prototype.getCreatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.coretex.agent.v1.BusPacket} returns this
*/
proto.coretex.agent.v1.BusPacket.prototype.setCreatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.coretex.agent.v1.BusPacket} returns this
 */
proto.coretex.agent.v1.BusPacket.prototype.clearCreatedAt = function() {
  return this.setCreatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.coretex.agent.v1.BusPacket.prototype.hasCreatedAt = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional int32 protocol_version = 4;
 * @return {number}
 */
proto.coretex.agent.v1.BusPacket.prototype.getProtocolVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.coretex.agent.v1.BusPacket} returns this
 */
proto.coretex.agent.v1.BusPacket.prototype.setProtocolVersion = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional JobRequest job_request = 10;
 * @return {?proto.coretex.agent.v1.JobRequest}
 */
proto.coretex.agent.v1.BusPacket.prototype.getJobRequest = function() {
  return /** @type{?proto.coretex.agent.v1.JobRequest} */ (
    jspb.Message.getWrapperField(this, coretex_agent_v1_job_pb.JobRequest, 10));
};


/**
 * @param {?proto.coretex.agent.v1.JobRequest|undefined} value
 * @return {!proto.coretex.agent.v1.BusPacket} returns this
*/
proto.coretex.agent.v1.BusPacket.prototype.setJobRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 10, proto.coretex.agent.v1.BusPacket.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.coretex.agent.v1.BusPacket} returns this
 */
proto.coretex.agent.v1.BusPacket.prototype.clearJobRequest = function() {
  return this.setJobRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.coretex.agent.v1.BusPacket.prototype.hasJobRequest = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional JobResult job_result = 11;
 * @return {?proto.coretex.agent.v1.JobResult}
 */
proto.coretex.agent.v1.BusPacket.prototype.getJobResult = function() {
  return /** @type{?proto.coretex.agent.v1.JobResult} */ (
    jspb.Message.getWrapperField(this, coretex_agent_v1_job_pb.JobResult, 11));
};


/**
 * @param {?proto.coretex.agent.v1.JobResult|undefined} value
 * @return {!proto.coretex.agent.v1.BusPacket} returns this
*/
proto.coretex.agent.v1.BusPacket.prototype.setJobResult = function(value) {
  return jspb.Message.setOneofWrapperField(this, 11, proto.coretex.agent.v1.BusPacket.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.coretex.agent.v1.BusPacket} returns this
 */
proto.coretex.agent.v1.BusPacket.prototype.clearJobResult = function() {
  return this.setJobResult(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.coretex.agent.v1.BusPacket.prototype.hasJobResult = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional Heartbeat heartbeat = 12;
 * @return {?proto.coretex.agent.v1.Heartbeat}
 */
proto.coretex.agent.v1.BusPacket.prototype.getHeartbeat = function() {
  return /** @type{?proto.coretex.agent.v1.Heartbeat} */ (
    jspb.Message.getWrapperField(this, coretex_agent_v1_heartbeat_pb.Heartbeat, 12));
};


/**
 * @param {?proto.coretex.agent.v1.Heartbeat|undefined} value
 * @return {!proto.coretex.agent.v1.BusPacket} returns this
*/
proto.coretex.agent.v1.BusPacket.prototype.setHeartbeat = function(value) {
  return jspb.Message.setOneofWrapperField(this, 12, proto.coretex.agent.v1.BusPacket.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.coretex.agent.v1.BusPacket} returns this
 */
proto.coretex.agent.v1.BusPacket.prototype.clearHeartbeat = function() {
  return this.setHeartbeat(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.coretex.agent.v1.BusPacket.prototype.hasHeartbeat = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional SystemAlert alert = 13;
 * @return {?proto.coretex.agent.v1.SystemAlert}
 */
proto.coretex.agent.v1.BusPacket.prototype.getAlert = function() {
  return /** @type{?proto.coretex.agent.v1.SystemAlert} */ (
    jspb.Message.getWrapperField(this, coretex_agent_v1_alert_pb.SystemAlert, 13));
};


/**
 * @param {?proto.coretex.agent.v1.SystemAlert|undefined} value
 * @return {!proto.coretex.agent.v1.BusPacket} returns this
*/
proto.coretex.agent.v1.BusPacket.prototype.setAlert = function(value) {
  return jspb.Message.setOneofWrapperField(this, 13, proto.coretex.agent.v1.BusPacket.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.coretex.agent.v1.BusPacket} returns this
 */
proto.coretex.agent.v1.BusPacket.prototype.clearAlert = function() {
  return this.setAlert(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.coretex.agent.v1.BusPacket.prototype.hasAlert = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional bytes signature = 14;
 * @return {!(string|Uint8Array)}
 */
proto.coretex.agent.v1.BusPacket.prototype.getSignature = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * optional bytes signature = 14;
 * This is a type-conversion wrapper around `getSignature()`
 * @return {string}
 */
proto.coretex.agent.v1.BusPacket.prototype.getSignature_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getSignature()));
};


/**
 * optional bytes signature = 14;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getSignature()`
 * @return {!Uint8Array}
 */
proto.coretex.agent.v1.BusPacket.prototype.getSignature_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getSignature()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.coretex.agent.v1.BusPacket} returns this
 */
proto.coretex.agent.v1.BusPacket.prototype.setSignature = function(value) {
  return jspb.Message.setProto3BytesField(this, 14, value);
};


goog.object.extend(exports, proto.coretex.agent.v1);
