/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.21.12
 * source: coretex/agent/v1/heartbeat.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export namespace coretex.agent.v1 {
    export class Heartbeat extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            worker_id?: string;
            region?: string;
            type?: string;
            cpu_load?: number;
            gpu_utilization?: number;
            active_jobs?: number;
            capabilities?: string[];
            pool?: string;
            max_parallel_jobs?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [7], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("worker_id" in data && data.worker_id != undefined) {
                    this.worker_id = data.worker_id;
                }
                if ("region" in data && data.region != undefined) {
                    this.region = data.region;
                }
                if ("type" in data && data.type != undefined) {
                    this.type = data.type;
                }
                if ("cpu_load" in data && data.cpu_load != undefined) {
                    this.cpu_load = data.cpu_load;
                }
                if ("gpu_utilization" in data && data.gpu_utilization != undefined) {
                    this.gpu_utilization = data.gpu_utilization;
                }
                if ("active_jobs" in data && data.active_jobs != undefined) {
                    this.active_jobs = data.active_jobs;
                }
                if ("capabilities" in data && data.capabilities != undefined) {
                    this.capabilities = data.capabilities;
                }
                if ("pool" in data && data.pool != undefined) {
                    this.pool = data.pool;
                }
                if ("max_parallel_jobs" in data && data.max_parallel_jobs != undefined) {
                    this.max_parallel_jobs = data.max_parallel_jobs;
                }
            }
        }
        get worker_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set worker_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get region() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set region(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get type() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set type(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get cpu_load() {
            return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
        }
        set cpu_load(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        get gpu_utilization() {
            return pb_1.Message.getFieldWithDefault(this, 5, 0) as number;
        }
        set gpu_utilization(value: number) {
            pb_1.Message.setField(this, 5, value);
        }
        get active_jobs() {
            return pb_1.Message.getFieldWithDefault(this, 6, 0) as number;
        }
        set active_jobs(value: number) {
            pb_1.Message.setField(this, 6, value);
        }
        get capabilities() {
            return pb_1.Message.getFieldWithDefault(this, 7, []) as string[];
        }
        set capabilities(value: string[]) {
            pb_1.Message.setField(this, 7, value);
        }
        get pool() {
            return pb_1.Message.getFieldWithDefault(this, 11, "") as string;
        }
        set pool(value: string) {
            pb_1.Message.setField(this, 11, value);
        }
        get max_parallel_jobs() {
            return pb_1.Message.getFieldWithDefault(this, 12, 0) as number;
        }
        set max_parallel_jobs(value: number) {
            pb_1.Message.setField(this, 12, value);
        }
        static fromObject(data: {
            worker_id?: string;
            region?: string;
            type?: string;
            cpu_load?: number;
            gpu_utilization?: number;
            active_jobs?: number;
            capabilities?: string[];
            pool?: string;
            max_parallel_jobs?: number;
        }): Heartbeat {
            const message = new Heartbeat({});
            if (data.worker_id != null) {
                message.worker_id = data.worker_id;
            }
            if (data.region != null) {
                message.region = data.region;
            }
            if (data.type != null) {
                message.type = data.type;
            }
            if (data.cpu_load != null) {
                message.cpu_load = data.cpu_load;
            }
            if (data.gpu_utilization != null) {
                message.gpu_utilization = data.gpu_utilization;
            }
            if (data.active_jobs != null) {
                message.active_jobs = data.active_jobs;
            }
            if (data.capabilities != null) {
                message.capabilities = data.capabilities;
            }
            if (data.pool != null) {
                message.pool = data.pool;
            }
            if (data.max_parallel_jobs != null) {
                message.max_parallel_jobs = data.max_parallel_jobs;
            }
            return message;
        }
        toObject() {
            const data: {
                worker_id?: string;
                region?: string;
                type?: string;
                cpu_load?: number;
                gpu_utilization?: number;
                active_jobs?: number;
                capabilities?: string[];
                pool?: string;
                max_parallel_jobs?: number;
            } = {};
            if (this.worker_id != null) {
                data.worker_id = this.worker_id;
            }
            if (this.region != null) {
                data.region = this.region;
            }
            if (this.type != null) {
                data.type = this.type;
            }
            if (this.cpu_load != null) {
                data.cpu_load = this.cpu_load;
            }
            if (this.gpu_utilization != null) {
                data.gpu_utilization = this.gpu_utilization;
            }
            if (this.active_jobs != null) {
                data.active_jobs = this.active_jobs;
            }
            if (this.capabilities != null) {
                data.capabilities = this.capabilities;
            }
            if (this.pool != null) {
                data.pool = this.pool;
            }
            if (this.max_parallel_jobs != null) {
                data.max_parallel_jobs = this.max_parallel_jobs;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.worker_id.length)
                writer.writeString(1, this.worker_id);
            if (this.region.length)
                writer.writeString(2, this.region);
            if (this.type.length)
                writer.writeString(3, this.type);
            if (this.cpu_load != 0)
                writer.writeFloat(4, this.cpu_load);
            if (this.gpu_utilization != 0)
                writer.writeFloat(5, this.gpu_utilization);
            if (this.active_jobs != 0)
                writer.writeInt32(6, this.active_jobs);
            if (this.capabilities.length)
                writer.writeRepeatedString(7, this.capabilities);
            if (this.pool.length)
                writer.writeString(11, this.pool);
            if (this.max_parallel_jobs != 0)
                writer.writeInt32(12, this.max_parallel_jobs);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Heartbeat {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Heartbeat();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.worker_id = reader.readString();
                        break;
                    case 2:
                        message.region = reader.readString();
                        break;
                    case 3:
                        message.type = reader.readString();
                        break;
                    case 4:
                        message.cpu_load = reader.readFloat();
                        break;
                    case 5:
                        message.gpu_utilization = reader.readFloat();
                        break;
                    case 6:
                        message.active_jobs = reader.readInt32();
                        break;
                    case 7:
                        pb_1.Message.addToRepeatedField(message, 7, reader.readString());
                        break;
                    case 11:
                        message.pool = reader.readString();
                        break;
                    case 12:
                        message.max_parallel_jobs = reader.readInt32();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Heartbeat {
            return Heartbeat.deserialize(bytes);
        }
    }
}
