// source: coretex/agent/v1/job.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.coretex.agent.v1.Budget', null, global);
goog.exportSymbol('proto.coretex.agent.v1.ContextHints', null, global);
goog.exportSymbol('proto.coretex.agent.v1.JobPriority', null, global);
goog.exportSymbol('proto.coretex.agent.v1.JobRequest', null, global);
goog.exportSymbol('proto.coretex.agent.v1.JobResult', null, global);
goog.exportSymbol('proto.coretex.agent.v1.JobStatus', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.coretex.agent.v1.ContextHints = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.coretex.agent.v1.ContextHints.repeatedFields_, null);
};
goog.inherits(proto.coretex.agent.v1.ContextHints, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.coretex.agent.v1.ContextHints.displayName = 'proto.coretex.agent.v1.ContextHints';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.coretex.agent.v1.Budget = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.coretex.agent.v1.Budget, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.coretex.agent.v1.Budget.displayName = 'proto.coretex.agent.v1.Budget';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.coretex.agent.v1.JobRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.coretex.agent.v1.JobRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.coretex.agent.v1.JobRequest.displayName = 'proto.coretex.agent.v1.JobRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.coretex.agent.v1.JobResult = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.coretex.agent.v1.JobResult, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.coretex.agent.v1.JobResult.displayName = 'proto.coretex.agent.v1.JobResult';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.coretex.agent.v1.ContextHints.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.coretex.agent.v1.ContextHints.prototype.toObject = function(opt_includeInstance) {
  return proto.coretex.agent.v1.ContextHints.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.coretex.agent.v1.ContextHints} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.coretex.agent.v1.ContextHints.toObject = function(includeInstance, msg) {
  var f, obj = {
maxInputTokens: jspb.Message.getFieldWithDefault(msg, 1, 0),
allowSummarization: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
allowRetrieval: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
tagsList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.coretex.agent.v1.ContextHints}
 */
proto.coretex.agent.v1.ContextHints.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.coretex.agent.v1.ContextHints;
  return proto.coretex.agent.v1.ContextHints.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.coretex.agent.v1.ContextHints} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.coretex.agent.v1.ContextHints}
 */
proto.coretex.agent.v1.ContextHints.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMaxInputTokens(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAllowSummarization(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAllowRetrieval(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.addTags(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.coretex.agent.v1.ContextHints.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.coretex.agent.v1.ContextHints.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.coretex.agent.v1.ContextHints} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.coretex.agent.v1.ContextHints.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMaxInputTokens();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getAllowSummarization();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getAllowRetrieval();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getTagsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      4,
      f
    );
  }
};


/**
 * optional int32 max_input_tokens = 1;
 * @return {number}
 */
proto.coretex.agent.v1.ContextHints.prototype.getMaxInputTokens = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.coretex.agent.v1.ContextHints} returns this
 */
proto.coretex.agent.v1.ContextHints.prototype.setMaxInputTokens = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional bool allow_summarization = 2;
 * @return {boolean}
 */
proto.coretex.agent.v1.ContextHints.prototype.getAllowSummarization = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.coretex.agent.v1.ContextHints} returns this
 */
proto.coretex.agent.v1.ContextHints.prototype.setAllowSummarization = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional bool allow_retrieval = 3;
 * @return {boolean}
 */
proto.coretex.agent.v1.ContextHints.prototype.getAllowRetrieval = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.coretex.agent.v1.ContextHints} returns this
 */
proto.coretex.agent.v1.ContextHints.prototype.setAllowRetrieval = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * repeated string tags = 4;
 * @return {!Array<string>}
 */
proto.coretex.agent.v1.ContextHints.prototype.getTagsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.coretex.agent.v1.ContextHints} returns this
 */
proto.coretex.agent.v1.ContextHints.prototype.setTagsList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.coretex.agent.v1.ContextHints} returns this
 */
proto.coretex.agent.v1.ContextHints.prototype.addTags = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.coretex.agent.v1.ContextHints} returns this
 */
proto.coretex.agent.v1.ContextHints.prototype.clearTagsList = function() {
  return this.setTagsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.coretex.agent.v1.Budget.prototype.toObject = function(opt_includeInstance) {
  return proto.coretex.agent.v1.Budget.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.coretex.agent.v1.Budget} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.coretex.agent.v1.Budget.toObject = function(includeInstance, msg) {
  var f, obj = {
maxInputTokens: jspb.Message.getFieldWithDefault(msg, 1, 0),
maxOutputTokens: jspb.Message.getFieldWithDefault(msg, 2, 0),
maxTotalTokens: jspb.Message.getFieldWithDefault(msg, 3, 0),
deadlineMs: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.coretex.agent.v1.Budget}
 */
proto.coretex.agent.v1.Budget.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.coretex.agent.v1.Budget;
  return proto.coretex.agent.v1.Budget.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.coretex.agent.v1.Budget} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.coretex.agent.v1.Budget}
 */
proto.coretex.agent.v1.Budget.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setMaxInputTokens(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setMaxOutputTokens(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setMaxTotalTokens(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDeadlineMs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.coretex.agent.v1.Budget.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.coretex.agent.v1.Budget.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.coretex.agent.v1.Budget} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.coretex.agent.v1.Budget.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMaxInputTokens();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getMaxOutputTokens();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getMaxTotalTokens();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getDeadlineMs();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
};


/**
 * optional int64 max_input_tokens = 1;
 * @return {number}
 */
proto.coretex.agent.v1.Budget.prototype.getMaxInputTokens = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.coretex.agent.v1.Budget} returns this
 */
proto.coretex.agent.v1.Budget.prototype.setMaxInputTokens = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 max_output_tokens = 2;
 * @return {number}
 */
proto.coretex.agent.v1.Budget.prototype.getMaxOutputTokens = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.coretex.agent.v1.Budget} returns this
 */
proto.coretex.agent.v1.Budget.prototype.setMaxOutputTokens = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 max_total_tokens = 3;
 * @return {number}
 */
proto.coretex.agent.v1.Budget.prototype.getMaxTotalTokens = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.coretex.agent.v1.Budget} returns this
 */
proto.coretex.agent.v1.Budget.prototype.setMaxTotalTokens = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int64 deadline_ms = 4;
 * @return {number}
 */
proto.coretex.agent.v1.Budget.prototype.getDeadlineMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.coretex.agent.v1.Budget} returns this
 */
proto.coretex.agent.v1.Budget.prototype.setDeadlineMs = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.coretex.agent.v1.JobRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.coretex.agent.v1.JobRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.coretex.agent.v1.JobRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.coretex.agent.v1.JobRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
jobId: jspb.Message.getFieldWithDefault(msg, 1, ""),
topic: jspb.Message.getFieldWithDefault(msg, 2, ""),
priority: jspb.Message.getFieldWithDefault(msg, 3, 0),
contextPtr: jspb.Message.getFieldWithDefault(msg, 4, ""),
adapterId: jspb.Message.getFieldWithDefault(msg, 5, ""),
envMap: (f = msg.getEnvMap()) ? f.toObject(includeInstance, undefined) : [],
parentJobId: jspb.Message.getFieldWithDefault(msg, 7, ""),
workflowId: jspb.Message.getFieldWithDefault(msg, 8, ""),
stepIndex: jspb.Message.getFieldWithDefault(msg, 9, 0),
memoryId: jspb.Message.getFieldWithDefault(msg, 10, ""),
contextHints: (f = msg.getContextHints()) && proto.coretex.agent.v1.ContextHints.toObject(includeInstance, f),
budget: (f = msg.getBudget()) && proto.coretex.agent.v1.Budget.toObject(includeInstance, f),
tenantId: jspb.Message.getFieldWithDefault(msg, 13, ""),
principalId: jspb.Message.getFieldWithDefault(msg, 14, ""),
labelsMap: (f = msg.getLabelsMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.coretex.agent.v1.JobRequest}
 */
proto.coretex.agent.v1.JobRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.coretex.agent.v1.JobRequest;
  return proto.coretex.agent.v1.JobRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.coretex.agent.v1.JobRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.coretex.agent.v1.JobRequest}
 */
proto.coretex.agent.v1.JobRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setJobId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTopic(value);
      break;
    case 3:
      var value = /** @type {!proto.coretex.agent.v1.JobPriority} */ (reader.readEnum());
      msg.setPriority(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setContextPtr(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setAdapterId(value);
      break;
    case 6:
      var value = msg.getEnvMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setParentJobId(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setWorkflowId(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setStepIndex(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setMemoryId(value);
      break;
    case 11:
      var value = new proto.coretex.agent.v1.ContextHints;
      reader.readMessage(value,proto.coretex.agent.v1.ContextHints.deserializeBinaryFromReader);
      msg.setContextHints(value);
      break;
    case 12:
      var value = new proto.coretex.agent.v1.Budget;
      reader.readMessage(value,proto.coretex.agent.v1.Budget.deserializeBinaryFromReader);
      msg.setBudget(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setTenantId(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setPrincipalId(value);
      break;
    case 15:
      var value = msg.getLabelsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.coretex.agent.v1.JobRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.coretex.agent.v1.JobRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.coretex.agent.v1.JobRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.coretex.agent.v1.JobRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getJobId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTopic();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPriority();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getContextPtr();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getAdapterId();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getEnvMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(6, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getParentJobId();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getWorkflowId();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getStepIndex();
  if (f !== 0) {
    writer.writeInt32(
      9,
      f
    );
  }
  f = message.getMemoryId();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getContextHints();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      proto.coretex.agent.v1.ContextHints.serializeBinaryToWriter
    );
  }
  f = message.getBudget();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      proto.coretex.agent.v1.Budget.serializeBinaryToWriter
    );
  }
  f = message.getTenantId();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getPrincipalId();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
  f = message.getLabelsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(15, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * optional string job_id = 1;
 * @return {string}
 */
proto.coretex.agent.v1.JobRequest.prototype.getJobId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.coretex.agent.v1.JobRequest} returns this
 */
proto.coretex.agent.v1.JobRequest.prototype.setJobId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string topic = 2;
 * @return {string}
 */
proto.coretex.agent.v1.JobRequest.prototype.getTopic = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.coretex.agent.v1.JobRequest} returns this
 */
proto.coretex.agent.v1.JobRequest.prototype.setTopic = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional JobPriority priority = 3;
 * @return {!proto.coretex.agent.v1.JobPriority}
 */
proto.coretex.agent.v1.JobRequest.prototype.getPriority = function() {
  return /** @type {!proto.coretex.agent.v1.JobPriority} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.coretex.agent.v1.JobPriority} value
 * @return {!proto.coretex.agent.v1.JobRequest} returns this
 */
proto.coretex.agent.v1.JobRequest.prototype.setPriority = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional string context_ptr = 4;
 * @return {string}
 */
proto.coretex.agent.v1.JobRequest.prototype.getContextPtr = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.coretex.agent.v1.JobRequest} returns this
 */
proto.coretex.agent.v1.JobRequest.prototype.setContextPtr = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string adapter_id = 5;
 * @return {string}
 */
proto.coretex.agent.v1.JobRequest.prototype.getAdapterId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.coretex.agent.v1.JobRequest} returns this
 */
proto.coretex.agent.v1.JobRequest.prototype.setAdapterId = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * map<string, string> env = 6;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.coretex.agent.v1.JobRequest.prototype.getEnvMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 6, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.coretex.agent.v1.JobRequest} returns this
 */
proto.coretex.agent.v1.JobRequest.prototype.clearEnvMap = function() {
  this.getEnvMap().clear();
  return this;
};


/**
 * optional string parent_job_id = 7;
 * @return {string}
 */
proto.coretex.agent.v1.JobRequest.prototype.getParentJobId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.coretex.agent.v1.JobRequest} returns this
 */
proto.coretex.agent.v1.JobRequest.prototype.setParentJobId = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string workflow_id = 8;
 * @return {string}
 */
proto.coretex.agent.v1.JobRequest.prototype.getWorkflowId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.coretex.agent.v1.JobRequest} returns this
 */
proto.coretex.agent.v1.JobRequest.prototype.setWorkflowId = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional int32 step_index = 9;
 * @return {number}
 */
proto.coretex.agent.v1.JobRequest.prototype.getStepIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.coretex.agent.v1.JobRequest} returns this
 */
proto.coretex.agent.v1.JobRequest.prototype.setStepIndex = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional string memory_id = 10;
 * @return {string}
 */
proto.coretex.agent.v1.JobRequest.prototype.getMemoryId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.coretex.agent.v1.JobRequest} returns this
 */
proto.coretex.agent.v1.JobRequest.prototype.setMemoryId = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional ContextHints context_hints = 11;
 * @return {?proto.coretex.agent.v1.ContextHints}
 */
proto.coretex.agent.v1.JobRequest.prototype.getContextHints = function() {
  return /** @type{?proto.coretex.agent.v1.ContextHints} */ (
    jspb.Message.getWrapperField(this, proto.coretex.agent.v1.ContextHints, 11));
};


/**
 * @param {?proto.coretex.agent.v1.ContextHints|undefined} value
 * @return {!proto.coretex.agent.v1.JobRequest} returns this
*/
proto.coretex.agent.v1.JobRequest.prototype.setContextHints = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.coretex.agent.v1.JobRequest} returns this
 */
proto.coretex.agent.v1.JobRequest.prototype.clearContextHints = function() {
  return this.setContextHints(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.coretex.agent.v1.JobRequest.prototype.hasContextHints = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional Budget budget = 12;
 * @return {?proto.coretex.agent.v1.Budget}
 */
proto.coretex.agent.v1.JobRequest.prototype.getBudget = function() {
  return /** @type{?proto.coretex.agent.v1.Budget} */ (
    jspb.Message.getWrapperField(this, proto.coretex.agent.v1.Budget, 12));
};


/**
 * @param {?proto.coretex.agent.v1.Budget|undefined} value
 * @return {!proto.coretex.agent.v1.JobRequest} returns this
*/
proto.coretex.agent.v1.JobRequest.prototype.setBudget = function(value) {
  return jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.coretex.agent.v1.JobRequest} returns this
 */
proto.coretex.agent.v1.JobRequest.prototype.clearBudget = function() {
  return this.setBudget(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.coretex.agent.v1.JobRequest.prototype.hasBudget = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional string tenant_id = 13;
 * @return {string}
 */
proto.coretex.agent.v1.JobRequest.prototype.getTenantId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.coretex.agent.v1.JobRequest} returns this
 */
proto.coretex.agent.v1.JobRequest.prototype.setTenantId = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional string principal_id = 14;
 * @return {string}
 */
proto.coretex.agent.v1.JobRequest.prototype.getPrincipalId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * @param {string} value
 * @return {!proto.coretex.agent.v1.JobRequest} returns this
 */
proto.coretex.agent.v1.JobRequest.prototype.setPrincipalId = function(value) {
  return jspb.Message.setProto3StringField(this, 14, value);
};


/**
 * map<string, string> labels = 15;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.coretex.agent.v1.JobRequest.prototype.getLabelsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 15, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.coretex.agent.v1.JobRequest} returns this
 */
proto.coretex.agent.v1.JobRequest.prototype.clearLabelsMap = function() {
  this.getLabelsMap().clear();
  return this;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.coretex.agent.v1.JobResult.prototype.toObject = function(opt_includeInstance) {
  return proto.coretex.agent.v1.JobResult.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.coretex.agent.v1.JobResult} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.coretex.agent.v1.JobResult.toObject = function(includeInstance, msg) {
  var f, obj = {
jobId: jspb.Message.getFieldWithDefault(msg, 1, ""),
status: jspb.Message.getFieldWithDefault(msg, 2, 0),
resultPtr: jspb.Message.getFieldWithDefault(msg, 3, ""),
workerId: jspb.Message.getFieldWithDefault(msg, 4, ""),
executionMs: jspb.Message.getFieldWithDefault(msg, 5, 0),
errorCode: jspb.Message.getFieldWithDefault(msg, 6, ""),
errorMessage: jspb.Message.getFieldWithDefault(msg, 7, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.coretex.agent.v1.JobResult}
 */
proto.coretex.agent.v1.JobResult.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.coretex.agent.v1.JobResult;
  return proto.coretex.agent.v1.JobResult.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.coretex.agent.v1.JobResult} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.coretex.agent.v1.JobResult}
 */
proto.coretex.agent.v1.JobResult.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setJobId(value);
      break;
    case 2:
      var value = /** @type {!proto.coretex.agent.v1.JobStatus} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setResultPtr(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setWorkerId(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setExecutionMs(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setErrorCode(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setErrorMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.coretex.agent.v1.JobResult.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.coretex.agent.v1.JobResult.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.coretex.agent.v1.JobResult} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.coretex.agent.v1.JobResult.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getJobId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getResultPtr();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getWorkerId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getExecutionMs();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getErrorCode();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getErrorMessage();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * optional string job_id = 1;
 * @return {string}
 */
proto.coretex.agent.v1.JobResult.prototype.getJobId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.coretex.agent.v1.JobResult} returns this
 */
proto.coretex.agent.v1.JobResult.prototype.setJobId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional JobStatus status = 2;
 * @return {!proto.coretex.agent.v1.JobStatus}
 */
proto.coretex.agent.v1.JobResult.prototype.getStatus = function() {
  return /** @type {!proto.coretex.agent.v1.JobStatus} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.coretex.agent.v1.JobStatus} value
 * @return {!proto.coretex.agent.v1.JobResult} returns this
 */
proto.coretex.agent.v1.JobResult.prototype.setStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional string result_ptr = 3;
 * @return {string}
 */
proto.coretex.agent.v1.JobResult.prototype.getResultPtr = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.coretex.agent.v1.JobResult} returns this
 */
proto.coretex.agent.v1.JobResult.prototype.setResultPtr = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string worker_id = 4;
 * @return {string}
 */
proto.coretex.agent.v1.JobResult.prototype.getWorkerId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.coretex.agent.v1.JobResult} returns this
 */
proto.coretex.agent.v1.JobResult.prototype.setWorkerId = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int64 execution_ms = 5;
 * @return {number}
 */
proto.coretex.agent.v1.JobResult.prototype.getExecutionMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.coretex.agent.v1.JobResult} returns this
 */
proto.coretex.agent.v1.JobResult.prototype.setExecutionMs = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional string error_code = 6;
 * @return {string}
 */
proto.coretex.agent.v1.JobResult.prototype.getErrorCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.coretex.agent.v1.JobResult} returns this
 */
proto.coretex.agent.v1.JobResult.prototype.setErrorCode = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string error_message = 7;
 * @return {string}
 */
proto.coretex.agent.v1.JobResult.prototype.getErrorMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.coretex.agent.v1.JobResult} returns this
 */
proto.coretex.agent.v1.JobResult.prototype.setErrorMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * @enum {number}
 */
proto.coretex.agent.v1.JobPriority = {
  JOB_PRIORITY_UNSPECIFIED: 0,
  JOB_PRIORITY_INTERACTIVE: 1,
  JOB_PRIORITY_BATCH: 2,
  JOB_PRIORITY_CRITICAL: 3
};

/**
 * @enum {number}
 */
proto.coretex.agent.v1.JobStatus = {
  JOB_STATUS_UNSPECIFIED: 0,
  JOB_STATUS_PENDING: 1,
  JOB_STATUS_SCHEDULED: 2,
  JOB_STATUS_DISPATCHED: 3,
  JOB_STATUS_RUNNING: 4,
  JOB_STATUS_SUCCEEDED: 5,
  JOB_STATUS_FAILED: 6,
  JOB_STATUS_CANCELLED: 7,
  JOB_STATUS_DENIED: 8,
  JOB_STATUS_TIMEOUT: 9
};

goog.object.extend(exports, proto.coretex.agent.v1);
