/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.19.1
 * source: coretex/agent/v1/safety.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./job";
import * as pb_1 from "google-protobuf";
import * as grpc_1 from "@grpc/grpc-js";
export namespace coretex.agent.v1 {
    export enum DecisionType {
        DECISION_TYPE_UNSPECIFIED = 0,
        DECISION_TYPE_ALLOW = 1,
        DECISION_TYPE_DENY = 2,
        DECISION_TYPE_REQUIRE_HUMAN = 3,
        DECISION_TYPE_THROTTLE = 4
    }
    export class PolicyCheckRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            job_id?: string;
            topic?: string;
            tenant?: string;
            priority?: dependency_1.coretex.agent.v1.JobPriority;
            estimated_cost?: number;
            budget?: dependency_1.coretex.agent.v1.Budget;
            principal_id?: string;
            labels?: Map<string, string>;
            memory_id?: string;
            effective_config?: Uint8Array;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("job_id" in data && data.job_id != undefined) {
                    this.job_id = data.job_id;
                }
                if ("topic" in data && data.topic != undefined) {
                    this.topic = data.topic;
                }
                if ("tenant" in data && data.tenant != undefined) {
                    this.tenant = data.tenant;
                }
                if ("priority" in data && data.priority != undefined) {
                    this.priority = data.priority;
                }
                if ("estimated_cost" in data && data.estimated_cost != undefined) {
                    this.estimated_cost = data.estimated_cost;
                }
                if ("budget" in data && data.budget != undefined) {
                    this.budget = data.budget;
                }
                if ("principal_id" in data && data.principal_id != undefined) {
                    this.principal_id = data.principal_id;
                }
                if ("labels" in data && data.labels != undefined) {
                    this.labels = data.labels;
                }
                if ("memory_id" in data && data.memory_id != undefined) {
                    this.memory_id = data.memory_id;
                }
                if ("effective_config" in data && data.effective_config != undefined) {
                    this.effective_config = data.effective_config;
                }
            }
            if (!this.labels)
                this.labels = new Map();
        }
        get job_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set job_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get topic() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set topic(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get tenant() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set tenant(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get priority() {
            return pb_1.Message.getFieldWithDefault(this, 4, dependency_1.coretex.agent.v1.JobPriority.JOB_PRIORITY_UNSPECIFIED) as dependency_1.coretex.agent.v1.JobPriority;
        }
        set priority(value: dependency_1.coretex.agent.v1.JobPriority) {
            pb_1.Message.setField(this, 4, value);
        }
        get estimated_cost() {
            return pb_1.Message.getFieldWithDefault(this, 5, 0) as number;
        }
        set estimated_cost(value: number) {
            pb_1.Message.setField(this, 5, value);
        }
        get budget() {
            return pb_1.Message.getWrapperField(this, dependency_1.coretex.agent.v1.Budget, 6) as dependency_1.coretex.agent.v1.Budget;
        }
        set budget(value: dependency_1.coretex.agent.v1.Budget) {
            pb_1.Message.setWrapperField(this, 6, value);
        }
        get has_budget() {
            return pb_1.Message.getField(this, 6) != null;
        }
        get principal_id() {
            return pb_1.Message.getFieldWithDefault(this, 7, "") as string;
        }
        set principal_id(value: string) {
            pb_1.Message.setField(this, 7, value);
        }
        get labels() {
            return pb_1.Message.getField(this, 8) as any as Map<string, string>;
        }
        set labels(value: Map<string, string>) {
            pb_1.Message.setField(this, 8, value as any);
        }
        get memory_id() {
            return pb_1.Message.getFieldWithDefault(this, 9, "") as string;
        }
        set memory_id(value: string) {
            pb_1.Message.setField(this, 9, value);
        }
        get effective_config() {
            return pb_1.Message.getFieldWithDefault(this, 10, new Uint8Array(0)) as Uint8Array;
        }
        set effective_config(value: Uint8Array) {
            pb_1.Message.setField(this, 10, value);
        }
        static fromObject(data: {
            job_id?: string;
            topic?: string;
            tenant?: string;
            priority?: dependency_1.coretex.agent.v1.JobPriority;
            estimated_cost?: number;
            budget?: ReturnType<typeof dependency_1.coretex.agent.v1.Budget.prototype.toObject>;
            principal_id?: string;
            labels?: {
                [key: string]: string;
            };
            memory_id?: string;
            effective_config?: Uint8Array;
        }): PolicyCheckRequest {
            const message = new PolicyCheckRequest({});
            if (data.job_id != null) {
                message.job_id = data.job_id;
            }
            if (data.topic != null) {
                message.topic = data.topic;
            }
            if (data.tenant != null) {
                message.tenant = data.tenant;
            }
            if (data.priority != null) {
                message.priority = data.priority;
            }
            if (data.estimated_cost != null) {
                message.estimated_cost = data.estimated_cost;
            }
            if (data.budget != null) {
                message.budget = dependency_1.coretex.agent.v1.Budget.fromObject(data.budget);
            }
            if (data.principal_id != null) {
                message.principal_id = data.principal_id;
            }
            if (typeof data.labels == "object") {
                message.labels = new Map(Object.entries(data.labels));
            }
            if (data.memory_id != null) {
                message.memory_id = data.memory_id;
            }
            if (data.effective_config != null) {
                message.effective_config = data.effective_config;
            }
            return message;
        }
        toObject() {
            const data: {
                job_id?: string;
                topic?: string;
                tenant?: string;
                priority?: dependency_1.coretex.agent.v1.JobPriority;
                estimated_cost?: number;
                budget?: ReturnType<typeof dependency_1.coretex.agent.v1.Budget.prototype.toObject>;
                principal_id?: string;
                labels?: {
                    [key: string]: string;
                };
                memory_id?: string;
                effective_config?: Uint8Array;
            } = {};
            if (this.job_id != null) {
                data.job_id = this.job_id;
            }
            if (this.topic != null) {
                data.topic = this.topic;
            }
            if (this.tenant != null) {
                data.tenant = this.tenant;
            }
            if (this.priority != null) {
                data.priority = this.priority;
            }
            if (this.estimated_cost != null) {
                data.estimated_cost = this.estimated_cost;
            }
            if (this.budget != null) {
                data.budget = this.budget.toObject();
            }
            if (this.principal_id != null) {
                data.principal_id = this.principal_id;
            }
            if (this.labels != null) {
                data.labels = (Object.fromEntries)(this.labels);
            }
            if (this.memory_id != null) {
                data.memory_id = this.memory_id;
            }
            if (this.effective_config != null) {
                data.effective_config = this.effective_config;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.job_id.length)
                writer.writeString(1, this.job_id);
            if (this.topic.length)
                writer.writeString(2, this.topic);
            if (this.tenant.length)
                writer.writeString(3, this.tenant);
            if (this.priority != dependency_1.coretex.agent.v1.JobPriority.JOB_PRIORITY_UNSPECIFIED)
                writer.writeEnum(4, this.priority);
            if (this.estimated_cost != 0)
                writer.writeDouble(5, this.estimated_cost);
            if (this.has_budget)
                writer.writeMessage(6, this.budget, () => this.budget.serialize(writer));
            if (this.principal_id.length)
                writer.writeString(7, this.principal_id);
            for (const [key, value] of this.labels) {
                writer.writeMessage(8, this.labels, () => {
                    writer.writeString(1, key);
                    writer.writeString(2, value);
                });
            }
            if (this.memory_id.length)
                writer.writeString(9, this.memory_id);
            if (this.effective_config.length)
                writer.writeBytes(10, this.effective_config);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): PolicyCheckRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new PolicyCheckRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.job_id = reader.readString();
                        break;
                    case 2:
                        message.topic = reader.readString();
                        break;
                    case 3:
                        message.tenant = reader.readString();
                        break;
                    case 4:
                        message.priority = reader.readEnum();
                        break;
                    case 5:
                        message.estimated_cost = reader.readDouble();
                        break;
                    case 6:
                        reader.readMessage(message.budget, () => message.budget = dependency_1.coretex.agent.v1.Budget.deserialize(reader));
                        break;
                    case 7:
                        message.principal_id = reader.readString();
                        break;
                    case 8:
                        reader.readMessage(message, () => pb_1.Map.deserializeBinary(message.labels as any, reader, reader.readString, reader.readString));
                        break;
                    case 9:
                        message.memory_id = reader.readString();
                        break;
                    case 10:
                        message.effective_config = reader.readBytes();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): PolicyCheckRequest {
            return PolicyCheckRequest.deserialize(bytes);
        }
    }
    export class BudgetConstraints extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            max_runtime_ms?: number;
            max_retries?: number;
            max_artifact_bytes?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("max_runtime_ms" in data && data.max_runtime_ms != undefined) {
                    this.max_runtime_ms = data.max_runtime_ms;
                }
                if ("max_retries" in data && data.max_retries != undefined) {
                    this.max_retries = data.max_retries;
                }
                if ("max_artifact_bytes" in data && data.max_artifact_bytes != undefined) {
                    this.max_artifact_bytes = data.max_artifact_bytes;
                }
            }
        }
        get max_runtime_ms() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set max_runtime_ms(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        get max_retries() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set max_retries(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        get max_artifact_bytes() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set max_artifact_bytes(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        static fromObject(data: {
            max_runtime_ms?: number;
            max_retries?: number;
            max_artifact_bytes?: number;
        }): BudgetConstraints {
            const message = new BudgetConstraints({});
            if (data.max_runtime_ms != null) {
                message.max_runtime_ms = data.max_runtime_ms;
            }
            if (data.max_retries != null) {
                message.max_retries = data.max_retries;
            }
            if (data.max_artifact_bytes != null) {
                message.max_artifact_bytes = data.max_artifact_bytes;
            }
            return message;
        }
        toObject() {
            const data: {
                max_runtime_ms?: number;
                max_retries?: number;
                max_artifact_bytes?: number;
            } = {};
            if (this.max_runtime_ms != null) {
                data.max_runtime_ms = this.max_runtime_ms;
            }
            if (this.max_retries != null) {
                data.max_retries = this.max_retries;
            }
            if (this.max_artifact_bytes != null) {
                data.max_artifact_bytes = this.max_artifact_bytes;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.max_runtime_ms != 0)
                writer.writeInt64(1, this.max_runtime_ms);
            if (this.max_retries != 0)
                writer.writeInt32(2, this.max_retries);
            if (this.max_artifact_bytes != 0)
                writer.writeInt64(3, this.max_artifact_bytes);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): BudgetConstraints {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new BudgetConstraints();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.max_runtime_ms = reader.readInt64();
                        break;
                    case 2:
                        message.max_retries = reader.readInt32();
                        break;
                    case 3:
                        message.max_artifact_bytes = reader.readInt64();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): BudgetConstraints {
            return BudgetConstraints.deserialize(bytes);
        }
    }
    export class SandboxProfile extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            isolated?: boolean;
            network_allowlist?: string[];
            fs_read_only?: string[];
            fs_read_write?: string[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2, 3, 4], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("isolated" in data && data.isolated != undefined) {
                    this.isolated = data.isolated;
                }
                if ("network_allowlist" in data && data.network_allowlist != undefined) {
                    this.network_allowlist = data.network_allowlist;
                }
                if ("fs_read_only" in data && data.fs_read_only != undefined) {
                    this.fs_read_only = data.fs_read_only;
                }
                if ("fs_read_write" in data && data.fs_read_write != undefined) {
                    this.fs_read_write = data.fs_read_write;
                }
            }
        }
        get isolated() {
            return pb_1.Message.getFieldWithDefault(this, 1, false) as boolean;
        }
        set isolated(value: boolean) {
            pb_1.Message.setField(this, 1, value);
        }
        get network_allowlist() {
            return pb_1.Message.getFieldWithDefault(this, 2, []) as string[];
        }
        set network_allowlist(value: string[]) {
            pb_1.Message.setField(this, 2, value);
        }
        get fs_read_only() {
            return pb_1.Message.getFieldWithDefault(this, 3, []) as string[];
        }
        set fs_read_only(value: string[]) {
            pb_1.Message.setField(this, 3, value);
        }
        get fs_read_write() {
            return pb_1.Message.getFieldWithDefault(this, 4, []) as string[];
        }
        set fs_read_write(value: string[]) {
            pb_1.Message.setField(this, 4, value);
        }
        static fromObject(data: {
            isolated?: boolean;
            network_allowlist?: string[];
            fs_read_only?: string[];
            fs_read_write?: string[];
        }): SandboxProfile {
            const message = new SandboxProfile({});
            if (data.isolated != null) {
                message.isolated = data.isolated;
            }
            if (data.network_allowlist != null) {
                message.network_allowlist = data.network_allowlist;
            }
            if (data.fs_read_only != null) {
                message.fs_read_only = data.fs_read_only;
            }
            if (data.fs_read_write != null) {
                message.fs_read_write = data.fs_read_write;
            }
            return message;
        }
        toObject() {
            const data: {
                isolated?: boolean;
                network_allowlist?: string[];
                fs_read_only?: string[];
                fs_read_write?: string[];
            } = {};
            if (this.isolated != null) {
                data.isolated = this.isolated;
            }
            if (this.network_allowlist != null) {
                data.network_allowlist = this.network_allowlist;
            }
            if (this.fs_read_only != null) {
                data.fs_read_only = this.fs_read_only;
            }
            if (this.fs_read_write != null) {
                data.fs_read_write = this.fs_read_write;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.isolated != false)
                writer.writeBool(1, this.isolated);
            if (this.network_allowlist.length)
                writer.writeRepeatedString(2, this.network_allowlist);
            if (this.fs_read_only.length)
                writer.writeRepeatedString(3, this.fs_read_only);
            if (this.fs_read_write.length)
                writer.writeRepeatedString(4, this.fs_read_write);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SandboxProfile {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new SandboxProfile();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.isolated = reader.readBool();
                        break;
                    case 2:
                        pb_1.Message.addToRepeatedField(message, 2, reader.readString());
                        break;
                    case 3:
                        pb_1.Message.addToRepeatedField(message, 3, reader.readString());
                        break;
                    case 4:
                        pb_1.Message.addToRepeatedField(message, 4, reader.readString());
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): SandboxProfile {
            return SandboxProfile.deserialize(bytes);
        }
    }
    export class ToolchainConstraints extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            allowed_tools?: string[];
            allowed_commands?: string[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1, 2], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("allowed_tools" in data && data.allowed_tools != undefined) {
                    this.allowed_tools = data.allowed_tools;
                }
                if ("allowed_commands" in data && data.allowed_commands != undefined) {
                    this.allowed_commands = data.allowed_commands;
                }
            }
        }
        get allowed_tools() {
            return pb_1.Message.getFieldWithDefault(this, 1, []) as string[];
        }
        set allowed_tools(value: string[]) {
            pb_1.Message.setField(this, 1, value);
        }
        get allowed_commands() {
            return pb_1.Message.getFieldWithDefault(this, 2, []) as string[];
        }
        set allowed_commands(value: string[]) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            allowed_tools?: string[];
            allowed_commands?: string[];
        }): ToolchainConstraints {
            const message = new ToolchainConstraints({});
            if (data.allowed_tools != null) {
                message.allowed_tools = data.allowed_tools;
            }
            if (data.allowed_commands != null) {
                message.allowed_commands = data.allowed_commands;
            }
            return message;
        }
        toObject() {
            const data: {
                allowed_tools?: string[];
                allowed_commands?: string[];
            } = {};
            if (this.allowed_tools != null) {
                data.allowed_tools = this.allowed_tools;
            }
            if (this.allowed_commands != null) {
                data.allowed_commands = this.allowed_commands;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.allowed_tools.length)
                writer.writeRepeatedString(1, this.allowed_tools);
            if (this.allowed_commands.length)
                writer.writeRepeatedString(2, this.allowed_commands);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ToolchainConstraints {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ToolchainConstraints();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        pb_1.Message.addToRepeatedField(message, 1, reader.readString());
                        break;
                    case 2:
                        pb_1.Message.addToRepeatedField(message, 2, reader.readString());
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): ToolchainConstraints {
            return ToolchainConstraints.deserialize(bytes);
        }
    }
    export class DiffConstraints extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            max_files?: number;
            max_lines?: number;
            deny_path_globs?: string[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [3], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("max_files" in data && data.max_files != undefined) {
                    this.max_files = data.max_files;
                }
                if ("max_lines" in data && data.max_lines != undefined) {
                    this.max_lines = data.max_lines;
                }
                if ("deny_path_globs" in data && data.deny_path_globs != undefined) {
                    this.deny_path_globs = data.deny_path_globs;
                }
            }
        }
        get max_files() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set max_files(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        get max_lines() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set max_lines(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        get deny_path_globs() {
            return pb_1.Message.getFieldWithDefault(this, 3, []) as string[];
        }
        set deny_path_globs(value: string[]) {
            pb_1.Message.setField(this, 3, value);
        }
        static fromObject(data: {
            max_files?: number;
            max_lines?: number;
            deny_path_globs?: string[];
        }): DiffConstraints {
            const message = new DiffConstraints({});
            if (data.max_files != null) {
                message.max_files = data.max_files;
            }
            if (data.max_lines != null) {
                message.max_lines = data.max_lines;
            }
            if (data.deny_path_globs != null) {
                message.deny_path_globs = data.deny_path_globs;
            }
            return message;
        }
        toObject() {
            const data: {
                max_files?: number;
                max_lines?: number;
                deny_path_globs?: string[];
            } = {};
            if (this.max_files != null) {
                data.max_files = this.max_files;
            }
            if (this.max_lines != null) {
                data.max_lines = this.max_lines;
            }
            if (this.deny_path_globs != null) {
                data.deny_path_globs = this.deny_path_globs;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.max_files != 0)
                writer.writeInt32(1, this.max_files);
            if (this.max_lines != 0)
                writer.writeInt32(2, this.max_lines);
            if (this.deny_path_globs.length)
                writer.writeRepeatedString(3, this.deny_path_globs);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): DiffConstraints {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new DiffConstraints();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.max_files = reader.readInt32();
                        break;
                    case 2:
                        message.max_lines = reader.readInt32();
                        break;
                    case 3:
                        pb_1.Message.addToRepeatedField(message, 3, reader.readString());
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): DiffConstraints {
            return DiffConstraints.deserialize(bytes);
        }
    }
    export class PolicyConstraints extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            budgets?: BudgetConstraints;
            sandbox?: SandboxProfile;
            toolchain?: ToolchainConstraints;
            diff?: DiffConstraints;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("budgets" in data && data.budgets != undefined) {
                    this.budgets = data.budgets;
                }
                if ("sandbox" in data && data.sandbox != undefined) {
                    this.sandbox = data.sandbox;
                }
                if ("toolchain" in data && data.toolchain != undefined) {
                    this.toolchain = data.toolchain;
                }
                if ("diff" in data && data.diff != undefined) {
                    this.diff = data.diff;
                }
            }
        }
        get budgets() {
            return pb_1.Message.getWrapperField(this, BudgetConstraints, 1) as BudgetConstraints;
        }
        set budgets(value: BudgetConstraints) {
            pb_1.Message.setWrapperField(this, 1, value);
        }
        get has_budgets() {
            return pb_1.Message.getField(this, 1) != null;
        }
        get sandbox() {
            return pb_1.Message.getWrapperField(this, SandboxProfile, 2) as SandboxProfile;
        }
        set sandbox(value: SandboxProfile) {
            pb_1.Message.setWrapperField(this, 2, value);
        }
        get has_sandbox() {
            return pb_1.Message.getField(this, 2) != null;
        }
        get toolchain() {
            return pb_1.Message.getWrapperField(this, ToolchainConstraints, 3) as ToolchainConstraints;
        }
        set toolchain(value: ToolchainConstraints) {
            pb_1.Message.setWrapperField(this, 3, value);
        }
        get has_toolchain() {
            return pb_1.Message.getField(this, 3) != null;
        }
        get diff() {
            return pb_1.Message.getWrapperField(this, DiffConstraints, 4) as DiffConstraints;
        }
        set diff(value: DiffConstraints) {
            pb_1.Message.setWrapperField(this, 4, value);
        }
        get has_diff() {
            return pb_1.Message.getField(this, 4) != null;
        }
        static fromObject(data: {
            budgets?: ReturnType<typeof BudgetConstraints.prototype.toObject>;
            sandbox?: ReturnType<typeof SandboxProfile.prototype.toObject>;
            toolchain?: ReturnType<typeof ToolchainConstraints.prototype.toObject>;
            diff?: ReturnType<typeof DiffConstraints.prototype.toObject>;
        }): PolicyConstraints {
            const message = new PolicyConstraints({});
            if (data.budgets != null) {
                message.budgets = BudgetConstraints.fromObject(data.budgets);
            }
            if (data.sandbox != null) {
                message.sandbox = SandboxProfile.fromObject(data.sandbox);
            }
            if (data.toolchain != null) {
                message.toolchain = ToolchainConstraints.fromObject(data.toolchain);
            }
            if (data.diff != null) {
                message.diff = DiffConstraints.fromObject(data.diff);
            }
            return message;
        }
        toObject() {
            const data: {
                budgets?: ReturnType<typeof BudgetConstraints.prototype.toObject>;
                sandbox?: ReturnType<typeof SandboxProfile.prototype.toObject>;
                toolchain?: ReturnType<typeof ToolchainConstraints.prototype.toObject>;
                diff?: ReturnType<typeof DiffConstraints.prototype.toObject>;
            } = {};
            if (this.budgets != null) {
                data.budgets = this.budgets.toObject();
            }
            if (this.sandbox != null) {
                data.sandbox = this.sandbox.toObject();
            }
            if (this.toolchain != null) {
                data.toolchain = this.toolchain.toObject();
            }
            if (this.diff != null) {
                data.diff = this.diff.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.has_budgets)
                writer.writeMessage(1, this.budgets, () => this.budgets.serialize(writer));
            if (this.has_sandbox)
                writer.writeMessage(2, this.sandbox, () => this.sandbox.serialize(writer));
            if (this.has_toolchain)
                writer.writeMessage(3, this.toolchain, () => this.toolchain.serialize(writer));
            if (this.has_diff)
                writer.writeMessage(4, this.diff, () => this.diff.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): PolicyConstraints {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new PolicyConstraints();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.budgets, () => message.budgets = BudgetConstraints.deserialize(reader));
                        break;
                    case 2:
                        reader.readMessage(message.sandbox, () => message.sandbox = SandboxProfile.deserialize(reader));
                        break;
                    case 3:
                        reader.readMessage(message.toolchain, () => message.toolchain = ToolchainConstraints.deserialize(reader));
                        break;
                    case 4:
                        reader.readMessage(message.diff, () => message.diff = DiffConstraints.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): PolicyConstraints {
            return PolicyConstraints.deserialize(bytes);
        }
    }
    export class PolicyCheckResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            decision?: DecisionType;
            reason?: string;
            redacted_context_ptr?: string;
            policy_snapshot?: string;
            rule_id?: string;
            constraints?: PolicyConstraints;
            approval_required?: boolean;
            approval_ref?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("decision" in data && data.decision != undefined) {
                    this.decision = data.decision;
                }
                if ("reason" in data && data.reason != undefined) {
                    this.reason = data.reason;
                }
                if ("redacted_context_ptr" in data && data.redacted_context_ptr != undefined) {
                    this.redacted_context_ptr = data.redacted_context_ptr;
                }
                if ("policy_snapshot" in data && data.policy_snapshot != undefined) {
                    this.policy_snapshot = data.policy_snapshot;
                }
                if ("rule_id" in data && data.rule_id != undefined) {
                    this.rule_id = data.rule_id;
                }
                if ("constraints" in data && data.constraints != undefined) {
                    this.constraints = data.constraints;
                }
                if ("approval_required" in data && data.approval_required != undefined) {
                    this.approval_required = data.approval_required;
                }
                if ("approval_ref" in data && data.approval_ref != undefined) {
                    this.approval_ref = data.approval_ref;
                }
            }
        }
        get decision() {
            return pb_1.Message.getFieldWithDefault(this, 1, DecisionType.DECISION_TYPE_UNSPECIFIED) as DecisionType;
        }
        set decision(value: DecisionType) {
            pb_1.Message.setField(this, 1, value);
        }
        get reason() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set reason(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get redacted_context_ptr() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set redacted_context_ptr(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get policy_snapshot() {
            return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
        }
        set policy_snapshot(value: string) {
            pb_1.Message.setField(this, 4, value);
        }
        get rule_id() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set rule_id(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        get constraints() {
            return pb_1.Message.getWrapperField(this, PolicyConstraints, 6) as PolicyConstraints;
        }
        set constraints(value: PolicyConstraints) {
            pb_1.Message.setWrapperField(this, 6, value);
        }
        get has_constraints() {
            return pb_1.Message.getField(this, 6) != null;
        }
        get approval_required() {
            return pb_1.Message.getFieldWithDefault(this, 7, false) as boolean;
        }
        set approval_required(value: boolean) {
            pb_1.Message.setField(this, 7, value);
        }
        get approval_ref() {
            return pb_1.Message.getFieldWithDefault(this, 8, "") as string;
        }
        set approval_ref(value: string) {
            pb_1.Message.setField(this, 8, value);
        }
        static fromObject(data: {
            decision?: DecisionType;
            reason?: string;
            redacted_context_ptr?: string;
            policy_snapshot?: string;
            rule_id?: string;
            constraints?: ReturnType<typeof PolicyConstraints.prototype.toObject>;
            approval_required?: boolean;
            approval_ref?: string;
        }): PolicyCheckResponse {
            const message = new PolicyCheckResponse({});
            if (data.decision != null) {
                message.decision = data.decision;
            }
            if (data.reason != null) {
                message.reason = data.reason;
            }
            if (data.redacted_context_ptr != null) {
                message.redacted_context_ptr = data.redacted_context_ptr;
            }
            if (data.policy_snapshot != null) {
                message.policy_snapshot = data.policy_snapshot;
            }
            if (data.rule_id != null) {
                message.rule_id = data.rule_id;
            }
            if (data.constraints != null) {
                message.constraints = PolicyConstraints.fromObject(data.constraints);
            }
            if (data.approval_required != null) {
                message.approval_required = data.approval_required;
            }
            if (data.approval_ref != null) {
                message.approval_ref = data.approval_ref;
            }
            return message;
        }
        toObject() {
            const data: {
                decision?: DecisionType;
                reason?: string;
                redacted_context_ptr?: string;
                policy_snapshot?: string;
                rule_id?: string;
                constraints?: ReturnType<typeof PolicyConstraints.prototype.toObject>;
                approval_required?: boolean;
                approval_ref?: string;
            } = {};
            if (this.decision != null) {
                data.decision = this.decision;
            }
            if (this.reason != null) {
                data.reason = this.reason;
            }
            if (this.redacted_context_ptr != null) {
                data.redacted_context_ptr = this.redacted_context_ptr;
            }
            if (this.policy_snapshot != null) {
                data.policy_snapshot = this.policy_snapshot;
            }
            if (this.rule_id != null) {
                data.rule_id = this.rule_id;
            }
            if (this.constraints != null) {
                data.constraints = this.constraints.toObject();
            }
            if (this.approval_required != null) {
                data.approval_required = this.approval_required;
            }
            if (this.approval_ref != null) {
                data.approval_ref = this.approval_ref;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.decision != DecisionType.DECISION_TYPE_UNSPECIFIED)
                writer.writeEnum(1, this.decision);
            if (this.reason.length)
                writer.writeString(2, this.reason);
            if (this.redacted_context_ptr.length)
                writer.writeString(3, this.redacted_context_ptr);
            if (this.policy_snapshot.length)
                writer.writeString(4, this.policy_snapshot);
            if (this.rule_id.length)
                writer.writeString(5, this.rule_id);
            if (this.has_constraints)
                writer.writeMessage(6, this.constraints, () => this.constraints.serialize(writer));
            if (this.approval_required != false)
                writer.writeBool(7, this.approval_required);
            if (this.approval_ref.length)
                writer.writeString(8, this.approval_ref);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): PolicyCheckResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new PolicyCheckResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.decision = reader.readEnum();
                        break;
                    case 2:
                        message.reason = reader.readString();
                        break;
                    case 3:
                        message.redacted_context_ptr = reader.readString();
                        break;
                    case 4:
                        message.policy_snapshot = reader.readString();
                        break;
                    case 5:
                        message.rule_id = reader.readString();
                        break;
                    case 6:
                        reader.readMessage(message.constraints, () => message.constraints = PolicyConstraints.deserialize(reader));
                        break;
                    case 7:
                        message.approval_required = reader.readBool();
                        break;
                    case 8:
                        message.approval_ref = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): PolicyCheckResponse {
            return PolicyCheckResponse.deserialize(bytes);
        }
    }
    export class ListSnapshotsRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {}) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") { }
        }
        static fromObject(data: {}): ListSnapshotsRequest {
            const message = new ListSnapshotsRequest({});
            return message;
        }
        toObject() {
            const data: {} = {};
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ListSnapshotsRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ListSnapshotsRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): ListSnapshotsRequest {
            return ListSnapshotsRequest.deserialize(bytes);
        }
    }
    export class ListSnapshotsResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            snapshots?: string[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("snapshots" in data && data.snapshots != undefined) {
                    this.snapshots = data.snapshots;
                }
            }
        }
        get snapshots() {
            return pb_1.Message.getFieldWithDefault(this, 1, []) as string[];
        }
        set snapshots(value: string[]) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            snapshots?: string[];
        }): ListSnapshotsResponse {
            const message = new ListSnapshotsResponse({});
            if (data.snapshots != null) {
                message.snapshots = data.snapshots;
            }
            return message;
        }
        toObject() {
            const data: {
                snapshots?: string[];
            } = {};
            if (this.snapshots != null) {
                data.snapshots = this.snapshots;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.snapshots.length)
                writer.writeRepeatedString(1, this.snapshots);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ListSnapshotsResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ListSnapshotsResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        pb_1.Message.addToRepeatedField(message, 1, reader.readString());
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): ListSnapshotsResponse {
            return ListSnapshotsResponse.deserialize(bytes);
        }
    }
    interface GrpcUnaryServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    }
    interface GrpcStreamServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
        (message: P, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
    }
    interface GrpWritableServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    }
    interface GrpcChunkServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
        (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
    }
    interface GrpcPromiseServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): Promise<R>;
        (message: P, options?: grpc_1.CallOptions): Promise<R>;
    }
    export abstract class UnimplementedSafetyKernelService {
        static definition = {
            Check: {
                path: "/coretex.agent.v1.SafetyKernel/Check",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: PolicyCheckRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => PolicyCheckRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: PolicyCheckResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => PolicyCheckResponse.deserialize(new Uint8Array(bytes))
            },
            Evaluate: {
                path: "/coretex.agent.v1.SafetyKernel/Evaluate",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: PolicyCheckRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => PolicyCheckRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: PolicyCheckResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => PolicyCheckResponse.deserialize(new Uint8Array(bytes))
            },
            Explain: {
                path: "/coretex.agent.v1.SafetyKernel/Explain",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: PolicyCheckRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => PolicyCheckRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: PolicyCheckResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => PolicyCheckResponse.deserialize(new Uint8Array(bytes))
            },
            Simulate: {
                path: "/coretex.agent.v1.SafetyKernel/Simulate",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: PolicyCheckRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => PolicyCheckRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: PolicyCheckResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => PolicyCheckResponse.deserialize(new Uint8Array(bytes))
            },
            ListSnapshots: {
                path: "/coretex.agent.v1.SafetyKernel/ListSnapshots",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: ListSnapshotsRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => ListSnapshotsRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: ListSnapshotsResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => ListSnapshotsResponse.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract Check(call: grpc_1.ServerUnaryCall<PolicyCheckRequest, PolicyCheckResponse>, callback: grpc_1.sendUnaryData<PolicyCheckResponse>): void;
        abstract Evaluate(call: grpc_1.ServerUnaryCall<PolicyCheckRequest, PolicyCheckResponse>, callback: grpc_1.sendUnaryData<PolicyCheckResponse>): void;
        abstract Explain(call: grpc_1.ServerUnaryCall<PolicyCheckRequest, PolicyCheckResponse>, callback: grpc_1.sendUnaryData<PolicyCheckResponse>): void;
        abstract Simulate(call: grpc_1.ServerUnaryCall<PolicyCheckRequest, PolicyCheckResponse>, callback: grpc_1.sendUnaryData<PolicyCheckResponse>): void;
        abstract ListSnapshots(call: grpc_1.ServerUnaryCall<ListSnapshotsRequest, ListSnapshotsResponse>, callback: grpc_1.sendUnaryData<ListSnapshotsResponse>): void;
    }
    export class SafetyKernelClient extends grpc_1.makeGenericClientConstructor(UnimplementedSafetyKernelService.definition, "SafetyKernel", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options);
        }
        Check: GrpcUnaryServiceInterface<PolicyCheckRequest, PolicyCheckResponse> = (message: PolicyCheckRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<PolicyCheckResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<PolicyCheckResponse>, callback?: grpc_1.requestCallback<PolicyCheckResponse>): grpc_1.ClientUnaryCall => {
            return super.Check(message, metadata, options, callback);
        };
        Evaluate: GrpcUnaryServiceInterface<PolicyCheckRequest, PolicyCheckResponse> = (message: PolicyCheckRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<PolicyCheckResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<PolicyCheckResponse>, callback?: grpc_1.requestCallback<PolicyCheckResponse>): grpc_1.ClientUnaryCall => {
            return super.Evaluate(message, metadata, options, callback);
        };
        Explain: GrpcUnaryServiceInterface<PolicyCheckRequest, PolicyCheckResponse> = (message: PolicyCheckRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<PolicyCheckResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<PolicyCheckResponse>, callback?: grpc_1.requestCallback<PolicyCheckResponse>): grpc_1.ClientUnaryCall => {
            return super.Explain(message, metadata, options, callback);
        };
        Simulate: GrpcUnaryServiceInterface<PolicyCheckRequest, PolicyCheckResponse> = (message: PolicyCheckRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<PolicyCheckResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<PolicyCheckResponse>, callback?: grpc_1.requestCallback<PolicyCheckResponse>): grpc_1.ClientUnaryCall => {
            return super.Simulate(message, metadata, options, callback);
        };
        ListSnapshots: GrpcUnaryServiceInterface<ListSnapshotsRequest, ListSnapshotsResponse> = (message: ListSnapshotsRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<ListSnapshotsResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<ListSnapshotsResponse>, callback?: grpc_1.requestCallback<ListSnapshotsResponse>): grpc_1.ClientUnaryCall => {
            return super.ListSnapshots(message, metadata, options, callback);
        };
    }
}
