// source: cordum/agent/v1/safety.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var cordum_agent_v1_job_pb = require('../../../cordum/agent/v1/job_pb.js');
goog.object.extend(proto, cordum_agent_v1_job_pb);
goog.exportSymbol('proto.cordum.agent.v1.BudgetConstraints', null, global);
goog.exportSymbol('proto.cordum.agent.v1.DecisionType', null, global);
goog.exportSymbol('proto.cordum.agent.v1.DiffConstraints', null, global);
goog.exportSymbol('proto.cordum.agent.v1.ListSnapshotsRequest', null, global);
goog.exportSymbol('proto.cordum.agent.v1.ListSnapshotsResponse', null, global);
goog.exportSymbol('proto.cordum.agent.v1.PolicyCheckRequest', null, global);
goog.exportSymbol('proto.cordum.agent.v1.PolicyCheckResponse', null, global);
goog.exportSymbol('proto.cordum.agent.v1.PolicyConstraints', null, global);
goog.exportSymbol('proto.cordum.agent.v1.SandboxProfile', null, global);
goog.exportSymbol('proto.cordum.agent.v1.ToolchainConstraints', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cordum.agent.v1.PolicyCheckRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cordum.agent.v1.PolicyCheckRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cordum.agent.v1.PolicyCheckRequest.displayName = 'proto.cordum.agent.v1.PolicyCheckRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cordum.agent.v1.BudgetConstraints = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cordum.agent.v1.BudgetConstraints, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cordum.agent.v1.BudgetConstraints.displayName = 'proto.cordum.agent.v1.BudgetConstraints';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cordum.agent.v1.SandboxProfile = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.cordum.agent.v1.SandboxProfile.repeatedFields_, null);
};
goog.inherits(proto.cordum.agent.v1.SandboxProfile, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cordum.agent.v1.SandboxProfile.displayName = 'proto.cordum.agent.v1.SandboxProfile';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cordum.agent.v1.ToolchainConstraints = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.cordum.agent.v1.ToolchainConstraints.repeatedFields_, null);
};
goog.inherits(proto.cordum.agent.v1.ToolchainConstraints, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cordum.agent.v1.ToolchainConstraints.displayName = 'proto.cordum.agent.v1.ToolchainConstraints';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cordum.agent.v1.DiffConstraints = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.cordum.agent.v1.DiffConstraints.repeatedFields_, null);
};
goog.inherits(proto.cordum.agent.v1.DiffConstraints, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cordum.agent.v1.DiffConstraints.displayName = 'proto.cordum.agent.v1.DiffConstraints';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cordum.agent.v1.PolicyConstraints = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cordum.agent.v1.PolicyConstraints, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cordum.agent.v1.PolicyConstraints.displayName = 'proto.cordum.agent.v1.PolicyConstraints';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cordum.agent.v1.PolicyCheckResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cordum.agent.v1.PolicyCheckResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cordum.agent.v1.PolicyCheckResponse.displayName = 'proto.cordum.agent.v1.PolicyCheckResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cordum.agent.v1.ListSnapshotsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cordum.agent.v1.ListSnapshotsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cordum.agent.v1.ListSnapshotsRequest.displayName = 'proto.cordum.agent.v1.ListSnapshotsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cordum.agent.v1.ListSnapshotsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.cordum.agent.v1.ListSnapshotsResponse.repeatedFields_, null);
};
goog.inherits(proto.cordum.agent.v1.ListSnapshotsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cordum.agent.v1.ListSnapshotsResponse.displayName = 'proto.cordum.agent.v1.ListSnapshotsResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cordum.agent.v1.PolicyCheckRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.cordum.agent.v1.PolicyCheckRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cordum.agent.v1.PolicyCheckRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cordum.agent.v1.PolicyCheckRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    jobId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    topic: jspb.Message.getFieldWithDefault(msg, 2, ""),
    tenant: jspb.Message.getFieldWithDefault(msg, 3, ""),
    priority: jspb.Message.getFieldWithDefault(msg, 4, 0),
    estimatedCost: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    budget: (f = msg.getBudget()) && cordum_agent_v1_job_pb.Budget.toObject(includeInstance, f),
    principalId: jspb.Message.getFieldWithDefault(msg, 7, ""),
    labelsMap: (f = msg.getLabelsMap()) ? f.toObject(includeInstance, undefined) : [],
    memoryId: jspb.Message.getFieldWithDefault(msg, 9, ""),
    effectiveConfig: msg.getEffectiveConfig_asB64(),
    meta: (f = msg.getMeta()) && cordum_agent_v1_job_pb.JobMetadata.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cordum.agent.v1.PolicyCheckRequest}
 */
proto.cordum.agent.v1.PolicyCheckRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cordum.agent.v1.PolicyCheckRequest;
  return proto.cordum.agent.v1.PolicyCheckRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cordum.agent.v1.PolicyCheckRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cordum.agent.v1.PolicyCheckRequest}
 */
proto.cordum.agent.v1.PolicyCheckRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setJobId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTopic(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTenant(value);
      break;
    case 4:
      var value = /** @type {!proto.cordum.agent.v1.JobPriority} */ (reader.readEnum());
      msg.setPriority(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setEstimatedCost(value);
      break;
    case 6:
      var value = new cordum_agent_v1_job_pb.Budget;
      reader.readMessage(value,cordum_agent_v1_job_pb.Budget.deserializeBinaryFromReader);
      msg.setBudget(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setPrincipalId(value);
      break;
    case 8:
      var value = msg.getLabelsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setMemoryId(value);
      break;
    case 10:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setEffectiveConfig(value);
      break;
    case 11:
      var value = new cordum_agent_v1_job_pb.JobMetadata;
      reader.readMessage(value,cordum_agent_v1_job_pb.JobMetadata.deserializeBinaryFromReader);
      msg.setMeta(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cordum.agent.v1.PolicyCheckRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cordum.agent.v1.PolicyCheckRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cordum.agent.v1.PolicyCheckRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cordum.agent.v1.PolicyCheckRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getJobId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTopic();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTenant();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPriority();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getEstimatedCost();
  if (f !== 0.0) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = message.getBudget();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      cordum_agent_v1_job_pb.Budget.serializeBinaryToWriter
    );
  }
  f = message.getPrincipalId();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getLabelsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(8, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getMemoryId();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getEffectiveConfig_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      10,
      f
    );
  }
  f = message.getMeta();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      cordum_agent_v1_job_pb.JobMetadata.serializeBinaryToWriter
    );
  }
};


/**
 * optional string job_id = 1;
 * @return {string}
 */
proto.cordum.agent.v1.PolicyCheckRequest.prototype.getJobId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.PolicyCheckRequest} returns this
 */
proto.cordum.agent.v1.PolicyCheckRequest.prototype.setJobId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string topic = 2;
 * @return {string}
 */
proto.cordum.agent.v1.PolicyCheckRequest.prototype.getTopic = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.PolicyCheckRequest} returns this
 */
proto.cordum.agent.v1.PolicyCheckRequest.prototype.setTopic = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string tenant = 3;
 * @return {string}
 */
proto.cordum.agent.v1.PolicyCheckRequest.prototype.getTenant = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.PolicyCheckRequest} returns this
 */
proto.cordum.agent.v1.PolicyCheckRequest.prototype.setTenant = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional JobPriority priority = 4;
 * @return {!proto.cordum.agent.v1.JobPriority}
 */
proto.cordum.agent.v1.PolicyCheckRequest.prototype.getPriority = function() {
  return /** @type {!proto.cordum.agent.v1.JobPriority} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.cordum.agent.v1.JobPriority} value
 * @return {!proto.cordum.agent.v1.PolicyCheckRequest} returns this
 */
proto.cordum.agent.v1.PolicyCheckRequest.prototype.setPriority = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional double estimated_cost = 5;
 * @return {number}
 */
proto.cordum.agent.v1.PolicyCheckRequest.prototype.getEstimatedCost = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.cordum.agent.v1.PolicyCheckRequest} returns this
 */
proto.cordum.agent.v1.PolicyCheckRequest.prototype.setEstimatedCost = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional Budget budget = 6;
 * @return {?proto.cordum.agent.v1.Budget}
 */
proto.cordum.agent.v1.PolicyCheckRequest.prototype.getBudget = function() {
  return /** @type{?proto.cordum.agent.v1.Budget} */ (
    jspb.Message.getWrapperField(this, cordum_agent_v1_job_pb.Budget, 6));
};


/**
 * @param {?proto.cordum.agent.v1.Budget|undefined} value
 * @return {!proto.cordum.agent.v1.PolicyCheckRequest} returns this
*/
proto.cordum.agent.v1.PolicyCheckRequest.prototype.setBudget = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cordum.agent.v1.PolicyCheckRequest} returns this
 */
proto.cordum.agent.v1.PolicyCheckRequest.prototype.clearBudget = function() {
  return this.setBudget(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cordum.agent.v1.PolicyCheckRequest.prototype.hasBudget = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional string principal_id = 7;
 * @return {string}
 */
proto.cordum.agent.v1.PolicyCheckRequest.prototype.getPrincipalId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.PolicyCheckRequest} returns this
 */
proto.cordum.agent.v1.PolicyCheckRequest.prototype.setPrincipalId = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * map<string, string> labels = 8;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.cordum.agent.v1.PolicyCheckRequest.prototype.getLabelsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 8, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.cordum.agent.v1.PolicyCheckRequest} returns this
 */
proto.cordum.agent.v1.PolicyCheckRequest.prototype.clearLabelsMap = function() {
  this.getLabelsMap().clear();
  return this;};


/**
 * optional string memory_id = 9;
 * @return {string}
 */
proto.cordum.agent.v1.PolicyCheckRequest.prototype.getMemoryId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.PolicyCheckRequest} returns this
 */
proto.cordum.agent.v1.PolicyCheckRequest.prototype.setMemoryId = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional bytes effective_config = 10;
 * @return {!(string|Uint8Array)}
 */
proto.cordum.agent.v1.PolicyCheckRequest.prototype.getEffectiveConfig = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * optional bytes effective_config = 10;
 * This is a type-conversion wrapper around `getEffectiveConfig()`
 * @return {string}
 */
proto.cordum.agent.v1.PolicyCheckRequest.prototype.getEffectiveConfig_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getEffectiveConfig()));
};


/**
 * optional bytes effective_config = 10;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getEffectiveConfig()`
 * @return {!Uint8Array}
 */
proto.cordum.agent.v1.PolicyCheckRequest.prototype.getEffectiveConfig_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getEffectiveConfig()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.cordum.agent.v1.PolicyCheckRequest} returns this
 */
proto.cordum.agent.v1.PolicyCheckRequest.prototype.setEffectiveConfig = function(value) {
  return jspb.Message.setProto3BytesField(this, 10, value);
};


/**
 * optional JobMetadata meta = 11;
 * @return {?proto.cordum.agent.v1.JobMetadata}
 */
proto.cordum.agent.v1.PolicyCheckRequest.prototype.getMeta = function() {
  return /** @type{?proto.cordum.agent.v1.JobMetadata} */ (
    jspb.Message.getWrapperField(this, cordum_agent_v1_job_pb.JobMetadata, 11));
};


/**
 * @param {?proto.cordum.agent.v1.JobMetadata|undefined} value
 * @return {!proto.cordum.agent.v1.PolicyCheckRequest} returns this
*/
proto.cordum.agent.v1.PolicyCheckRequest.prototype.setMeta = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cordum.agent.v1.PolicyCheckRequest} returns this
 */
proto.cordum.agent.v1.PolicyCheckRequest.prototype.clearMeta = function() {
  return this.setMeta(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cordum.agent.v1.PolicyCheckRequest.prototype.hasMeta = function() {
  return jspb.Message.getField(this, 11) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cordum.agent.v1.BudgetConstraints.prototype.toObject = function(opt_includeInstance) {
  return proto.cordum.agent.v1.BudgetConstraints.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cordum.agent.v1.BudgetConstraints} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cordum.agent.v1.BudgetConstraints.toObject = function(includeInstance, msg) {
  var f, obj = {
    maxRuntimeMs: jspb.Message.getFieldWithDefault(msg, 1, 0),
    maxRetries: jspb.Message.getFieldWithDefault(msg, 2, 0),
    maxArtifactBytes: jspb.Message.getFieldWithDefault(msg, 3, 0),
    maxConcurrentJobs: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cordum.agent.v1.BudgetConstraints}
 */
proto.cordum.agent.v1.BudgetConstraints.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cordum.agent.v1.BudgetConstraints;
  return proto.cordum.agent.v1.BudgetConstraints.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cordum.agent.v1.BudgetConstraints} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cordum.agent.v1.BudgetConstraints}
 */
proto.cordum.agent.v1.BudgetConstraints.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setMaxRuntimeMs(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMaxRetries(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setMaxArtifactBytes(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMaxConcurrentJobs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cordum.agent.v1.BudgetConstraints.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cordum.agent.v1.BudgetConstraints.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cordum.agent.v1.BudgetConstraints} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cordum.agent.v1.BudgetConstraints.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMaxRuntimeMs();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getMaxRetries();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getMaxArtifactBytes();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getMaxConcurrentJobs();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
};


/**
 * optional int64 max_runtime_ms = 1;
 * @return {number}
 */
proto.cordum.agent.v1.BudgetConstraints.prototype.getMaxRuntimeMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.cordum.agent.v1.BudgetConstraints} returns this
 */
proto.cordum.agent.v1.BudgetConstraints.prototype.setMaxRuntimeMs = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 max_retries = 2;
 * @return {number}
 */
proto.cordum.agent.v1.BudgetConstraints.prototype.getMaxRetries = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.cordum.agent.v1.BudgetConstraints} returns this
 */
proto.cordum.agent.v1.BudgetConstraints.prototype.setMaxRetries = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 max_artifact_bytes = 3;
 * @return {number}
 */
proto.cordum.agent.v1.BudgetConstraints.prototype.getMaxArtifactBytes = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.cordum.agent.v1.BudgetConstraints} returns this
 */
proto.cordum.agent.v1.BudgetConstraints.prototype.setMaxArtifactBytes = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 max_concurrent_jobs = 4;
 * @return {number}
 */
proto.cordum.agent.v1.BudgetConstraints.prototype.getMaxConcurrentJobs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.cordum.agent.v1.BudgetConstraints} returns this
 */
proto.cordum.agent.v1.BudgetConstraints.prototype.setMaxConcurrentJobs = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.cordum.agent.v1.SandboxProfile.repeatedFields_ = [2,3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cordum.agent.v1.SandboxProfile.prototype.toObject = function(opt_includeInstance) {
  return proto.cordum.agent.v1.SandboxProfile.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cordum.agent.v1.SandboxProfile} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cordum.agent.v1.SandboxProfile.toObject = function(includeInstance, msg) {
  var f, obj = {
    isolated: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    networkAllowlistList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
    fsReadOnlyList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    fsReadWriteList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cordum.agent.v1.SandboxProfile}
 */
proto.cordum.agent.v1.SandboxProfile.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cordum.agent.v1.SandboxProfile;
  return proto.cordum.agent.v1.SandboxProfile.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cordum.agent.v1.SandboxProfile} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cordum.agent.v1.SandboxProfile}
 */
proto.cordum.agent.v1.SandboxProfile.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsolated(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addNetworkAllowlist(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addFsReadOnly(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.addFsReadWrite(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cordum.agent.v1.SandboxProfile.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cordum.agent.v1.SandboxProfile.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cordum.agent.v1.SandboxProfile} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cordum.agent.v1.SandboxProfile.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIsolated();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getNetworkAllowlistList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getFsReadOnlyList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getFsReadWriteList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      4,
      f
    );
  }
};


/**
 * optional bool isolated = 1;
 * @return {boolean}
 */
proto.cordum.agent.v1.SandboxProfile.prototype.getIsolated = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.cordum.agent.v1.SandboxProfile} returns this
 */
proto.cordum.agent.v1.SandboxProfile.prototype.setIsolated = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * repeated string network_allowlist = 2;
 * @return {!Array<string>}
 */
proto.cordum.agent.v1.SandboxProfile.prototype.getNetworkAllowlistList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.cordum.agent.v1.SandboxProfile} returns this
 */
proto.cordum.agent.v1.SandboxProfile.prototype.setNetworkAllowlistList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.cordum.agent.v1.SandboxProfile} returns this
 */
proto.cordum.agent.v1.SandboxProfile.prototype.addNetworkAllowlist = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.cordum.agent.v1.SandboxProfile} returns this
 */
proto.cordum.agent.v1.SandboxProfile.prototype.clearNetworkAllowlistList = function() {
  return this.setNetworkAllowlistList([]);
};


/**
 * repeated string fs_read_only = 3;
 * @return {!Array<string>}
 */
proto.cordum.agent.v1.SandboxProfile.prototype.getFsReadOnlyList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.cordum.agent.v1.SandboxProfile} returns this
 */
proto.cordum.agent.v1.SandboxProfile.prototype.setFsReadOnlyList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.cordum.agent.v1.SandboxProfile} returns this
 */
proto.cordum.agent.v1.SandboxProfile.prototype.addFsReadOnly = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.cordum.agent.v1.SandboxProfile} returns this
 */
proto.cordum.agent.v1.SandboxProfile.prototype.clearFsReadOnlyList = function() {
  return this.setFsReadOnlyList([]);
};


/**
 * repeated string fs_read_write = 4;
 * @return {!Array<string>}
 */
proto.cordum.agent.v1.SandboxProfile.prototype.getFsReadWriteList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.cordum.agent.v1.SandboxProfile} returns this
 */
proto.cordum.agent.v1.SandboxProfile.prototype.setFsReadWriteList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.cordum.agent.v1.SandboxProfile} returns this
 */
proto.cordum.agent.v1.SandboxProfile.prototype.addFsReadWrite = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.cordum.agent.v1.SandboxProfile} returns this
 */
proto.cordum.agent.v1.SandboxProfile.prototype.clearFsReadWriteList = function() {
  return this.setFsReadWriteList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.cordum.agent.v1.ToolchainConstraints.repeatedFields_ = [1,2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cordum.agent.v1.ToolchainConstraints.prototype.toObject = function(opt_includeInstance) {
  return proto.cordum.agent.v1.ToolchainConstraints.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cordum.agent.v1.ToolchainConstraints} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cordum.agent.v1.ToolchainConstraints.toObject = function(includeInstance, msg) {
  var f, obj = {
    allowedToolsList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
    allowedCommandsList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cordum.agent.v1.ToolchainConstraints}
 */
proto.cordum.agent.v1.ToolchainConstraints.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cordum.agent.v1.ToolchainConstraints;
  return proto.cordum.agent.v1.ToolchainConstraints.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cordum.agent.v1.ToolchainConstraints} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cordum.agent.v1.ToolchainConstraints}
 */
proto.cordum.agent.v1.ToolchainConstraints.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addAllowedTools(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addAllowedCommands(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cordum.agent.v1.ToolchainConstraints.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cordum.agent.v1.ToolchainConstraints.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cordum.agent.v1.ToolchainConstraints} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cordum.agent.v1.ToolchainConstraints.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAllowedToolsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
  f = message.getAllowedCommandsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
};


/**
 * repeated string allowed_tools = 1;
 * @return {!Array<string>}
 */
proto.cordum.agent.v1.ToolchainConstraints.prototype.getAllowedToolsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.cordum.agent.v1.ToolchainConstraints} returns this
 */
proto.cordum.agent.v1.ToolchainConstraints.prototype.setAllowedToolsList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.cordum.agent.v1.ToolchainConstraints} returns this
 */
proto.cordum.agent.v1.ToolchainConstraints.prototype.addAllowedTools = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.cordum.agent.v1.ToolchainConstraints} returns this
 */
proto.cordum.agent.v1.ToolchainConstraints.prototype.clearAllowedToolsList = function() {
  return this.setAllowedToolsList([]);
};


/**
 * repeated string allowed_commands = 2;
 * @return {!Array<string>}
 */
proto.cordum.agent.v1.ToolchainConstraints.prototype.getAllowedCommandsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.cordum.agent.v1.ToolchainConstraints} returns this
 */
proto.cordum.agent.v1.ToolchainConstraints.prototype.setAllowedCommandsList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.cordum.agent.v1.ToolchainConstraints} returns this
 */
proto.cordum.agent.v1.ToolchainConstraints.prototype.addAllowedCommands = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.cordum.agent.v1.ToolchainConstraints} returns this
 */
proto.cordum.agent.v1.ToolchainConstraints.prototype.clearAllowedCommandsList = function() {
  return this.setAllowedCommandsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.cordum.agent.v1.DiffConstraints.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cordum.agent.v1.DiffConstraints.prototype.toObject = function(opt_includeInstance) {
  return proto.cordum.agent.v1.DiffConstraints.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cordum.agent.v1.DiffConstraints} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cordum.agent.v1.DiffConstraints.toObject = function(includeInstance, msg) {
  var f, obj = {
    maxFiles: jspb.Message.getFieldWithDefault(msg, 1, 0),
    maxLines: jspb.Message.getFieldWithDefault(msg, 2, 0),
    denyPathGlobsList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cordum.agent.v1.DiffConstraints}
 */
proto.cordum.agent.v1.DiffConstraints.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cordum.agent.v1.DiffConstraints;
  return proto.cordum.agent.v1.DiffConstraints.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cordum.agent.v1.DiffConstraints} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cordum.agent.v1.DiffConstraints}
 */
proto.cordum.agent.v1.DiffConstraints.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMaxFiles(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMaxLines(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addDenyPathGlobs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cordum.agent.v1.DiffConstraints.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cordum.agent.v1.DiffConstraints.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cordum.agent.v1.DiffConstraints} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cordum.agent.v1.DiffConstraints.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMaxFiles();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getMaxLines();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getDenyPathGlobsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
};


/**
 * optional int32 max_files = 1;
 * @return {number}
 */
proto.cordum.agent.v1.DiffConstraints.prototype.getMaxFiles = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.cordum.agent.v1.DiffConstraints} returns this
 */
proto.cordum.agent.v1.DiffConstraints.prototype.setMaxFiles = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 max_lines = 2;
 * @return {number}
 */
proto.cordum.agent.v1.DiffConstraints.prototype.getMaxLines = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.cordum.agent.v1.DiffConstraints} returns this
 */
proto.cordum.agent.v1.DiffConstraints.prototype.setMaxLines = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * repeated string deny_path_globs = 3;
 * @return {!Array<string>}
 */
proto.cordum.agent.v1.DiffConstraints.prototype.getDenyPathGlobsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.cordum.agent.v1.DiffConstraints} returns this
 */
proto.cordum.agent.v1.DiffConstraints.prototype.setDenyPathGlobsList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.cordum.agent.v1.DiffConstraints} returns this
 */
proto.cordum.agent.v1.DiffConstraints.prototype.addDenyPathGlobs = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.cordum.agent.v1.DiffConstraints} returns this
 */
proto.cordum.agent.v1.DiffConstraints.prototype.clearDenyPathGlobsList = function() {
  return this.setDenyPathGlobsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cordum.agent.v1.PolicyConstraints.prototype.toObject = function(opt_includeInstance) {
  return proto.cordum.agent.v1.PolicyConstraints.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cordum.agent.v1.PolicyConstraints} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cordum.agent.v1.PolicyConstraints.toObject = function(includeInstance, msg) {
  var f, obj = {
    budgets: (f = msg.getBudgets()) && proto.cordum.agent.v1.BudgetConstraints.toObject(includeInstance, f),
    sandbox: (f = msg.getSandbox()) && proto.cordum.agent.v1.SandboxProfile.toObject(includeInstance, f),
    toolchain: (f = msg.getToolchain()) && proto.cordum.agent.v1.ToolchainConstraints.toObject(includeInstance, f),
    diff: (f = msg.getDiff()) && proto.cordum.agent.v1.DiffConstraints.toObject(includeInstance, f),
    redactionLevel: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cordum.agent.v1.PolicyConstraints}
 */
proto.cordum.agent.v1.PolicyConstraints.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cordum.agent.v1.PolicyConstraints;
  return proto.cordum.agent.v1.PolicyConstraints.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cordum.agent.v1.PolicyConstraints} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cordum.agent.v1.PolicyConstraints}
 */
proto.cordum.agent.v1.PolicyConstraints.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.cordum.agent.v1.BudgetConstraints;
      reader.readMessage(value,proto.cordum.agent.v1.BudgetConstraints.deserializeBinaryFromReader);
      msg.setBudgets(value);
      break;
    case 2:
      var value = new proto.cordum.agent.v1.SandboxProfile;
      reader.readMessage(value,proto.cordum.agent.v1.SandboxProfile.deserializeBinaryFromReader);
      msg.setSandbox(value);
      break;
    case 3:
      var value = new proto.cordum.agent.v1.ToolchainConstraints;
      reader.readMessage(value,proto.cordum.agent.v1.ToolchainConstraints.deserializeBinaryFromReader);
      msg.setToolchain(value);
      break;
    case 4:
      var value = new proto.cordum.agent.v1.DiffConstraints;
      reader.readMessage(value,proto.cordum.agent.v1.DiffConstraints.deserializeBinaryFromReader);
      msg.setDiff(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setRedactionLevel(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cordum.agent.v1.PolicyConstraints.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cordum.agent.v1.PolicyConstraints.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cordum.agent.v1.PolicyConstraints} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cordum.agent.v1.PolicyConstraints.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBudgets();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.cordum.agent.v1.BudgetConstraints.serializeBinaryToWriter
    );
  }
  f = message.getSandbox();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.cordum.agent.v1.SandboxProfile.serializeBinaryToWriter
    );
  }
  f = message.getToolchain();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.cordum.agent.v1.ToolchainConstraints.serializeBinaryToWriter
    );
  }
  f = message.getDiff();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.cordum.agent.v1.DiffConstraints.serializeBinaryToWriter
    );
  }
  f = message.getRedactionLevel();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional BudgetConstraints budgets = 1;
 * @return {?proto.cordum.agent.v1.BudgetConstraints}
 */
proto.cordum.agent.v1.PolicyConstraints.prototype.getBudgets = function() {
  return /** @type{?proto.cordum.agent.v1.BudgetConstraints} */ (
    jspb.Message.getWrapperField(this, proto.cordum.agent.v1.BudgetConstraints, 1));
};


/**
 * @param {?proto.cordum.agent.v1.BudgetConstraints|undefined} value
 * @return {!proto.cordum.agent.v1.PolicyConstraints} returns this
*/
proto.cordum.agent.v1.PolicyConstraints.prototype.setBudgets = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cordum.agent.v1.PolicyConstraints} returns this
 */
proto.cordum.agent.v1.PolicyConstraints.prototype.clearBudgets = function() {
  return this.setBudgets(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cordum.agent.v1.PolicyConstraints.prototype.hasBudgets = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional SandboxProfile sandbox = 2;
 * @return {?proto.cordum.agent.v1.SandboxProfile}
 */
proto.cordum.agent.v1.PolicyConstraints.prototype.getSandbox = function() {
  return /** @type{?proto.cordum.agent.v1.SandboxProfile} */ (
    jspb.Message.getWrapperField(this, proto.cordum.agent.v1.SandboxProfile, 2));
};


/**
 * @param {?proto.cordum.agent.v1.SandboxProfile|undefined} value
 * @return {!proto.cordum.agent.v1.PolicyConstraints} returns this
*/
proto.cordum.agent.v1.PolicyConstraints.prototype.setSandbox = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cordum.agent.v1.PolicyConstraints} returns this
 */
proto.cordum.agent.v1.PolicyConstraints.prototype.clearSandbox = function() {
  return this.setSandbox(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cordum.agent.v1.PolicyConstraints.prototype.hasSandbox = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional ToolchainConstraints toolchain = 3;
 * @return {?proto.cordum.agent.v1.ToolchainConstraints}
 */
proto.cordum.agent.v1.PolicyConstraints.prototype.getToolchain = function() {
  return /** @type{?proto.cordum.agent.v1.ToolchainConstraints} */ (
    jspb.Message.getWrapperField(this, proto.cordum.agent.v1.ToolchainConstraints, 3));
};


/**
 * @param {?proto.cordum.agent.v1.ToolchainConstraints|undefined} value
 * @return {!proto.cordum.agent.v1.PolicyConstraints} returns this
*/
proto.cordum.agent.v1.PolicyConstraints.prototype.setToolchain = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cordum.agent.v1.PolicyConstraints} returns this
 */
proto.cordum.agent.v1.PolicyConstraints.prototype.clearToolchain = function() {
  return this.setToolchain(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cordum.agent.v1.PolicyConstraints.prototype.hasToolchain = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional DiffConstraints diff = 4;
 * @return {?proto.cordum.agent.v1.DiffConstraints}
 */
proto.cordum.agent.v1.PolicyConstraints.prototype.getDiff = function() {
  return /** @type{?proto.cordum.agent.v1.DiffConstraints} */ (
    jspb.Message.getWrapperField(this, proto.cordum.agent.v1.DiffConstraints, 4));
};


/**
 * @param {?proto.cordum.agent.v1.DiffConstraints|undefined} value
 * @return {!proto.cordum.agent.v1.PolicyConstraints} returns this
*/
proto.cordum.agent.v1.PolicyConstraints.prototype.setDiff = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cordum.agent.v1.PolicyConstraints} returns this
 */
proto.cordum.agent.v1.PolicyConstraints.prototype.clearDiff = function() {
  return this.setDiff(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cordum.agent.v1.PolicyConstraints.prototype.hasDiff = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string redaction_level = 5;
 * @return {string}
 */
proto.cordum.agent.v1.PolicyConstraints.prototype.getRedactionLevel = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.PolicyConstraints} returns this
 */
proto.cordum.agent.v1.PolicyConstraints.prototype.setRedactionLevel = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cordum.agent.v1.PolicyCheckResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.cordum.agent.v1.PolicyCheckResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cordum.agent.v1.PolicyCheckResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cordum.agent.v1.PolicyCheckResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    decision: jspb.Message.getFieldWithDefault(msg, 1, 0),
    reason: jspb.Message.getFieldWithDefault(msg, 2, ""),
    redactedContextPtr: jspb.Message.getFieldWithDefault(msg, 3, ""),
    policySnapshot: jspb.Message.getFieldWithDefault(msg, 4, ""),
    ruleId: jspb.Message.getFieldWithDefault(msg, 5, ""),
    constraints: (f = msg.getConstraints()) && proto.cordum.agent.v1.PolicyConstraints.toObject(includeInstance, f),
    approvalRequired: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
    approvalRef: jspb.Message.getFieldWithDefault(msg, 8, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cordum.agent.v1.PolicyCheckResponse}
 */
proto.cordum.agent.v1.PolicyCheckResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cordum.agent.v1.PolicyCheckResponse;
  return proto.cordum.agent.v1.PolicyCheckResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cordum.agent.v1.PolicyCheckResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cordum.agent.v1.PolicyCheckResponse}
 */
proto.cordum.agent.v1.PolicyCheckResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.cordum.agent.v1.DecisionType} */ (reader.readEnum());
      msg.setDecision(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setReason(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setRedactedContextPtr(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setPolicySnapshot(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setRuleId(value);
      break;
    case 6:
      var value = new proto.cordum.agent.v1.PolicyConstraints;
      reader.readMessage(value,proto.cordum.agent.v1.PolicyConstraints.deserializeBinaryFromReader);
      msg.setConstraints(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setApprovalRequired(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setApprovalRef(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cordum.agent.v1.PolicyCheckResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cordum.agent.v1.PolicyCheckResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cordum.agent.v1.PolicyCheckResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cordum.agent.v1.PolicyCheckResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDecision();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getReason();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRedactedContextPtr();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPolicySnapshot();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getRuleId();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getConstraints();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.cordum.agent.v1.PolicyConstraints.serializeBinaryToWriter
    );
  }
  f = message.getApprovalRequired();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getApprovalRef();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
};


/**
 * optional DecisionType decision = 1;
 * @return {!proto.cordum.agent.v1.DecisionType}
 */
proto.cordum.agent.v1.PolicyCheckResponse.prototype.getDecision = function() {
  return /** @type {!proto.cordum.agent.v1.DecisionType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.cordum.agent.v1.DecisionType} value
 * @return {!proto.cordum.agent.v1.PolicyCheckResponse} returns this
 */
proto.cordum.agent.v1.PolicyCheckResponse.prototype.setDecision = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string reason = 2;
 * @return {string}
 */
proto.cordum.agent.v1.PolicyCheckResponse.prototype.getReason = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.PolicyCheckResponse} returns this
 */
proto.cordum.agent.v1.PolicyCheckResponse.prototype.setReason = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string redacted_context_ptr = 3;
 * @return {string}
 */
proto.cordum.agent.v1.PolicyCheckResponse.prototype.getRedactedContextPtr = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.PolicyCheckResponse} returns this
 */
proto.cordum.agent.v1.PolicyCheckResponse.prototype.setRedactedContextPtr = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string policy_snapshot = 4;
 * @return {string}
 */
proto.cordum.agent.v1.PolicyCheckResponse.prototype.getPolicySnapshot = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.PolicyCheckResponse} returns this
 */
proto.cordum.agent.v1.PolicyCheckResponse.prototype.setPolicySnapshot = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string rule_id = 5;
 * @return {string}
 */
proto.cordum.agent.v1.PolicyCheckResponse.prototype.getRuleId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.PolicyCheckResponse} returns this
 */
proto.cordum.agent.v1.PolicyCheckResponse.prototype.setRuleId = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional PolicyConstraints constraints = 6;
 * @return {?proto.cordum.agent.v1.PolicyConstraints}
 */
proto.cordum.agent.v1.PolicyCheckResponse.prototype.getConstraints = function() {
  return /** @type{?proto.cordum.agent.v1.PolicyConstraints} */ (
    jspb.Message.getWrapperField(this, proto.cordum.agent.v1.PolicyConstraints, 6));
};


/**
 * @param {?proto.cordum.agent.v1.PolicyConstraints|undefined} value
 * @return {!proto.cordum.agent.v1.PolicyCheckResponse} returns this
*/
proto.cordum.agent.v1.PolicyCheckResponse.prototype.setConstraints = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cordum.agent.v1.PolicyCheckResponse} returns this
 */
proto.cordum.agent.v1.PolicyCheckResponse.prototype.clearConstraints = function() {
  return this.setConstraints(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cordum.agent.v1.PolicyCheckResponse.prototype.hasConstraints = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional bool approval_required = 7;
 * @return {boolean}
 */
proto.cordum.agent.v1.PolicyCheckResponse.prototype.getApprovalRequired = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.cordum.agent.v1.PolicyCheckResponse} returns this
 */
proto.cordum.agent.v1.PolicyCheckResponse.prototype.setApprovalRequired = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * optional string approval_ref = 8;
 * @return {string}
 */
proto.cordum.agent.v1.PolicyCheckResponse.prototype.getApprovalRef = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.cordum.agent.v1.PolicyCheckResponse} returns this
 */
proto.cordum.agent.v1.PolicyCheckResponse.prototype.setApprovalRef = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cordum.agent.v1.ListSnapshotsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.cordum.agent.v1.ListSnapshotsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cordum.agent.v1.ListSnapshotsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cordum.agent.v1.ListSnapshotsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cordum.agent.v1.ListSnapshotsRequest}
 */
proto.cordum.agent.v1.ListSnapshotsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cordum.agent.v1.ListSnapshotsRequest;
  return proto.cordum.agent.v1.ListSnapshotsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cordum.agent.v1.ListSnapshotsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cordum.agent.v1.ListSnapshotsRequest}
 */
proto.cordum.agent.v1.ListSnapshotsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cordum.agent.v1.ListSnapshotsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cordum.agent.v1.ListSnapshotsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cordum.agent.v1.ListSnapshotsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cordum.agent.v1.ListSnapshotsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.cordum.agent.v1.ListSnapshotsResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cordum.agent.v1.ListSnapshotsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.cordum.agent.v1.ListSnapshotsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cordum.agent.v1.ListSnapshotsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cordum.agent.v1.ListSnapshotsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    snapshotsList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cordum.agent.v1.ListSnapshotsResponse}
 */
proto.cordum.agent.v1.ListSnapshotsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cordum.agent.v1.ListSnapshotsResponse;
  return proto.cordum.agent.v1.ListSnapshotsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cordum.agent.v1.ListSnapshotsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cordum.agent.v1.ListSnapshotsResponse}
 */
proto.cordum.agent.v1.ListSnapshotsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addSnapshots(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cordum.agent.v1.ListSnapshotsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cordum.agent.v1.ListSnapshotsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cordum.agent.v1.ListSnapshotsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cordum.agent.v1.ListSnapshotsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSnapshotsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
};


/**
 * repeated string snapshots = 1;
 * @return {!Array<string>}
 */
proto.cordum.agent.v1.ListSnapshotsResponse.prototype.getSnapshotsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.cordum.agent.v1.ListSnapshotsResponse} returns this
 */
proto.cordum.agent.v1.ListSnapshotsResponse.prototype.setSnapshotsList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.cordum.agent.v1.ListSnapshotsResponse} returns this
 */
proto.cordum.agent.v1.ListSnapshotsResponse.prototype.addSnapshots = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.cordum.agent.v1.ListSnapshotsResponse} returns this
 */
proto.cordum.agent.v1.ListSnapshotsResponse.prototype.clearSnapshotsList = function() {
  return this.setSnapshotsList([]);
};


/**
 * @enum {number}
 */
proto.cordum.agent.v1.DecisionType = {
  DECISION_TYPE_UNSPECIFIED: 0,
  DECISION_TYPE_ALLOW: 1,
  DECISION_TYPE_DENY: 2,
  DECISION_TYPE_REQUIRE_HUMAN: 3,
  DECISION_TYPE_THROTTLE: 4,
  DECISION_TYPE_ALLOW_WITH_CONSTRAINTS: 5
};

goog.object.extend(exports, proto.cordum.agent.v1);
