// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coretex/agent/v1/buspacket.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_coretex_2fagent_2fv1_2fbuspacket_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_coretex_2fagent_2fv1_2fbuspacket_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/timestamp.pb.h>
#include "coretex/agent/v1/job.pb.h"
#include "coretex/agent/v1/heartbeat.pb.h"
#include "coretex/agent/v1/alert.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_coretex_2fagent_2fv1_2fbuspacket_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_coretex_2fagent_2fv1_2fbuspacket_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_coretex_2fagent_2fv1_2fbuspacket_2eproto;
namespace coretex {
namespace agent {
namespace v1 {
class BusPacket;
struct BusPacketDefaultTypeInternal;
extern BusPacketDefaultTypeInternal _BusPacket_default_instance_;
}  // namespace v1
}  // namespace agent
}  // namespace coretex
PROTOBUF_NAMESPACE_OPEN
template<> ::coretex::agent::v1::BusPacket* Arena::CreateMaybeMessage<::coretex::agent::v1::BusPacket>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace coretex {
namespace agent {
namespace v1 {

// ===================================================================

class BusPacket final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:coretex.agent.v1.BusPacket) */ {
 public:
  inline BusPacket() : BusPacket(nullptr) {}
  ~BusPacket() override;
  explicit PROTOBUF_CONSTEXPR BusPacket(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BusPacket(const BusPacket& from);
  BusPacket(BusPacket&& from) noexcept
    : BusPacket() {
    *this = ::std::move(from);
  }

  inline BusPacket& operator=(const BusPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline BusPacket& operator=(BusPacket&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BusPacket& default_instance() {
    return *internal_default_instance();
  }
  enum PayloadCase {
    kJobRequest = 10,
    kJobResult = 11,
    kHeartbeat = 12,
    kAlert = 13,
    PAYLOAD_NOT_SET = 0,
  };

  static inline const BusPacket* internal_default_instance() {
    return reinterpret_cast<const BusPacket*>(
               &_BusPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(BusPacket& a, BusPacket& b) {
    a.Swap(&b);
  }
  inline void Swap(BusPacket* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BusPacket* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BusPacket* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BusPacket>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BusPacket& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const BusPacket& from) {
    BusPacket::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BusPacket* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "coretex.agent.v1.BusPacket";
  }
  protected:
  explicit BusPacket(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTraceIdFieldNumber = 1,
    kSenderIdFieldNumber = 2,
    kSignatureFieldNumber = 14,
    kCreatedAtFieldNumber = 3,
    kProtocolVersionFieldNumber = 4,
    kJobRequestFieldNumber = 10,
    kJobResultFieldNumber = 11,
    kHeartbeatFieldNumber = 12,
    kAlertFieldNumber = 13,
  };
  // string trace_id = 1;
  void clear_trace_id();
  const std::string& trace_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_trace_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_trace_id();
  PROTOBUF_NODISCARD std::string* release_trace_id();
  void set_allocated_trace_id(std::string* trace_id);
  private:
  const std::string& _internal_trace_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_trace_id(const std::string& value);
  std::string* _internal_mutable_trace_id();
  public:

  // string sender_id = 2;
  void clear_sender_id();
  const std::string& sender_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sender_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sender_id();
  PROTOBUF_NODISCARD std::string* release_sender_id();
  void set_allocated_sender_id(std::string* sender_id);
  private:
  const std::string& _internal_sender_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sender_id(const std::string& value);
  std::string* _internal_mutable_sender_id();
  public:

  // bytes signature = 14;
  void clear_signature();
  const std::string& signature() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_signature(ArgT0&& arg0, ArgT... args);
  std::string* mutable_signature();
  PROTOBUF_NODISCARD std::string* release_signature();
  void set_allocated_signature(std::string* signature);
  private:
  const std::string& _internal_signature() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_signature(const std::string& value);
  std::string* _internal_mutable_signature();
  public:

  // .google.protobuf.Timestamp created_at = 3;
  bool has_created_at() const;
  private:
  bool _internal_has_created_at() const;
  public:
  void clear_created_at();
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& created_at() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Timestamp* release_created_at();
  ::PROTOBUF_NAMESPACE_ID::Timestamp* mutable_created_at();
  void set_allocated_created_at(::PROTOBUF_NAMESPACE_ID::Timestamp* created_at);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& _internal_created_at() const;
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_created_at();
  public:
  void unsafe_arena_set_allocated_created_at(
      ::PROTOBUF_NAMESPACE_ID::Timestamp* created_at);
  ::PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_created_at();

  // int32 protocol_version = 4;
  void clear_protocol_version();
  int32_t protocol_version() const;
  void set_protocol_version(int32_t value);
  private:
  int32_t _internal_protocol_version() const;
  void _internal_set_protocol_version(int32_t value);
  public:

  // .coretex.agent.v1.JobRequest job_request = 10;
  bool has_job_request() const;
  private:
  bool _internal_has_job_request() const;
  public:
  void clear_job_request();
  const ::coretex::agent::v1::JobRequest& job_request() const;
  PROTOBUF_NODISCARD ::coretex::agent::v1::JobRequest* release_job_request();
  ::coretex::agent::v1::JobRequest* mutable_job_request();
  void set_allocated_job_request(::coretex::agent::v1::JobRequest* job_request);
  private:
  const ::coretex::agent::v1::JobRequest& _internal_job_request() const;
  ::coretex::agent::v1::JobRequest* _internal_mutable_job_request();
  public:
  void unsafe_arena_set_allocated_job_request(
      ::coretex::agent::v1::JobRequest* job_request);
  ::coretex::agent::v1::JobRequest* unsafe_arena_release_job_request();

  // .coretex.agent.v1.JobResult job_result = 11;
  bool has_job_result() const;
  private:
  bool _internal_has_job_result() const;
  public:
  void clear_job_result();
  const ::coretex::agent::v1::JobResult& job_result() const;
  PROTOBUF_NODISCARD ::coretex::agent::v1::JobResult* release_job_result();
  ::coretex::agent::v1::JobResult* mutable_job_result();
  void set_allocated_job_result(::coretex::agent::v1::JobResult* job_result);
  private:
  const ::coretex::agent::v1::JobResult& _internal_job_result() const;
  ::coretex::agent::v1::JobResult* _internal_mutable_job_result();
  public:
  void unsafe_arena_set_allocated_job_result(
      ::coretex::agent::v1::JobResult* job_result);
  ::coretex::agent::v1::JobResult* unsafe_arena_release_job_result();

  // .coretex.agent.v1.Heartbeat heartbeat = 12;
  bool has_heartbeat() const;
  private:
  bool _internal_has_heartbeat() const;
  public:
  void clear_heartbeat();
  const ::coretex::agent::v1::Heartbeat& heartbeat() const;
  PROTOBUF_NODISCARD ::coretex::agent::v1::Heartbeat* release_heartbeat();
  ::coretex::agent::v1::Heartbeat* mutable_heartbeat();
  void set_allocated_heartbeat(::coretex::agent::v1::Heartbeat* heartbeat);
  private:
  const ::coretex::agent::v1::Heartbeat& _internal_heartbeat() const;
  ::coretex::agent::v1::Heartbeat* _internal_mutable_heartbeat();
  public:
  void unsafe_arena_set_allocated_heartbeat(
      ::coretex::agent::v1::Heartbeat* heartbeat);
  ::coretex::agent::v1::Heartbeat* unsafe_arena_release_heartbeat();

  // .coretex.agent.v1.SystemAlert alert = 13;
  bool has_alert() const;
  private:
  bool _internal_has_alert() const;
  public:
  void clear_alert();
  const ::coretex::agent::v1::SystemAlert& alert() const;
  PROTOBUF_NODISCARD ::coretex::agent::v1::SystemAlert* release_alert();
  ::coretex::agent::v1::SystemAlert* mutable_alert();
  void set_allocated_alert(::coretex::agent::v1::SystemAlert* alert);
  private:
  const ::coretex::agent::v1::SystemAlert& _internal_alert() const;
  ::coretex::agent::v1::SystemAlert* _internal_mutable_alert();
  public:
  void unsafe_arena_set_allocated_alert(
      ::coretex::agent::v1::SystemAlert* alert);
  ::coretex::agent::v1::SystemAlert* unsafe_arena_release_alert();

  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:coretex.agent.v1.BusPacket)
 private:
  class _Internal;
  void set_has_job_request();
  void set_has_job_result();
  void set_has_heartbeat();
  void set_has_alert();

  inline bool has_payload() const;
  inline void clear_has_payload();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr trace_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sender_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr signature_;
    ::PROTOBUF_NAMESPACE_ID::Timestamp* created_at_;
    int32_t protocol_version_;
    union PayloadUnion {
      constexpr PayloadUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::coretex::agent::v1::JobRequest* job_request_;
      ::coretex::agent::v1::JobResult* job_result_;
      ::coretex::agent::v1::Heartbeat* heartbeat_;
      ::coretex::agent::v1::SystemAlert* alert_;
    } payload_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_coretex_2fagent_2fv1_2fbuspacket_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BusPacket

// string trace_id = 1;
inline void BusPacket::clear_trace_id() {
  _impl_.trace_id_.ClearToEmpty();
}
inline const std::string& BusPacket::trace_id() const {
  // @@protoc_insertion_point(field_get:coretex.agent.v1.BusPacket.trace_id)
  return _internal_trace_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void BusPacket::set_trace_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.trace_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:coretex.agent.v1.BusPacket.trace_id)
}
inline std::string* BusPacket::mutable_trace_id() {
  std::string* _s = _internal_mutable_trace_id();
  // @@protoc_insertion_point(field_mutable:coretex.agent.v1.BusPacket.trace_id)
  return _s;
}
inline const std::string& BusPacket::_internal_trace_id() const {
  return _impl_.trace_id_.Get();
}
inline void BusPacket::_internal_set_trace_id(const std::string& value) {
  
  _impl_.trace_id_.Set(value, GetArenaForAllocation());
}
inline std::string* BusPacket::_internal_mutable_trace_id() {
  
  return _impl_.trace_id_.Mutable(GetArenaForAllocation());
}
inline std::string* BusPacket::release_trace_id() {
  // @@protoc_insertion_point(field_release:coretex.agent.v1.BusPacket.trace_id)
  return _impl_.trace_id_.Release();
}
inline void BusPacket::set_allocated_trace_id(std::string* trace_id) {
  if (trace_id != nullptr) {
    
  } else {
    
  }
  _impl_.trace_id_.SetAllocated(trace_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.trace_id_.IsDefault()) {
    _impl_.trace_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:coretex.agent.v1.BusPacket.trace_id)
}

// string sender_id = 2;
inline void BusPacket::clear_sender_id() {
  _impl_.sender_id_.ClearToEmpty();
}
inline const std::string& BusPacket::sender_id() const {
  // @@protoc_insertion_point(field_get:coretex.agent.v1.BusPacket.sender_id)
  return _internal_sender_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void BusPacket::set_sender_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.sender_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:coretex.agent.v1.BusPacket.sender_id)
}
inline std::string* BusPacket::mutable_sender_id() {
  std::string* _s = _internal_mutable_sender_id();
  // @@protoc_insertion_point(field_mutable:coretex.agent.v1.BusPacket.sender_id)
  return _s;
}
inline const std::string& BusPacket::_internal_sender_id() const {
  return _impl_.sender_id_.Get();
}
inline void BusPacket::_internal_set_sender_id(const std::string& value) {
  
  _impl_.sender_id_.Set(value, GetArenaForAllocation());
}
inline std::string* BusPacket::_internal_mutable_sender_id() {
  
  return _impl_.sender_id_.Mutable(GetArenaForAllocation());
}
inline std::string* BusPacket::release_sender_id() {
  // @@protoc_insertion_point(field_release:coretex.agent.v1.BusPacket.sender_id)
  return _impl_.sender_id_.Release();
}
inline void BusPacket::set_allocated_sender_id(std::string* sender_id) {
  if (sender_id != nullptr) {
    
  } else {
    
  }
  _impl_.sender_id_.SetAllocated(sender_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.sender_id_.IsDefault()) {
    _impl_.sender_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:coretex.agent.v1.BusPacket.sender_id)
}

// .google.protobuf.Timestamp created_at = 3;
inline bool BusPacket::_internal_has_created_at() const {
  return this != internal_default_instance() && _impl_.created_at_ != nullptr;
}
inline bool BusPacket::has_created_at() const {
  return _internal_has_created_at();
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& BusPacket::_internal_created_at() const {
  const ::PROTOBUF_NAMESPACE_ID::Timestamp* p = _impl_.created_at_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Timestamp&>(
      ::PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& BusPacket::created_at() const {
  // @@protoc_insertion_point(field_get:coretex.agent.v1.BusPacket.created_at)
  return _internal_created_at();
}
inline void BusPacket::unsafe_arena_set_allocated_created_at(
    ::PROTOBUF_NAMESPACE_ID::Timestamp* created_at) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.created_at_);
  }
  _impl_.created_at_ = created_at;
  if (created_at) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:coretex.agent.v1.BusPacket.created_at)
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* BusPacket::release_created_at() {
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.created_at_;
  _impl_.created_at_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* BusPacket::unsafe_arena_release_created_at() {
  // @@protoc_insertion_point(field_release:coretex.agent.v1.BusPacket.created_at)
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.created_at_;
  _impl_.created_at_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* BusPacket::_internal_mutable_created_at() {
  
  if (_impl_.created_at_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Timestamp>(GetArenaForAllocation());
    _impl_.created_at_ = p;
  }
  return _impl_.created_at_;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* BusPacket::mutable_created_at() {
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _msg = _internal_mutable_created_at();
  // @@protoc_insertion_point(field_mutable:coretex.agent.v1.BusPacket.created_at)
  return _msg;
}
inline void BusPacket::set_allocated_created_at(::PROTOBUF_NAMESPACE_ID::Timestamp* created_at) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.created_at_);
  }
  if (created_at) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(created_at));
    if (message_arena != submessage_arena) {
      created_at = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, created_at, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.created_at_ = created_at;
  // @@protoc_insertion_point(field_set_allocated:coretex.agent.v1.BusPacket.created_at)
}

// int32 protocol_version = 4;
inline void BusPacket::clear_protocol_version() {
  _impl_.protocol_version_ = 0;
}
inline int32_t BusPacket::_internal_protocol_version() const {
  return _impl_.protocol_version_;
}
inline int32_t BusPacket::protocol_version() const {
  // @@protoc_insertion_point(field_get:coretex.agent.v1.BusPacket.protocol_version)
  return _internal_protocol_version();
}
inline void BusPacket::_internal_set_protocol_version(int32_t value) {
  
  _impl_.protocol_version_ = value;
}
inline void BusPacket::set_protocol_version(int32_t value) {
  _internal_set_protocol_version(value);
  // @@protoc_insertion_point(field_set:coretex.agent.v1.BusPacket.protocol_version)
}

// .coretex.agent.v1.JobRequest job_request = 10;
inline bool BusPacket::_internal_has_job_request() const {
  return payload_case() == kJobRequest;
}
inline bool BusPacket::has_job_request() const {
  return _internal_has_job_request();
}
inline void BusPacket::set_has_job_request() {
  _impl_._oneof_case_[0] = kJobRequest;
}
inline ::coretex::agent::v1::JobRequest* BusPacket::release_job_request() {
  // @@protoc_insertion_point(field_release:coretex.agent.v1.BusPacket.job_request)
  if (_internal_has_job_request()) {
    clear_has_payload();
    ::coretex::agent::v1::JobRequest* temp = _impl_.payload_.job_request_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.job_request_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::coretex::agent::v1::JobRequest& BusPacket::_internal_job_request() const {
  return _internal_has_job_request()
      ? *_impl_.payload_.job_request_
      : reinterpret_cast< ::coretex::agent::v1::JobRequest&>(::coretex::agent::v1::_JobRequest_default_instance_);
}
inline const ::coretex::agent::v1::JobRequest& BusPacket::job_request() const {
  // @@protoc_insertion_point(field_get:coretex.agent.v1.BusPacket.job_request)
  return _internal_job_request();
}
inline ::coretex::agent::v1::JobRequest* BusPacket::unsafe_arena_release_job_request() {
  // @@protoc_insertion_point(field_unsafe_arena_release:coretex.agent.v1.BusPacket.job_request)
  if (_internal_has_job_request()) {
    clear_has_payload();
    ::coretex::agent::v1::JobRequest* temp = _impl_.payload_.job_request_;
    _impl_.payload_.job_request_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void BusPacket::unsafe_arena_set_allocated_job_request(::coretex::agent::v1::JobRequest* job_request) {
  clear_payload();
  if (job_request) {
    set_has_job_request();
    _impl_.payload_.job_request_ = job_request;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:coretex.agent.v1.BusPacket.job_request)
}
inline ::coretex::agent::v1::JobRequest* BusPacket::_internal_mutable_job_request() {
  if (!_internal_has_job_request()) {
    clear_payload();
    set_has_job_request();
    _impl_.payload_.job_request_ = CreateMaybeMessage< ::coretex::agent::v1::JobRequest >(GetArenaForAllocation());
  }
  return _impl_.payload_.job_request_;
}
inline ::coretex::agent::v1::JobRequest* BusPacket::mutable_job_request() {
  ::coretex::agent::v1::JobRequest* _msg = _internal_mutable_job_request();
  // @@protoc_insertion_point(field_mutable:coretex.agent.v1.BusPacket.job_request)
  return _msg;
}

// .coretex.agent.v1.JobResult job_result = 11;
inline bool BusPacket::_internal_has_job_result() const {
  return payload_case() == kJobResult;
}
inline bool BusPacket::has_job_result() const {
  return _internal_has_job_result();
}
inline void BusPacket::set_has_job_result() {
  _impl_._oneof_case_[0] = kJobResult;
}
inline ::coretex::agent::v1::JobResult* BusPacket::release_job_result() {
  // @@protoc_insertion_point(field_release:coretex.agent.v1.BusPacket.job_result)
  if (_internal_has_job_result()) {
    clear_has_payload();
    ::coretex::agent::v1::JobResult* temp = _impl_.payload_.job_result_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.job_result_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::coretex::agent::v1::JobResult& BusPacket::_internal_job_result() const {
  return _internal_has_job_result()
      ? *_impl_.payload_.job_result_
      : reinterpret_cast< ::coretex::agent::v1::JobResult&>(::coretex::agent::v1::_JobResult_default_instance_);
}
inline const ::coretex::agent::v1::JobResult& BusPacket::job_result() const {
  // @@protoc_insertion_point(field_get:coretex.agent.v1.BusPacket.job_result)
  return _internal_job_result();
}
inline ::coretex::agent::v1::JobResult* BusPacket::unsafe_arena_release_job_result() {
  // @@protoc_insertion_point(field_unsafe_arena_release:coretex.agent.v1.BusPacket.job_result)
  if (_internal_has_job_result()) {
    clear_has_payload();
    ::coretex::agent::v1::JobResult* temp = _impl_.payload_.job_result_;
    _impl_.payload_.job_result_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void BusPacket::unsafe_arena_set_allocated_job_result(::coretex::agent::v1::JobResult* job_result) {
  clear_payload();
  if (job_result) {
    set_has_job_result();
    _impl_.payload_.job_result_ = job_result;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:coretex.agent.v1.BusPacket.job_result)
}
inline ::coretex::agent::v1::JobResult* BusPacket::_internal_mutable_job_result() {
  if (!_internal_has_job_result()) {
    clear_payload();
    set_has_job_result();
    _impl_.payload_.job_result_ = CreateMaybeMessage< ::coretex::agent::v1::JobResult >(GetArenaForAllocation());
  }
  return _impl_.payload_.job_result_;
}
inline ::coretex::agent::v1::JobResult* BusPacket::mutable_job_result() {
  ::coretex::agent::v1::JobResult* _msg = _internal_mutable_job_result();
  // @@protoc_insertion_point(field_mutable:coretex.agent.v1.BusPacket.job_result)
  return _msg;
}

// .coretex.agent.v1.Heartbeat heartbeat = 12;
inline bool BusPacket::_internal_has_heartbeat() const {
  return payload_case() == kHeartbeat;
}
inline bool BusPacket::has_heartbeat() const {
  return _internal_has_heartbeat();
}
inline void BusPacket::set_has_heartbeat() {
  _impl_._oneof_case_[0] = kHeartbeat;
}
inline ::coretex::agent::v1::Heartbeat* BusPacket::release_heartbeat() {
  // @@protoc_insertion_point(field_release:coretex.agent.v1.BusPacket.heartbeat)
  if (_internal_has_heartbeat()) {
    clear_has_payload();
    ::coretex::agent::v1::Heartbeat* temp = _impl_.payload_.heartbeat_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.heartbeat_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::coretex::agent::v1::Heartbeat& BusPacket::_internal_heartbeat() const {
  return _internal_has_heartbeat()
      ? *_impl_.payload_.heartbeat_
      : reinterpret_cast< ::coretex::agent::v1::Heartbeat&>(::coretex::agent::v1::_Heartbeat_default_instance_);
}
inline const ::coretex::agent::v1::Heartbeat& BusPacket::heartbeat() const {
  // @@protoc_insertion_point(field_get:coretex.agent.v1.BusPacket.heartbeat)
  return _internal_heartbeat();
}
inline ::coretex::agent::v1::Heartbeat* BusPacket::unsafe_arena_release_heartbeat() {
  // @@protoc_insertion_point(field_unsafe_arena_release:coretex.agent.v1.BusPacket.heartbeat)
  if (_internal_has_heartbeat()) {
    clear_has_payload();
    ::coretex::agent::v1::Heartbeat* temp = _impl_.payload_.heartbeat_;
    _impl_.payload_.heartbeat_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void BusPacket::unsafe_arena_set_allocated_heartbeat(::coretex::agent::v1::Heartbeat* heartbeat) {
  clear_payload();
  if (heartbeat) {
    set_has_heartbeat();
    _impl_.payload_.heartbeat_ = heartbeat;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:coretex.agent.v1.BusPacket.heartbeat)
}
inline ::coretex::agent::v1::Heartbeat* BusPacket::_internal_mutable_heartbeat() {
  if (!_internal_has_heartbeat()) {
    clear_payload();
    set_has_heartbeat();
    _impl_.payload_.heartbeat_ = CreateMaybeMessage< ::coretex::agent::v1::Heartbeat >(GetArenaForAllocation());
  }
  return _impl_.payload_.heartbeat_;
}
inline ::coretex::agent::v1::Heartbeat* BusPacket::mutable_heartbeat() {
  ::coretex::agent::v1::Heartbeat* _msg = _internal_mutable_heartbeat();
  // @@protoc_insertion_point(field_mutable:coretex.agent.v1.BusPacket.heartbeat)
  return _msg;
}

// .coretex.agent.v1.SystemAlert alert = 13;
inline bool BusPacket::_internal_has_alert() const {
  return payload_case() == kAlert;
}
inline bool BusPacket::has_alert() const {
  return _internal_has_alert();
}
inline void BusPacket::set_has_alert() {
  _impl_._oneof_case_[0] = kAlert;
}
inline ::coretex::agent::v1::SystemAlert* BusPacket::release_alert() {
  // @@protoc_insertion_point(field_release:coretex.agent.v1.BusPacket.alert)
  if (_internal_has_alert()) {
    clear_has_payload();
    ::coretex::agent::v1::SystemAlert* temp = _impl_.payload_.alert_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.alert_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::coretex::agent::v1::SystemAlert& BusPacket::_internal_alert() const {
  return _internal_has_alert()
      ? *_impl_.payload_.alert_
      : reinterpret_cast< ::coretex::agent::v1::SystemAlert&>(::coretex::agent::v1::_SystemAlert_default_instance_);
}
inline const ::coretex::agent::v1::SystemAlert& BusPacket::alert() const {
  // @@protoc_insertion_point(field_get:coretex.agent.v1.BusPacket.alert)
  return _internal_alert();
}
inline ::coretex::agent::v1::SystemAlert* BusPacket::unsafe_arena_release_alert() {
  // @@protoc_insertion_point(field_unsafe_arena_release:coretex.agent.v1.BusPacket.alert)
  if (_internal_has_alert()) {
    clear_has_payload();
    ::coretex::agent::v1::SystemAlert* temp = _impl_.payload_.alert_;
    _impl_.payload_.alert_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void BusPacket::unsafe_arena_set_allocated_alert(::coretex::agent::v1::SystemAlert* alert) {
  clear_payload();
  if (alert) {
    set_has_alert();
    _impl_.payload_.alert_ = alert;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:coretex.agent.v1.BusPacket.alert)
}
inline ::coretex::agent::v1::SystemAlert* BusPacket::_internal_mutable_alert() {
  if (!_internal_has_alert()) {
    clear_payload();
    set_has_alert();
    _impl_.payload_.alert_ = CreateMaybeMessage< ::coretex::agent::v1::SystemAlert >(GetArenaForAllocation());
  }
  return _impl_.payload_.alert_;
}
inline ::coretex::agent::v1::SystemAlert* BusPacket::mutable_alert() {
  ::coretex::agent::v1::SystemAlert* _msg = _internal_mutable_alert();
  // @@protoc_insertion_point(field_mutable:coretex.agent.v1.BusPacket.alert)
  return _msg;
}

// bytes signature = 14;
inline void BusPacket::clear_signature() {
  _impl_.signature_.ClearToEmpty();
}
inline const std::string& BusPacket::signature() const {
  // @@protoc_insertion_point(field_get:coretex.agent.v1.BusPacket.signature)
  return _internal_signature();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void BusPacket::set_signature(ArgT0&& arg0, ArgT... args) {
 
 _impl_.signature_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:coretex.agent.v1.BusPacket.signature)
}
inline std::string* BusPacket::mutable_signature() {
  std::string* _s = _internal_mutable_signature();
  // @@protoc_insertion_point(field_mutable:coretex.agent.v1.BusPacket.signature)
  return _s;
}
inline const std::string& BusPacket::_internal_signature() const {
  return _impl_.signature_.Get();
}
inline void BusPacket::_internal_set_signature(const std::string& value) {
  
  _impl_.signature_.Set(value, GetArenaForAllocation());
}
inline std::string* BusPacket::_internal_mutable_signature() {
  
  return _impl_.signature_.Mutable(GetArenaForAllocation());
}
inline std::string* BusPacket::release_signature() {
  // @@protoc_insertion_point(field_release:coretex.agent.v1.BusPacket.signature)
  return _impl_.signature_.Release();
}
inline void BusPacket::set_allocated_signature(std::string* signature) {
  if (signature != nullptr) {
    
  } else {
    
  }
  _impl_.signature_.SetAllocated(signature, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.signature_.IsDefault()) {
    _impl_.signature_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:coretex.agent.v1.BusPacket.signature)
}

inline bool BusPacket::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void BusPacket::clear_has_payload() {
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline BusPacket::PayloadCase BusPacket::payload_case() const {
  return BusPacket::PayloadCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace agent
}  // namespace coretex

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_coretex_2fagent_2fv1_2fbuspacket_2eproto
