// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coretex/agent/v1/buspacket.proto

#include "coretex/agent/v1/buspacket.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace coretex {
namespace agent {
namespace v1 {
PROTOBUF_CONSTEXPR BusPacket::BusPacket(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.trace_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.sender_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.signature_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.created_at_)*/nullptr
  , /*decltype(_impl_.protocol_version_)*/0
  , /*decltype(_impl_.payload_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct BusPacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BusPacketDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BusPacketDefaultTypeInternal() {}
  union {
    BusPacket _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BusPacketDefaultTypeInternal _BusPacket_default_instance_;
}  // namespace v1
}  // namespace agent
}  // namespace coretex
static ::_pb::Metadata file_level_metadata_coretex_2fagent_2fv1_2fbuspacket_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_coretex_2fagent_2fv1_2fbuspacket_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_coretex_2fagent_2fv1_2fbuspacket_2eproto = nullptr;

const uint32_t TableStruct_coretex_2fagent_2fv1_2fbuspacket_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::coretex::agent::v1::BusPacket, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::coretex::agent::v1::BusPacket, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::coretex::agent::v1::BusPacket, _impl_.trace_id_),
  PROTOBUF_FIELD_OFFSET(::coretex::agent::v1::BusPacket, _impl_.sender_id_),
  PROTOBUF_FIELD_OFFSET(::coretex::agent::v1::BusPacket, _impl_.created_at_),
  PROTOBUF_FIELD_OFFSET(::coretex::agent::v1::BusPacket, _impl_.protocol_version_),
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::coretex::agent::v1::BusPacket, _impl_.signature_),
  PROTOBUF_FIELD_OFFSET(::coretex::agent::v1::BusPacket, _impl_.payload_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::coretex::agent::v1::BusPacket)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::coretex::agent::v1::_BusPacket_default_instance_._instance,
};

const char descriptor_table_protodef_coretex_2fagent_2fv1_2fbuspacket_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\037coretex/agent/v1/buspacket.proto\022\017corte"
  "x.agent.v1\032\037google/protobuf/timestamp.pr"
  "oto\032\031coretex/agent/v1/job.proto\032\037coretex/a"
  "gent/v1/heartbeat.proto\032\033coretex/agent/v1"
  "/alert.proto\"\336\002\n\tBusPacket\022\020\n\010trace_id\030\001"
  " \001(\t\022\021\n\tsender_id\030\002 \001(\t\022.\n\ncreated_at\030\003 "
  "\001(\0132\032.google.protobuf.Timestamp\022\030\n\020proto"
  "col_version\030\004 \001(\005\0222\n\013job_request\030\n \001(\0132\033"
  ".coretex.agent.v1.JobRequestH\000\0220\n\njob_res"
  "ult\030\013 \001(\0132\032.coretex.agent.v1.JobResultH\000\022"
  "/\n\theartbeat\030\014 \001(\0132\032.coretex.agent.v1.Hea"
  "rtbeatH\000\022-\n\005alert\030\r \001(\0132\034.coretex.agent.v"
  "1.SystemAlertH\000\022\021\n\tsignature\030\016 \001(\014B\t\n\007pa"
  "yloadB\177\n\026ai.coretex.cap.agent.v1P\001Z+githu"
  "b.com/coretexos/cap/go/coretex/agent/v1\252\002"
  "\017coretex.Agent.V1\312\002\017coretex\\Agent\\V1\352\002\021Cor"
  "tex::Agent::V1b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_coretex_2fagent_2fv1_2fbuspacket_2eproto_deps[4] = {
  &::descriptor_table_coretex_2fagent_2fv1_2falert_2eproto,
  &::descriptor_table_coretex_2fagent_2fv1_2fheartbeat_2eproto,
  &::descriptor_table_coretex_2fagent_2fv1_2fjob_2eproto,
  &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
};
static ::_pbi::once_flag descriptor_table_coretex_2fagent_2fv1_2fbuspacket_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_coretex_2fagent_2fv1_2fbuspacket_2eproto = {
    false, false, 662, descriptor_table_protodef_coretex_2fagent_2fv1_2fbuspacket_2eproto,
    "coretex/agent/v1/buspacket.proto",
    &descriptor_table_coretex_2fagent_2fv1_2fbuspacket_2eproto_once, descriptor_table_coretex_2fagent_2fv1_2fbuspacket_2eproto_deps, 4, 1,
    schemas, file_default_instances, TableStruct_coretex_2fagent_2fv1_2fbuspacket_2eproto::offsets,
    file_level_metadata_coretex_2fagent_2fv1_2fbuspacket_2eproto, file_level_enum_descriptors_coretex_2fagent_2fv1_2fbuspacket_2eproto,
    file_level_service_descriptors_coretex_2fagent_2fv1_2fbuspacket_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_coretex_2fagent_2fv1_2fbuspacket_2eproto_getter() {
  return &descriptor_table_coretex_2fagent_2fv1_2fbuspacket_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_coretex_2fagent_2fv1_2fbuspacket_2eproto(&descriptor_table_coretex_2fagent_2fv1_2fbuspacket_2eproto);
namespace coretex {
namespace agent {
namespace v1 {

// ===================================================================

class BusPacket::_Internal {
 public:
  static const ::PROTOBUF_NAMESPACE_ID::Timestamp& created_at(const BusPacket* msg);
  static const ::coretex::agent::v1::JobRequest& job_request(const BusPacket* msg);
  static const ::coretex::agent::v1::JobResult& job_result(const BusPacket* msg);
  static const ::coretex::agent::v1::Heartbeat& heartbeat(const BusPacket* msg);
  static const ::coretex::agent::v1::SystemAlert& alert(const BusPacket* msg);
};

const ::PROTOBUF_NAMESPACE_ID::Timestamp&
BusPacket::_Internal::created_at(const BusPacket* msg) {
  return *msg->_impl_.created_at_;
}
const ::coretex::agent::v1::JobRequest&
BusPacket::_Internal::job_request(const BusPacket* msg) {
  return *msg->_impl_.payload_.job_request_;
}
const ::coretex::agent::v1::JobResult&
BusPacket::_Internal::job_result(const BusPacket* msg) {
  return *msg->_impl_.payload_.job_result_;
}
const ::coretex::agent::v1::Heartbeat&
BusPacket::_Internal::heartbeat(const BusPacket* msg) {
  return *msg->_impl_.payload_.heartbeat_;
}
const ::coretex::agent::v1::SystemAlert&
BusPacket::_Internal::alert(const BusPacket* msg) {
  return *msg->_impl_.payload_.alert_;
}
void BusPacket::clear_created_at() {
  if (GetArenaForAllocation() == nullptr && _impl_.created_at_ != nullptr) {
    delete _impl_.created_at_;
  }
  _impl_.created_at_ = nullptr;
}
void BusPacket::set_allocated_job_request(::coretex::agent::v1::JobRequest* job_request) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (job_request) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(job_request));
    if (message_arena != submessage_arena) {
      job_request = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, job_request, submessage_arena);
    }
    set_has_job_request();
    _impl_.payload_.job_request_ = job_request;
  }
  // @@protoc_insertion_point(field_set_allocated:coretex.agent.v1.BusPacket.job_request)
}
void BusPacket::clear_job_request() {
  if (_internal_has_job_request()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.job_request_;
    }
    clear_has_payload();
  }
}
void BusPacket::set_allocated_job_result(::coretex::agent::v1::JobResult* job_result) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (job_result) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(job_result));
    if (message_arena != submessage_arena) {
      job_result = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, job_result, submessage_arena);
    }
    set_has_job_result();
    _impl_.payload_.job_result_ = job_result;
  }
  // @@protoc_insertion_point(field_set_allocated:coretex.agent.v1.BusPacket.job_result)
}
void BusPacket::clear_job_result() {
  if (_internal_has_job_result()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.job_result_;
    }
    clear_has_payload();
  }
}
void BusPacket::set_allocated_heartbeat(::coretex::agent::v1::Heartbeat* heartbeat) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (heartbeat) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(heartbeat));
    if (message_arena != submessage_arena) {
      heartbeat = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, heartbeat, submessage_arena);
    }
    set_has_heartbeat();
    _impl_.payload_.heartbeat_ = heartbeat;
  }
  // @@protoc_insertion_point(field_set_allocated:coretex.agent.v1.BusPacket.heartbeat)
}
void BusPacket::clear_heartbeat() {
  if (_internal_has_heartbeat()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.heartbeat_;
    }
    clear_has_payload();
  }
}
void BusPacket::set_allocated_alert(::coretex::agent::v1::SystemAlert* alert) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (alert) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(alert));
    if (message_arena != submessage_arena) {
      alert = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, alert, submessage_arena);
    }
    set_has_alert();
    _impl_.payload_.alert_ = alert;
  }
  // @@protoc_insertion_point(field_set_allocated:coretex.agent.v1.BusPacket.alert)
}
void BusPacket::clear_alert() {
  if (_internal_has_alert()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.alert_;
    }
    clear_has_payload();
  }
}
BusPacket::BusPacket(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:coretex.agent.v1.BusPacket)
}
BusPacket::BusPacket(const BusPacket& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  BusPacket* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.trace_id_){}
    , decltype(_impl_.sender_id_){}
    , decltype(_impl_.signature_){}
    , decltype(_impl_.created_at_){nullptr}
    , decltype(_impl_.protocol_version_){}
    , decltype(_impl_.payload_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.trace_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.trace_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_trace_id().empty()) {
    _this->_impl_.trace_id_.Set(from._internal_trace_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.sender_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sender_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_sender_id().empty()) {
    _this->_impl_.sender_id_.Set(from._internal_sender_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.signature_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.signature_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_signature().empty()) {
    _this->_impl_.signature_.Set(from._internal_signature(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_created_at()) {
    _this->_impl_.created_at_ = new ::PROTOBUF_NAMESPACE_ID::Timestamp(*from._impl_.created_at_);
  }
  _this->_impl_.protocol_version_ = from._impl_.protocol_version_;
  clear_has_payload();
  switch (from.payload_case()) {
    case kJobRequest: {
      _this->_internal_mutable_job_request()->::coretex::agent::v1::JobRequest::MergeFrom(
          from._internal_job_request());
      break;
    }
    case kJobResult: {
      _this->_internal_mutable_job_result()->::coretex::agent::v1::JobResult::MergeFrom(
          from._internal_job_result());
      break;
    }
    case kHeartbeat: {
      _this->_internal_mutable_heartbeat()->::coretex::agent::v1::Heartbeat::MergeFrom(
          from._internal_heartbeat());
      break;
    }
    case kAlert: {
      _this->_internal_mutable_alert()->::coretex::agent::v1::SystemAlert::MergeFrom(
          from._internal_alert());
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:coretex.agent.v1.BusPacket)
}

inline void BusPacket::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.trace_id_){}
    , decltype(_impl_.sender_id_){}
    , decltype(_impl_.signature_){}
    , decltype(_impl_.created_at_){nullptr}
    , decltype(_impl_.protocol_version_){0}
    , decltype(_impl_.payload_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  _impl_.trace_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.trace_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.sender_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sender_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.signature_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.signature_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  clear_has_payload();
}

BusPacket::~BusPacket() {
  // @@protoc_insertion_point(destructor:coretex.agent.v1.BusPacket)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BusPacket::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.trace_id_.Destroy();
  _impl_.sender_id_.Destroy();
  _impl_.signature_.Destroy();
  if (this != internal_default_instance()) delete _impl_.created_at_;
  if (has_payload()) {
    clear_payload();
  }
}

void BusPacket::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BusPacket::clear_payload() {
// @@protoc_insertion_point(one_of_clear_start:coretex.agent.v1.BusPacket)
  switch (payload_case()) {
    case kJobRequest: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.job_request_;
      }
      break;
    }
    case kJobResult: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.job_result_;
      }
      break;
    }
    case kHeartbeat: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.heartbeat_;
      }
      break;
    }
    case kAlert: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.alert_;
      }
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}


void BusPacket::Clear() {
// @@protoc_insertion_point(message_clear_start:coretex.agent.v1.BusPacket)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.trace_id_.ClearToEmpty();
  _impl_.sender_id_.ClearToEmpty();
  _impl_.signature_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.created_at_ != nullptr) {
    delete _impl_.created_at_;
  }
  _impl_.created_at_ = nullptr;
  _impl_.protocol_version_ = 0;
  clear_payload();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BusPacket::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string trace_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_trace_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "coretex.agent.v1.BusPacket.trace_id"));
        } else
          goto handle_unusual;
        continue;
      // string sender_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_sender_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "coretex.agent.v1.BusPacket.sender_id"));
        } else
          goto handle_unusual;
        continue;
      // .google.protobuf.Timestamp created_at = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_created_at(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 protocol_version = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.protocol_version_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .coretex.agent.v1.JobRequest job_request = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 82)) {
          ptr = ctx->ParseMessage(_internal_mutable_job_request(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .coretex.agent.v1.JobResult job_result = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 90)) {
          ptr = ctx->ParseMessage(_internal_mutable_job_result(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .coretex.agent.v1.Heartbeat heartbeat = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 98)) {
          ptr = ctx->ParseMessage(_internal_mutable_heartbeat(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .coretex.agent.v1.SystemAlert alert = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 106)) {
          ptr = ctx->ParseMessage(_internal_mutable_alert(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes signature = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 114)) {
          auto str = _internal_mutable_signature();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BusPacket::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:coretex.agent.v1.BusPacket)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string trace_id = 1;
  if (!this->_internal_trace_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_trace_id().data(), static_cast<int>(this->_internal_trace_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "coretex.agent.v1.BusPacket.trace_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_trace_id(), target);
  }

  // string sender_id = 2;
  if (!this->_internal_sender_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sender_id().data(), static_cast<int>(this->_internal_sender_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "coretex.agent.v1.BusPacket.sender_id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_sender_id(), target);
  }

  // .google.protobuf.Timestamp created_at = 3;
  if (this->_internal_has_created_at()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::created_at(this),
        _Internal::created_at(this).GetCachedSize(), target, stream);
  }

  // int32 protocol_version = 4;
  if (this->_internal_protocol_version() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_protocol_version(), target);
  }

  // .coretex.agent.v1.JobRequest job_request = 10;
  if (_internal_has_job_request()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(10, _Internal::job_request(this),
        _Internal::job_request(this).GetCachedSize(), target, stream);
  }

  // .coretex.agent.v1.JobResult job_result = 11;
  if (_internal_has_job_result()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(11, _Internal::job_result(this),
        _Internal::job_result(this).GetCachedSize(), target, stream);
  }

  // .coretex.agent.v1.Heartbeat heartbeat = 12;
  if (_internal_has_heartbeat()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(12, _Internal::heartbeat(this),
        _Internal::heartbeat(this).GetCachedSize(), target, stream);
  }

  // .coretex.agent.v1.SystemAlert alert = 13;
  if (_internal_has_alert()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(13, _Internal::alert(this),
        _Internal::alert(this).GetCachedSize(), target, stream);
  }

  // bytes signature = 14;
  if (!this->_internal_signature().empty()) {
    target = stream->WriteBytesMaybeAliased(
        14, this->_internal_signature(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:coretex.agent.v1.BusPacket)
  return target;
}

size_t BusPacket::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:coretex.agent.v1.BusPacket)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string trace_id = 1;
  if (!this->_internal_trace_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_trace_id());
  }

  // string sender_id = 2;
  if (!this->_internal_sender_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sender_id());
  }

  // bytes signature = 14;
  if (!this->_internal_signature().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_signature());
  }

  // .google.protobuf.Timestamp created_at = 3;
  if (this->_internal_has_created_at()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.created_at_);
  }

  // int32 protocol_version = 4;
  if (this->_internal_protocol_version() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_protocol_version());
  }

  switch (payload_case()) {
    // .coretex.agent.v1.JobRequest job_request = 10;
    case kJobRequest: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.job_request_);
      break;
    }
    // .coretex.agent.v1.JobResult job_result = 11;
    case kJobResult: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.job_result_);
      break;
    }
    // .coretex.agent.v1.Heartbeat heartbeat = 12;
    case kHeartbeat: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.heartbeat_);
      break;
    }
    // .coretex.agent.v1.SystemAlert alert = 13;
    case kAlert: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.alert_);
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BusPacket::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    BusPacket::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BusPacket::GetClassData() const { return &_class_data_; }


void BusPacket::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<BusPacket*>(&to_msg);
  auto& from = static_cast<const BusPacket&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:coretex.agent.v1.BusPacket)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_trace_id().empty()) {
    _this->_internal_set_trace_id(from._internal_trace_id());
  }
  if (!from._internal_sender_id().empty()) {
    _this->_internal_set_sender_id(from._internal_sender_id());
  }
  if (!from._internal_signature().empty()) {
    _this->_internal_set_signature(from._internal_signature());
  }
  if (from._internal_has_created_at()) {
    _this->_internal_mutable_created_at()->::PROTOBUF_NAMESPACE_ID::Timestamp::MergeFrom(
        from._internal_created_at());
  }
  if (from._internal_protocol_version() != 0) {
    _this->_internal_set_protocol_version(from._internal_protocol_version());
  }
  switch (from.payload_case()) {
    case kJobRequest: {
      _this->_internal_mutable_job_request()->::coretex::agent::v1::JobRequest::MergeFrom(
          from._internal_job_request());
      break;
    }
    case kJobResult: {
      _this->_internal_mutable_job_result()->::coretex::agent::v1::JobResult::MergeFrom(
          from._internal_job_result());
      break;
    }
    case kHeartbeat: {
      _this->_internal_mutable_heartbeat()->::coretex::agent::v1::Heartbeat::MergeFrom(
          from._internal_heartbeat());
      break;
    }
    case kAlert: {
      _this->_internal_mutable_alert()->::coretex::agent::v1::SystemAlert::MergeFrom(
          from._internal_alert());
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BusPacket::CopyFrom(const BusPacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:coretex.agent.v1.BusPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BusPacket::IsInitialized() const {
  return true;
}

void BusPacket::InternalSwap(BusPacket* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.trace_id_, lhs_arena,
      &other->_impl_.trace_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.sender_id_, lhs_arena,
      &other->_impl_.sender_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.signature_, lhs_arena,
      &other->_impl_.signature_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(BusPacket, _impl_.protocol_version_)
      + sizeof(BusPacket::_impl_.protocol_version_)
      - PROTOBUF_FIELD_OFFSET(BusPacket, _impl_.created_at_)>(
          reinterpret_cast<char*>(&_impl_.created_at_),
          reinterpret_cast<char*>(&other->_impl_.created_at_));
  swap(_impl_.payload_, other->_impl_.payload_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata BusPacket::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_coretex_2fagent_2fv1_2fbuspacket_2eproto_getter, &descriptor_table_coretex_2fagent_2fv1_2fbuspacket_2eproto_once,
      file_level_metadata_coretex_2fagent_2fv1_2fbuspacket_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace agent
}  // namespace coretex
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::coretex::agent::v1::BusPacket*
Arena::CreateMaybeMessage< ::coretex::agent::v1::BusPacket >(Arena* arena) {
  return Arena::CreateMessageInternal< ::coretex::agent::v1::BusPacket >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
