// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coretex/agent/v1/heartbeat.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_coretex_2fagent_2fv1_2fheartbeat_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_coretex_2fagent_2fv1_2fheartbeat_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_coretex_2fagent_2fv1_2fheartbeat_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_coretex_2fagent_2fv1_2fheartbeat_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_coretex_2fagent_2fv1_2fheartbeat_2eproto;
namespace coretex {
namespace agent {
namespace v1 {
class Heartbeat;
struct HeartbeatDefaultTypeInternal;
extern HeartbeatDefaultTypeInternal _Heartbeat_default_instance_;
}  // namespace v1
}  // namespace agent
}  // namespace coretex
PROTOBUF_NAMESPACE_OPEN
template<> ::coretex::agent::v1::Heartbeat* Arena::CreateMaybeMessage<::coretex::agent::v1::Heartbeat>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace coretex {
namespace agent {
namespace v1 {

// ===================================================================

class Heartbeat final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:coretex.agent.v1.Heartbeat) */ {
 public:
  inline Heartbeat() : Heartbeat(nullptr) {}
  ~Heartbeat() override;
  explicit PROTOBUF_CONSTEXPR Heartbeat(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Heartbeat(const Heartbeat& from);
  Heartbeat(Heartbeat&& from) noexcept
    : Heartbeat() {
    *this = ::std::move(from);
  }

  inline Heartbeat& operator=(const Heartbeat& from) {
    CopyFrom(from);
    return *this;
  }
  inline Heartbeat& operator=(Heartbeat&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Heartbeat& default_instance() {
    return *internal_default_instance();
  }
  static inline const Heartbeat* internal_default_instance() {
    return reinterpret_cast<const Heartbeat*>(
               &_Heartbeat_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Heartbeat& a, Heartbeat& b) {
    a.Swap(&b);
  }
  inline void Swap(Heartbeat* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Heartbeat* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Heartbeat* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Heartbeat>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Heartbeat& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Heartbeat& from) {
    Heartbeat::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Heartbeat* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "coretex.agent.v1.Heartbeat";
  }
  protected:
  explicit Heartbeat(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCapabilitiesFieldNumber = 7,
    kWorkerIdFieldNumber = 1,
    kRegionFieldNumber = 2,
    kTypeFieldNumber = 3,
    kPoolFieldNumber = 11,
    kCpuLoadFieldNumber = 4,
    kGpuUtilizationFieldNumber = 5,
    kActiveJobsFieldNumber = 6,
    kMaxParallelJobsFieldNumber = 12,
  };
  // repeated string capabilities = 7;
  int capabilities_size() const;
  private:
  int _internal_capabilities_size() const;
  public:
  void clear_capabilities();
  const std::string& capabilities(int index) const;
  std::string* mutable_capabilities(int index);
  void set_capabilities(int index, const std::string& value);
  void set_capabilities(int index, std::string&& value);
  void set_capabilities(int index, const char* value);
  void set_capabilities(int index, const char* value, size_t size);
  std::string* add_capabilities();
  void add_capabilities(const std::string& value);
  void add_capabilities(std::string&& value);
  void add_capabilities(const char* value);
  void add_capabilities(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& capabilities() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_capabilities();
  private:
  const std::string& _internal_capabilities(int index) const;
  std::string* _internal_add_capabilities();
  public:

  // string worker_id = 1;
  void clear_worker_id();
  const std::string& worker_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_worker_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_worker_id();
  PROTOBUF_NODISCARD std::string* release_worker_id();
  void set_allocated_worker_id(std::string* worker_id);
  private:
  const std::string& _internal_worker_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_worker_id(const std::string& value);
  std::string* _internal_mutable_worker_id();
  public:

  // string region = 2;
  void clear_region();
  const std::string& region() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_region(ArgT0&& arg0, ArgT... args);
  std::string* mutable_region();
  PROTOBUF_NODISCARD std::string* release_region();
  void set_allocated_region(std::string* region);
  private:
  const std::string& _internal_region() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_region(const std::string& value);
  std::string* _internal_mutable_region();
  public:

  // string type = 3;
  void clear_type();
  const std::string& type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_type();
  PROTOBUF_NODISCARD std::string* release_type();
  void set_allocated_type(std::string* type);
  private:
  const std::string& _internal_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_type(const std::string& value);
  std::string* _internal_mutable_type();
  public:

  // string pool = 11;
  void clear_pool();
  const std::string& pool() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_pool(ArgT0&& arg0, ArgT... args);
  std::string* mutable_pool();
  PROTOBUF_NODISCARD std::string* release_pool();
  void set_allocated_pool(std::string* pool);
  private:
  const std::string& _internal_pool() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pool(const std::string& value);
  std::string* _internal_mutable_pool();
  public:

  // float cpu_load = 4;
  void clear_cpu_load();
  float cpu_load() const;
  void set_cpu_load(float value);
  private:
  float _internal_cpu_load() const;
  void _internal_set_cpu_load(float value);
  public:

  // float gpu_utilization = 5;
  void clear_gpu_utilization();
  float gpu_utilization() const;
  void set_gpu_utilization(float value);
  private:
  float _internal_gpu_utilization() const;
  void _internal_set_gpu_utilization(float value);
  public:

  // int32 active_jobs = 6;
  void clear_active_jobs();
  int32_t active_jobs() const;
  void set_active_jobs(int32_t value);
  private:
  int32_t _internal_active_jobs() const;
  void _internal_set_active_jobs(int32_t value);
  public:

  // int32 max_parallel_jobs = 12;
  void clear_max_parallel_jobs();
  int32_t max_parallel_jobs() const;
  void set_max_parallel_jobs(int32_t value);
  private:
  int32_t _internal_max_parallel_jobs() const;
  void _internal_set_max_parallel_jobs(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:coretex.agent.v1.Heartbeat)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> capabilities_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr worker_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr region_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr type_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr pool_;
    float cpu_load_;
    float gpu_utilization_;
    int32_t active_jobs_;
    int32_t max_parallel_jobs_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_coretex_2fagent_2fv1_2fheartbeat_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Heartbeat

// string worker_id = 1;
inline void Heartbeat::clear_worker_id() {
  _impl_.worker_id_.ClearToEmpty();
}
inline const std::string& Heartbeat::worker_id() const {
  // @@protoc_insertion_point(field_get:coretex.agent.v1.Heartbeat.worker_id)
  return _internal_worker_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Heartbeat::set_worker_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.worker_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:coretex.agent.v1.Heartbeat.worker_id)
}
inline std::string* Heartbeat::mutable_worker_id() {
  std::string* _s = _internal_mutable_worker_id();
  // @@protoc_insertion_point(field_mutable:coretex.agent.v1.Heartbeat.worker_id)
  return _s;
}
inline const std::string& Heartbeat::_internal_worker_id() const {
  return _impl_.worker_id_.Get();
}
inline void Heartbeat::_internal_set_worker_id(const std::string& value) {
  
  _impl_.worker_id_.Set(value, GetArenaForAllocation());
}
inline std::string* Heartbeat::_internal_mutable_worker_id() {
  
  return _impl_.worker_id_.Mutable(GetArenaForAllocation());
}
inline std::string* Heartbeat::release_worker_id() {
  // @@protoc_insertion_point(field_release:coretex.agent.v1.Heartbeat.worker_id)
  return _impl_.worker_id_.Release();
}
inline void Heartbeat::set_allocated_worker_id(std::string* worker_id) {
  if (worker_id != nullptr) {
    
  } else {
    
  }
  _impl_.worker_id_.SetAllocated(worker_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.worker_id_.IsDefault()) {
    _impl_.worker_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:coretex.agent.v1.Heartbeat.worker_id)
}

// string region = 2;
inline void Heartbeat::clear_region() {
  _impl_.region_.ClearToEmpty();
}
inline const std::string& Heartbeat::region() const {
  // @@protoc_insertion_point(field_get:coretex.agent.v1.Heartbeat.region)
  return _internal_region();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Heartbeat::set_region(ArgT0&& arg0, ArgT... args) {
 
 _impl_.region_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:coretex.agent.v1.Heartbeat.region)
}
inline std::string* Heartbeat::mutable_region() {
  std::string* _s = _internal_mutable_region();
  // @@protoc_insertion_point(field_mutable:coretex.agent.v1.Heartbeat.region)
  return _s;
}
inline const std::string& Heartbeat::_internal_region() const {
  return _impl_.region_.Get();
}
inline void Heartbeat::_internal_set_region(const std::string& value) {
  
  _impl_.region_.Set(value, GetArenaForAllocation());
}
inline std::string* Heartbeat::_internal_mutable_region() {
  
  return _impl_.region_.Mutable(GetArenaForAllocation());
}
inline std::string* Heartbeat::release_region() {
  // @@protoc_insertion_point(field_release:coretex.agent.v1.Heartbeat.region)
  return _impl_.region_.Release();
}
inline void Heartbeat::set_allocated_region(std::string* region) {
  if (region != nullptr) {
    
  } else {
    
  }
  _impl_.region_.SetAllocated(region, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.region_.IsDefault()) {
    _impl_.region_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:coretex.agent.v1.Heartbeat.region)
}

// string type = 3;
inline void Heartbeat::clear_type() {
  _impl_.type_.ClearToEmpty();
}
inline const std::string& Heartbeat::type() const {
  // @@protoc_insertion_point(field_get:coretex.agent.v1.Heartbeat.type)
  return _internal_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Heartbeat::set_type(ArgT0&& arg0, ArgT... args) {
 
 _impl_.type_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:coretex.agent.v1.Heartbeat.type)
}
inline std::string* Heartbeat::mutable_type() {
  std::string* _s = _internal_mutable_type();
  // @@protoc_insertion_point(field_mutable:coretex.agent.v1.Heartbeat.type)
  return _s;
}
inline const std::string& Heartbeat::_internal_type() const {
  return _impl_.type_.Get();
}
inline void Heartbeat::_internal_set_type(const std::string& value) {
  
  _impl_.type_.Set(value, GetArenaForAllocation());
}
inline std::string* Heartbeat::_internal_mutable_type() {
  
  return _impl_.type_.Mutable(GetArenaForAllocation());
}
inline std::string* Heartbeat::release_type() {
  // @@protoc_insertion_point(field_release:coretex.agent.v1.Heartbeat.type)
  return _impl_.type_.Release();
}
inline void Heartbeat::set_allocated_type(std::string* type) {
  if (type != nullptr) {
    
  } else {
    
  }
  _impl_.type_.SetAllocated(type, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.type_.IsDefault()) {
    _impl_.type_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:coretex.agent.v1.Heartbeat.type)
}

// float cpu_load = 4;
inline void Heartbeat::clear_cpu_load() {
  _impl_.cpu_load_ = 0;
}
inline float Heartbeat::_internal_cpu_load() const {
  return _impl_.cpu_load_;
}
inline float Heartbeat::cpu_load() const {
  // @@protoc_insertion_point(field_get:coretex.agent.v1.Heartbeat.cpu_load)
  return _internal_cpu_load();
}
inline void Heartbeat::_internal_set_cpu_load(float value) {
  
  _impl_.cpu_load_ = value;
}
inline void Heartbeat::set_cpu_load(float value) {
  _internal_set_cpu_load(value);
  // @@protoc_insertion_point(field_set:coretex.agent.v1.Heartbeat.cpu_load)
}

// float gpu_utilization = 5;
inline void Heartbeat::clear_gpu_utilization() {
  _impl_.gpu_utilization_ = 0;
}
inline float Heartbeat::_internal_gpu_utilization() const {
  return _impl_.gpu_utilization_;
}
inline float Heartbeat::gpu_utilization() const {
  // @@protoc_insertion_point(field_get:coretex.agent.v1.Heartbeat.gpu_utilization)
  return _internal_gpu_utilization();
}
inline void Heartbeat::_internal_set_gpu_utilization(float value) {
  
  _impl_.gpu_utilization_ = value;
}
inline void Heartbeat::set_gpu_utilization(float value) {
  _internal_set_gpu_utilization(value);
  // @@protoc_insertion_point(field_set:coretex.agent.v1.Heartbeat.gpu_utilization)
}

// int32 active_jobs = 6;
inline void Heartbeat::clear_active_jobs() {
  _impl_.active_jobs_ = 0;
}
inline int32_t Heartbeat::_internal_active_jobs() const {
  return _impl_.active_jobs_;
}
inline int32_t Heartbeat::active_jobs() const {
  // @@protoc_insertion_point(field_get:coretex.agent.v1.Heartbeat.active_jobs)
  return _internal_active_jobs();
}
inline void Heartbeat::_internal_set_active_jobs(int32_t value) {
  
  _impl_.active_jobs_ = value;
}
inline void Heartbeat::set_active_jobs(int32_t value) {
  _internal_set_active_jobs(value);
  // @@protoc_insertion_point(field_set:coretex.agent.v1.Heartbeat.active_jobs)
}

// repeated string capabilities = 7;
inline int Heartbeat::_internal_capabilities_size() const {
  return _impl_.capabilities_.size();
}
inline int Heartbeat::capabilities_size() const {
  return _internal_capabilities_size();
}
inline void Heartbeat::clear_capabilities() {
  _impl_.capabilities_.Clear();
}
inline std::string* Heartbeat::add_capabilities() {
  std::string* _s = _internal_add_capabilities();
  // @@protoc_insertion_point(field_add_mutable:coretex.agent.v1.Heartbeat.capabilities)
  return _s;
}
inline const std::string& Heartbeat::_internal_capabilities(int index) const {
  return _impl_.capabilities_.Get(index);
}
inline const std::string& Heartbeat::capabilities(int index) const {
  // @@protoc_insertion_point(field_get:coretex.agent.v1.Heartbeat.capabilities)
  return _internal_capabilities(index);
}
inline std::string* Heartbeat::mutable_capabilities(int index) {
  // @@protoc_insertion_point(field_mutable:coretex.agent.v1.Heartbeat.capabilities)
  return _impl_.capabilities_.Mutable(index);
}
inline void Heartbeat::set_capabilities(int index, const std::string& value) {
  _impl_.capabilities_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:coretex.agent.v1.Heartbeat.capabilities)
}
inline void Heartbeat::set_capabilities(int index, std::string&& value) {
  _impl_.capabilities_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:coretex.agent.v1.Heartbeat.capabilities)
}
inline void Heartbeat::set_capabilities(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.capabilities_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:coretex.agent.v1.Heartbeat.capabilities)
}
inline void Heartbeat::set_capabilities(int index, const char* value, size_t size) {
  _impl_.capabilities_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:coretex.agent.v1.Heartbeat.capabilities)
}
inline std::string* Heartbeat::_internal_add_capabilities() {
  return _impl_.capabilities_.Add();
}
inline void Heartbeat::add_capabilities(const std::string& value) {
  _impl_.capabilities_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:coretex.agent.v1.Heartbeat.capabilities)
}
inline void Heartbeat::add_capabilities(std::string&& value) {
  _impl_.capabilities_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:coretex.agent.v1.Heartbeat.capabilities)
}
inline void Heartbeat::add_capabilities(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.capabilities_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:coretex.agent.v1.Heartbeat.capabilities)
}
inline void Heartbeat::add_capabilities(const char* value, size_t size) {
  _impl_.capabilities_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:coretex.agent.v1.Heartbeat.capabilities)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
Heartbeat::capabilities() const {
  // @@protoc_insertion_point(field_list:coretex.agent.v1.Heartbeat.capabilities)
  return _impl_.capabilities_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
Heartbeat::mutable_capabilities() {
  // @@protoc_insertion_point(field_mutable_list:coretex.agent.v1.Heartbeat.capabilities)
  return &_impl_.capabilities_;
}

// string pool = 11;
inline void Heartbeat::clear_pool() {
  _impl_.pool_.ClearToEmpty();
}
inline const std::string& Heartbeat::pool() const {
  // @@protoc_insertion_point(field_get:coretex.agent.v1.Heartbeat.pool)
  return _internal_pool();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Heartbeat::set_pool(ArgT0&& arg0, ArgT... args) {
 
 _impl_.pool_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:coretex.agent.v1.Heartbeat.pool)
}
inline std::string* Heartbeat::mutable_pool() {
  std::string* _s = _internal_mutable_pool();
  // @@protoc_insertion_point(field_mutable:coretex.agent.v1.Heartbeat.pool)
  return _s;
}
inline const std::string& Heartbeat::_internal_pool() const {
  return _impl_.pool_.Get();
}
inline void Heartbeat::_internal_set_pool(const std::string& value) {
  
  _impl_.pool_.Set(value, GetArenaForAllocation());
}
inline std::string* Heartbeat::_internal_mutable_pool() {
  
  return _impl_.pool_.Mutable(GetArenaForAllocation());
}
inline std::string* Heartbeat::release_pool() {
  // @@protoc_insertion_point(field_release:coretex.agent.v1.Heartbeat.pool)
  return _impl_.pool_.Release();
}
inline void Heartbeat::set_allocated_pool(std::string* pool) {
  if (pool != nullptr) {
    
  } else {
    
  }
  _impl_.pool_.SetAllocated(pool, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.pool_.IsDefault()) {
    _impl_.pool_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:coretex.agent.v1.Heartbeat.pool)
}

// int32 max_parallel_jobs = 12;
inline void Heartbeat::clear_max_parallel_jobs() {
  _impl_.max_parallel_jobs_ = 0;
}
inline int32_t Heartbeat::_internal_max_parallel_jobs() const {
  return _impl_.max_parallel_jobs_;
}
inline int32_t Heartbeat::max_parallel_jobs() const {
  // @@protoc_insertion_point(field_get:coretex.agent.v1.Heartbeat.max_parallel_jobs)
  return _internal_max_parallel_jobs();
}
inline void Heartbeat::_internal_set_max_parallel_jobs(int32_t value) {
  
  _impl_.max_parallel_jobs_ = value;
}
inline void Heartbeat::set_max_parallel_jobs(int32_t value) {
  _internal_set_max_parallel_jobs(value);
  // @@protoc_insertion_point(field_set:coretex.agent.v1.Heartbeat.max_parallel_jobs)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace agent
}  // namespace coretex

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_coretex_2fagent_2fv1_2fheartbeat_2eproto
