// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coretex/agent/v1/heartbeat.proto

#include "coretex/agent/v1/heartbeat.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace coretex {
namespace agent {
namespace v1 {
PROTOBUF_CONSTEXPR Heartbeat::Heartbeat(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.capabilities_)*/{}
  , /*decltype(_impl_.worker_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.region_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.type_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.pool_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.cpu_load_)*/0
  , /*decltype(_impl_.gpu_utilization_)*/0
  , /*decltype(_impl_.active_jobs_)*/0
  , /*decltype(_impl_.max_parallel_jobs_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct HeartbeatDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HeartbeatDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~HeartbeatDefaultTypeInternal() {}
  union {
    Heartbeat _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HeartbeatDefaultTypeInternal _Heartbeat_default_instance_;
}  // namespace v1
}  // namespace agent
}  // namespace coretex
static ::_pb::Metadata file_level_metadata_coretex_2fagent_2fv1_2fheartbeat_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_coretex_2fagent_2fv1_2fheartbeat_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_coretex_2fagent_2fv1_2fheartbeat_2eproto = nullptr;

const uint32_t TableStruct_coretex_2fagent_2fv1_2fheartbeat_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::coretex::agent::v1::Heartbeat, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::coretex::agent::v1::Heartbeat, _impl_.worker_id_),
  PROTOBUF_FIELD_OFFSET(::coretex::agent::v1::Heartbeat, _impl_.region_),
  PROTOBUF_FIELD_OFFSET(::coretex::agent::v1::Heartbeat, _impl_.type_),
  PROTOBUF_FIELD_OFFSET(::coretex::agent::v1::Heartbeat, _impl_.cpu_load_),
  PROTOBUF_FIELD_OFFSET(::coretex::agent::v1::Heartbeat, _impl_.gpu_utilization_),
  PROTOBUF_FIELD_OFFSET(::coretex::agent::v1::Heartbeat, _impl_.active_jobs_),
  PROTOBUF_FIELD_OFFSET(::coretex::agent::v1::Heartbeat, _impl_.capabilities_),
  PROTOBUF_FIELD_OFFSET(::coretex::agent::v1::Heartbeat, _impl_.pool_),
  PROTOBUF_FIELD_OFFSET(::coretex::agent::v1::Heartbeat, _impl_.max_parallel_jobs_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::coretex::agent::v1::Heartbeat)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::coretex::agent::v1::_Heartbeat_default_instance_._instance,
};

const char descriptor_table_protodef_coretex_2fagent_2fv1_2fheartbeat_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\037coretex/agent/v1/heartbeat.proto\022\017corte"
  "x.agent.v1\"\273\001\n\tHeartbeat\022\021\n\tworker_id\030\001 "
  "\001(\t\022\016\n\006region\030\002 \001(\t\022\014\n\004type\030\003 \001(\t\022\020\n\010cpu"
  "_load\030\004 \001(\002\022\027\n\017gpu_utilization\030\005 \001(\002\022\023\n\013"
  "active_jobs\030\006 \001(\005\022\024\n\014capabilities\030\007 \003(\t\022"
  "\014\n\004pool\030\013 \001(\t\022\031\n\021max_parallel_jobs\030\014 \001(\005"
  "B\177\n\026ai.coretex.cap.agent.v1P\001Z+github.com"
  "/coretexos/cap/go/coretex/agent/v1\252\002\017Cort"
  "ex.Agent.V1\312\002\017coretex\\Agent\\V1\352\002\021coretex::"
  "Agent::V1b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_coretex_2fagent_2fv1_2fheartbeat_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_coretex_2fagent_2fv1_2fheartbeat_2eproto = {
    false, false, 377, descriptor_table_protodef_coretex_2fagent_2fv1_2fheartbeat_2eproto,
    "coretex/agent/v1/heartbeat.proto",
    &descriptor_table_coretex_2fagent_2fv1_2fheartbeat_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_coretex_2fagent_2fv1_2fheartbeat_2eproto::offsets,
    file_level_metadata_coretex_2fagent_2fv1_2fheartbeat_2eproto, file_level_enum_descriptors_coretex_2fagent_2fv1_2fheartbeat_2eproto,
    file_level_service_descriptors_coretex_2fagent_2fv1_2fheartbeat_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_coretex_2fagent_2fv1_2fheartbeat_2eproto_getter() {
  return &descriptor_table_coretex_2fagent_2fv1_2fheartbeat_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_coretex_2fagent_2fv1_2fheartbeat_2eproto(&descriptor_table_coretex_2fagent_2fv1_2fheartbeat_2eproto);
namespace coretex {
namespace agent {
namespace v1 {

// ===================================================================

class Heartbeat::_Internal {
 public:
};

Heartbeat::Heartbeat(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:coretex.agent.v1.Heartbeat)
}
Heartbeat::Heartbeat(const Heartbeat& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Heartbeat* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.capabilities_){from._impl_.capabilities_}
    , decltype(_impl_.worker_id_){}
    , decltype(_impl_.region_){}
    , decltype(_impl_.type_){}
    , decltype(_impl_.pool_){}
    , decltype(_impl_.cpu_load_){}
    , decltype(_impl_.gpu_utilization_){}
    , decltype(_impl_.active_jobs_){}
    , decltype(_impl_.max_parallel_jobs_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.worker_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.worker_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_worker_id().empty()) {
    _this->_impl_.worker_id_.Set(from._internal_worker_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.region_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.region_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_region().empty()) {
    _this->_impl_.region_.Set(from._internal_region(), 
      _this->GetArenaForAllocation());
  }
  _impl_.type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_type().empty()) {
    _this->_impl_.type_.Set(from._internal_type(), 
      _this->GetArenaForAllocation());
  }
  _impl_.pool_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.pool_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_pool().empty()) {
    _this->_impl_.pool_.Set(from._internal_pool(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.cpu_load_, &from._impl_.cpu_load_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.max_parallel_jobs_) -
    reinterpret_cast<char*>(&_impl_.cpu_load_)) + sizeof(_impl_.max_parallel_jobs_));
  // @@protoc_insertion_point(copy_constructor:coretex.agent.v1.Heartbeat)
}

inline void Heartbeat::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.capabilities_){arena}
    , decltype(_impl_.worker_id_){}
    , decltype(_impl_.region_){}
    , decltype(_impl_.type_){}
    , decltype(_impl_.pool_){}
    , decltype(_impl_.cpu_load_){0}
    , decltype(_impl_.gpu_utilization_){0}
    , decltype(_impl_.active_jobs_){0}
    , decltype(_impl_.max_parallel_jobs_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.worker_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.worker_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.region_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.region_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.pool_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.pool_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Heartbeat::~Heartbeat() {
  // @@protoc_insertion_point(destructor:coretex.agent.v1.Heartbeat)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Heartbeat::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.capabilities_.~RepeatedPtrField();
  _impl_.worker_id_.Destroy();
  _impl_.region_.Destroy();
  _impl_.type_.Destroy();
  _impl_.pool_.Destroy();
}

void Heartbeat::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Heartbeat::Clear() {
// @@protoc_insertion_point(message_clear_start:coretex.agent.v1.Heartbeat)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.capabilities_.Clear();
  _impl_.worker_id_.ClearToEmpty();
  _impl_.region_.ClearToEmpty();
  _impl_.type_.ClearToEmpty();
  _impl_.pool_.ClearToEmpty();
  ::memset(&_impl_.cpu_load_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.max_parallel_jobs_) -
      reinterpret_cast<char*>(&_impl_.cpu_load_)) + sizeof(_impl_.max_parallel_jobs_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Heartbeat::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string worker_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_worker_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "coretex.agent.v1.Heartbeat.worker_id"));
        } else
          goto handle_unusual;
        continue;
      // string region = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_region();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "coretex.agent.v1.Heartbeat.region"));
        } else
          goto handle_unusual;
        continue;
      // string type = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_type();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "coretex.agent.v1.Heartbeat.type"));
        } else
          goto handle_unusual;
        continue;
      // float cpu_load = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 37)) {
          _impl_.cpu_load_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float gpu_utilization = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 45)) {
          _impl_.gpu_utilization_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // int32 active_jobs = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.active_jobs_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated string capabilities = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_capabilities();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "coretex.agent.v1.Heartbeat.capabilities"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<58>(ptr));
        } else
          goto handle_unusual;
        continue;
      // string pool = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 90)) {
          auto str = _internal_mutable_pool();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "coretex.agent.v1.Heartbeat.pool"));
        } else
          goto handle_unusual;
        continue;
      // int32 max_parallel_jobs = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 96)) {
          _impl_.max_parallel_jobs_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Heartbeat::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:coretex.agent.v1.Heartbeat)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string worker_id = 1;
  if (!this->_internal_worker_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_worker_id().data(), static_cast<int>(this->_internal_worker_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "coretex.agent.v1.Heartbeat.worker_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_worker_id(), target);
  }

  // string region = 2;
  if (!this->_internal_region().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_region().data(), static_cast<int>(this->_internal_region().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "coretex.agent.v1.Heartbeat.region");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_region(), target);
  }

  // string type = 3;
  if (!this->_internal_type().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_type().data(), static_cast<int>(this->_internal_type().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "coretex.agent.v1.Heartbeat.type");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_type(), target);
  }

  // float cpu_load = 4;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_cpu_load = this->_internal_cpu_load();
  uint32_t raw_cpu_load;
  memcpy(&raw_cpu_load, &tmp_cpu_load, sizeof(tmp_cpu_load));
  if (raw_cpu_load != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(4, this->_internal_cpu_load(), target);
  }

  // float gpu_utilization = 5;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_gpu_utilization = this->_internal_gpu_utilization();
  uint32_t raw_gpu_utilization;
  memcpy(&raw_gpu_utilization, &tmp_gpu_utilization, sizeof(tmp_gpu_utilization));
  if (raw_gpu_utilization != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(5, this->_internal_gpu_utilization(), target);
  }

  // int32 active_jobs = 6;
  if (this->_internal_active_jobs() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(6, this->_internal_active_jobs(), target);
  }

  // repeated string capabilities = 7;
  for (int i = 0, n = this->_internal_capabilities_size(); i < n; i++) {
    const auto& s = this->_internal_capabilities(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "coretex.agent.v1.Heartbeat.capabilities");
    target = stream->WriteString(7, s, target);
  }

  // string pool = 11;
  if (!this->_internal_pool().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_pool().data(), static_cast<int>(this->_internal_pool().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "coretex.agent.v1.Heartbeat.pool");
    target = stream->WriteStringMaybeAliased(
        11, this->_internal_pool(), target);
  }

  // int32 max_parallel_jobs = 12;
  if (this->_internal_max_parallel_jobs() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(12, this->_internal_max_parallel_jobs(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:coretex.agent.v1.Heartbeat)
  return target;
}

size_t Heartbeat::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:coretex.agent.v1.Heartbeat)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string capabilities = 7;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.capabilities_.size());
  for (int i = 0, n = _impl_.capabilities_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.capabilities_.Get(i));
  }

  // string worker_id = 1;
  if (!this->_internal_worker_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_worker_id());
  }

  // string region = 2;
  if (!this->_internal_region().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_region());
  }

  // string type = 3;
  if (!this->_internal_type().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_type());
  }

  // string pool = 11;
  if (!this->_internal_pool().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_pool());
  }

  // float cpu_load = 4;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_cpu_load = this->_internal_cpu_load();
  uint32_t raw_cpu_load;
  memcpy(&raw_cpu_load, &tmp_cpu_load, sizeof(tmp_cpu_load));
  if (raw_cpu_load != 0) {
    total_size += 1 + 4;
  }

  // float gpu_utilization = 5;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_gpu_utilization = this->_internal_gpu_utilization();
  uint32_t raw_gpu_utilization;
  memcpy(&raw_gpu_utilization, &tmp_gpu_utilization, sizeof(tmp_gpu_utilization));
  if (raw_gpu_utilization != 0) {
    total_size += 1 + 4;
  }

  // int32 active_jobs = 6;
  if (this->_internal_active_jobs() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_active_jobs());
  }

  // int32 max_parallel_jobs = 12;
  if (this->_internal_max_parallel_jobs() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_max_parallel_jobs());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Heartbeat::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Heartbeat::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Heartbeat::GetClassData() const { return &_class_data_; }


void Heartbeat::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Heartbeat*>(&to_msg);
  auto& from = static_cast<const Heartbeat&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:coretex.agent.v1.Heartbeat)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.capabilities_.MergeFrom(from._impl_.capabilities_);
  if (!from._internal_worker_id().empty()) {
    _this->_internal_set_worker_id(from._internal_worker_id());
  }
  if (!from._internal_region().empty()) {
    _this->_internal_set_region(from._internal_region());
  }
  if (!from._internal_type().empty()) {
    _this->_internal_set_type(from._internal_type());
  }
  if (!from._internal_pool().empty()) {
    _this->_internal_set_pool(from._internal_pool());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_cpu_load = from._internal_cpu_load();
  uint32_t raw_cpu_load;
  memcpy(&raw_cpu_load, &tmp_cpu_load, sizeof(tmp_cpu_load));
  if (raw_cpu_load != 0) {
    _this->_internal_set_cpu_load(from._internal_cpu_load());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_gpu_utilization = from._internal_gpu_utilization();
  uint32_t raw_gpu_utilization;
  memcpy(&raw_gpu_utilization, &tmp_gpu_utilization, sizeof(tmp_gpu_utilization));
  if (raw_gpu_utilization != 0) {
    _this->_internal_set_gpu_utilization(from._internal_gpu_utilization());
  }
  if (from._internal_active_jobs() != 0) {
    _this->_internal_set_active_jobs(from._internal_active_jobs());
  }
  if (from._internal_max_parallel_jobs() != 0) {
    _this->_internal_set_max_parallel_jobs(from._internal_max_parallel_jobs());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Heartbeat::CopyFrom(const Heartbeat& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:coretex.agent.v1.Heartbeat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Heartbeat::IsInitialized() const {
  return true;
}

void Heartbeat::InternalSwap(Heartbeat* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.capabilities_.InternalSwap(&other->_impl_.capabilities_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.worker_id_, lhs_arena,
      &other->_impl_.worker_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.region_, lhs_arena,
      &other->_impl_.region_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.type_, lhs_arena,
      &other->_impl_.type_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.pool_, lhs_arena,
      &other->_impl_.pool_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Heartbeat, _impl_.max_parallel_jobs_)
      + sizeof(Heartbeat::_impl_.max_parallel_jobs_)
      - PROTOBUF_FIELD_OFFSET(Heartbeat, _impl_.cpu_load_)>(
          reinterpret_cast<char*>(&_impl_.cpu_load_),
          reinterpret_cast<char*>(&other->_impl_.cpu_load_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Heartbeat::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_coretex_2fagent_2fv1_2fheartbeat_2eproto_getter, &descriptor_table_coretex_2fagent_2fv1_2fheartbeat_2eproto_once,
      file_level_metadata_coretex_2fagent_2fv1_2fheartbeat_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace agent
}  // namespace coretex
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::coretex::agent::v1::Heartbeat*
Arena::CreateMaybeMessage< ::coretex::agent::v1::Heartbeat >(Arena* arena) {
  return Arena::CreateMessageInternal< ::coretex::agent::v1::Heartbeat >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
