// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coretex/agent/v1/safety.proto

#include "coretex/agent/v1/safety.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace coretex {
namespace agent {
namespace v1 {
PROTOBUF_CONSTEXPR PolicyCheckRequest_LabelsEntry_DoNotUse::PolicyCheckRequest_LabelsEntry_DoNotUse(
    ::_pbi::ConstantInitialized) {}
struct PolicyCheckRequest_LabelsEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PolicyCheckRequest_LabelsEntry_DoNotUseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PolicyCheckRequest_LabelsEntry_DoNotUseDefaultTypeInternal() {}
  union {
    PolicyCheckRequest_LabelsEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PolicyCheckRequest_LabelsEntry_DoNotUseDefaultTypeInternal _PolicyCheckRequest_LabelsEntry_DoNotUse_default_instance_;
PROTOBUF_CONSTEXPR PolicyCheckRequest::PolicyCheckRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.labels_)*/{::_pbi::ConstantInitialized()}
  , /*decltype(_impl_.job_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.topic_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.tenant_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.principal_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.memory_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.budget_)*/nullptr
  , /*decltype(_impl_.estimated_cost_)*/0
  , /*decltype(_impl_.priority_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PolicyCheckRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PolicyCheckRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PolicyCheckRequestDefaultTypeInternal() {}
  union {
    PolicyCheckRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PolicyCheckRequestDefaultTypeInternal _PolicyCheckRequest_default_instance_;
PROTOBUF_CONSTEXPR PolicyCheckResponse::PolicyCheckResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.reason_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.redacted_context_ptr_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.decision_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PolicyCheckResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PolicyCheckResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PolicyCheckResponseDefaultTypeInternal() {}
  union {
    PolicyCheckResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PolicyCheckResponseDefaultTypeInternal _PolicyCheckResponse_default_instance_;
}  // namespace v1
}  // namespace agent
}  // namespace coretex
static ::_pb::Metadata file_level_metadata_coretex_2fagent_2fv1_2fsafety_2eproto[3];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_coretex_2fagent_2fv1_2fsafety_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_coretex_2fagent_2fv1_2fsafety_2eproto = nullptr;

const uint32_t TableStruct_coretex_2fagent_2fv1_2fsafety_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::coretex::agent::v1::PolicyCheckRequest_LabelsEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::coretex::agent::v1::PolicyCheckRequest_LabelsEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::coretex::agent::v1::PolicyCheckRequest_LabelsEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::coretex::agent::v1::PolicyCheckRequest_LabelsEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::coretex::agent::v1::PolicyCheckRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::coretex::agent::v1::PolicyCheckRequest, _impl_.job_id_),
  PROTOBUF_FIELD_OFFSET(::coretex::agent::v1::PolicyCheckRequest, _impl_.topic_),
  PROTOBUF_FIELD_OFFSET(::coretex::agent::v1::PolicyCheckRequest, _impl_.tenant_),
  PROTOBUF_FIELD_OFFSET(::coretex::agent::v1::PolicyCheckRequest, _impl_.priority_),
  PROTOBUF_FIELD_OFFSET(::coretex::agent::v1::PolicyCheckRequest, _impl_.estimated_cost_),
  PROTOBUF_FIELD_OFFSET(::coretex::agent::v1::PolicyCheckRequest, _impl_.budget_),
  PROTOBUF_FIELD_OFFSET(::coretex::agent::v1::PolicyCheckRequest, _impl_.principal_id_),
  PROTOBUF_FIELD_OFFSET(::coretex::agent::v1::PolicyCheckRequest, _impl_.labels_),
  PROTOBUF_FIELD_OFFSET(::coretex::agent::v1::PolicyCheckRequest, _impl_.memory_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::coretex::agent::v1::PolicyCheckResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::coretex::agent::v1::PolicyCheckResponse, _impl_.decision_),
  PROTOBUF_FIELD_OFFSET(::coretex::agent::v1::PolicyCheckResponse, _impl_.reason_),
  PROTOBUF_FIELD_OFFSET(::coretex::agent::v1::PolicyCheckResponse, _impl_.redacted_context_ptr_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, -1, sizeof(::coretex::agent::v1::PolicyCheckRequest_LabelsEntry_DoNotUse)},
  { 10, -1, -1, sizeof(::coretex::agent::v1::PolicyCheckRequest)},
  { 25, -1, -1, sizeof(::coretex::agent::v1::PolicyCheckResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::coretex::agent::v1::_PolicyCheckRequest_LabelsEntry_DoNotUse_default_instance_._instance,
  &::coretex::agent::v1::_PolicyCheckRequest_default_instance_._instance,
  &::coretex::agent::v1::_PolicyCheckResponse_default_instance_._instance,
};

const char descriptor_table_protodef_coretex_2fagent_2fv1_2fsafety_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\034coretex/agent/v1/safety.proto\022\017coretex.a"
  "gent.v1\032\031coretex/agent/v1/job.proto\"\315\002\n\022P"
  "olicyCheckRequest\022\016\n\006job_id\030\001 \001(\t\022\r\n\005top"
  "ic\030\002 \001(\t\022\016\n\006tenant\030\003 \001(\t\022.\n\010priority\030\004 \001"
  "(\0162\034.coretex.agent.v1.JobPriority\022\026\n\016esti"
  "mated_cost\030\005 \001(\001\022\'\n\006budget\030\006 \001(\0132\027.corte"
  "x.agent.v1.Budget\022\024\n\014principal_id\030\007 \001(\t\022"
  "\?\n\006labels\030\010 \003(\0132/.coretex.agent.v1.Policy"
  "CheckRequest.LabelsEntry\022\021\n\tmemory_id\030\t "
  "\001(\t\032-\n\013LabelsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value"
  "\030\002 \001(\t:\0028\001\"t\n\023PolicyCheckResponse\022/\n\010dec"
  "ision\030\001 \001(\0162\035.coretex.agent.v1.DecisionTy"
  "pe\022\016\n\006reason\030\002 \001(\t\022\034\n\024redacted_context_p"
  "tr\030\003 \001(\t*\233\001\n\014DecisionType\022\035\n\031DECISION_TY"
  "PE_UNSPECIFIED\020\000\022\027\n\023DECISION_TYPE_ALLOW\020"
  "\001\022\026\n\022DECISION_TYPE_DENY\020\002\022\037\n\033DECISION_TY"
  "PE_REQUIRE_HUMAN\020\003\022\032\n\026DECISION_TYPE_THRO"
  "TTLE\020\0042b\n\014SafetyKernel\022R\n\005Check\022#.coretex"
  ".agent.v1.PolicyCheckRequest\032$.coretex.ag"
  "ent.v1.PolicyCheckResponseB\177\n\026ai.coretex."
  "cap.agent.v1P\001Z+github.com/coretexos/cap"
  "/go/coretex/agent/v1\252\002\017coretex.Agent.V1\312\002\017"
  "coretex\\Agent\\V1\352\002\021coretex::Agent::V1b\006pro"
  "to3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_coretex_2fagent_2fv1_2fsafety_2eproto_deps[1] = {
  &::descriptor_table_coretex_2fagent_2fv1_2fjob_2eproto,
};
static ::_pbi::once_flag descriptor_table_coretex_2fagent_2fv1_2fsafety_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_coretex_2fagent_2fv1_2fsafety_2eproto = {
    false, false, 923, descriptor_table_protodef_coretex_2fagent_2fv1_2fsafety_2eproto,
    "coretex/agent/v1/safety.proto",
    &descriptor_table_coretex_2fagent_2fv1_2fsafety_2eproto_once, descriptor_table_coretex_2fagent_2fv1_2fsafety_2eproto_deps, 1, 3,
    schemas, file_default_instances, TableStruct_coretex_2fagent_2fv1_2fsafety_2eproto::offsets,
    file_level_metadata_coretex_2fagent_2fv1_2fsafety_2eproto, file_level_enum_descriptors_coretex_2fagent_2fv1_2fsafety_2eproto,
    file_level_service_descriptors_coretex_2fagent_2fv1_2fsafety_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_coretex_2fagent_2fv1_2fsafety_2eproto_getter() {
  return &descriptor_table_coretex_2fagent_2fv1_2fsafety_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_coretex_2fagent_2fv1_2fsafety_2eproto(&descriptor_table_coretex_2fagent_2fv1_2fsafety_2eproto);
namespace coretex {
namespace agent {
namespace v1 {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DecisionType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_coretex_2fagent_2fv1_2fsafety_2eproto);
  return file_level_enum_descriptors_coretex_2fagent_2fv1_2fsafety_2eproto[0];
}
bool DecisionType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}


// ===================================================================

PolicyCheckRequest_LabelsEntry_DoNotUse::PolicyCheckRequest_LabelsEntry_DoNotUse() {}
PolicyCheckRequest_LabelsEntry_DoNotUse::PolicyCheckRequest_LabelsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void PolicyCheckRequest_LabelsEntry_DoNotUse::MergeFrom(const PolicyCheckRequest_LabelsEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata PolicyCheckRequest_LabelsEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_coretex_2fagent_2fv1_2fsafety_2eproto_getter, &descriptor_table_coretex_2fagent_2fv1_2fsafety_2eproto_once,
      file_level_metadata_coretex_2fagent_2fv1_2fsafety_2eproto[0]);
}

// ===================================================================

class PolicyCheckRequest::_Internal {
 public:
  static const ::coretex::agent::v1::Budget& budget(const PolicyCheckRequest* msg);
};

const ::coretex::agent::v1::Budget&
PolicyCheckRequest::_Internal::budget(const PolicyCheckRequest* msg) {
  return *msg->_impl_.budget_;
}
void PolicyCheckRequest::clear_budget() {
  if (GetArenaForAllocation() == nullptr && _impl_.budget_ != nullptr) {
    delete _impl_.budget_;
  }
  _impl_.budget_ = nullptr;
}
PolicyCheckRequest::PolicyCheckRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  if (arena != nullptr && !is_message_owned) {
    arena->OwnCustomDestructor(this, &PolicyCheckRequest::ArenaDtor);
  }
  // @@protoc_insertion_point(arena_constructor:coretex.agent.v1.PolicyCheckRequest)
}
PolicyCheckRequest::PolicyCheckRequest(const PolicyCheckRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PolicyCheckRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      /*decltype(_impl_.labels_)*/{}
    , decltype(_impl_.job_id_){}
    , decltype(_impl_.topic_){}
    , decltype(_impl_.tenant_){}
    , decltype(_impl_.principal_id_){}
    , decltype(_impl_.memory_id_){}
    , decltype(_impl_.budget_){nullptr}
    , decltype(_impl_.estimated_cost_){}
    , decltype(_impl_.priority_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.labels_.MergeFrom(from._impl_.labels_);
  _impl_.job_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.job_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_job_id().empty()) {
    _this->_impl_.job_id_.Set(from._internal_job_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.topic_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.topic_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_topic().empty()) {
    _this->_impl_.topic_.Set(from._internal_topic(), 
      _this->GetArenaForAllocation());
  }
  _impl_.tenant_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.tenant_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_tenant().empty()) {
    _this->_impl_.tenant_.Set(from._internal_tenant(), 
      _this->GetArenaForAllocation());
  }
  _impl_.principal_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.principal_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_principal_id().empty()) {
    _this->_impl_.principal_id_.Set(from._internal_principal_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.memory_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.memory_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_memory_id().empty()) {
    _this->_impl_.memory_id_.Set(from._internal_memory_id(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_budget()) {
    _this->_impl_.budget_ = new ::coretex::agent::v1::Budget(*from._impl_.budget_);
  }
  ::memcpy(&_impl_.estimated_cost_, &from._impl_.estimated_cost_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.priority_) -
    reinterpret_cast<char*>(&_impl_.estimated_cost_)) + sizeof(_impl_.priority_));
  // @@protoc_insertion_point(copy_constructor:coretex.agent.v1.PolicyCheckRequest)
}

inline void PolicyCheckRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      /*decltype(_impl_.labels_)*/{::_pbi::ArenaInitialized(), arena}
    , decltype(_impl_.job_id_){}
    , decltype(_impl_.topic_){}
    , decltype(_impl_.tenant_){}
    , decltype(_impl_.principal_id_){}
    , decltype(_impl_.memory_id_){}
    , decltype(_impl_.budget_){nullptr}
    , decltype(_impl_.estimated_cost_){0}
    , decltype(_impl_.priority_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.job_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.job_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.topic_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.topic_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.tenant_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.tenant_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.principal_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.principal_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.memory_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.memory_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PolicyCheckRequest::~PolicyCheckRequest() {
  // @@protoc_insertion_point(destructor:coretex.agent.v1.PolicyCheckRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    ArenaDtor(this);
    return;
  }
  SharedDtor();
}

inline void PolicyCheckRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.labels_.Destruct();
  _impl_.labels_.~MapField();
  _impl_.job_id_.Destroy();
  _impl_.topic_.Destroy();
  _impl_.tenant_.Destroy();
  _impl_.principal_id_.Destroy();
  _impl_.memory_id_.Destroy();
  if (this != internal_default_instance()) delete _impl_.budget_;
}

void PolicyCheckRequest::ArenaDtor(void* object) {
  PolicyCheckRequest* _this = reinterpret_cast< PolicyCheckRequest* >(object);
  _this->_impl_.labels_.Destruct();
}
void PolicyCheckRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PolicyCheckRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:coretex.agent.v1.PolicyCheckRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.labels_.Clear();
  _impl_.job_id_.ClearToEmpty();
  _impl_.topic_.ClearToEmpty();
  _impl_.tenant_.ClearToEmpty();
  _impl_.principal_id_.ClearToEmpty();
  _impl_.memory_id_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.budget_ != nullptr) {
    delete _impl_.budget_;
  }
  _impl_.budget_ = nullptr;
  ::memset(&_impl_.estimated_cost_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.priority_) -
      reinterpret_cast<char*>(&_impl_.estimated_cost_)) + sizeof(_impl_.priority_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PolicyCheckRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string job_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_job_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "coretex.agent.v1.PolicyCheckRequest.job_id"));
        } else
          goto handle_unusual;
        continue;
      // string topic = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_topic();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "coretex.agent.v1.PolicyCheckRequest.topic"));
        } else
          goto handle_unusual;
        continue;
      // string tenant = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_tenant();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "coretex.agent.v1.PolicyCheckRequest.tenant"));
        } else
          goto handle_unusual;
        continue;
      // .coretex.agent.v1.JobPriority priority = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_priority(static_cast<::coretex::agent::v1::JobPriority>(val));
        } else
          goto handle_unusual;
        continue;
      // double estimated_cost = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 41)) {
          _impl_.estimated_cost_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // .coretex.agent.v1.Budget budget = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_budget(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string principal_id = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          auto str = _internal_mutable_principal_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "coretex.agent.v1.PolicyCheckRequest.principal_id"));
        } else
          goto handle_unusual;
        continue;
      // map<string, string> labels = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&_impl_.labels_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<66>(ptr));
        } else
          goto handle_unusual;
        continue;
      // string memory_id = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 74)) {
          auto str = _internal_mutable_memory_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "coretex.agent.v1.PolicyCheckRequest.memory_id"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PolicyCheckRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:coretex.agent.v1.PolicyCheckRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string job_id = 1;
  if (!this->_internal_job_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_job_id().data(), static_cast<int>(this->_internal_job_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "coretex.agent.v1.PolicyCheckRequest.job_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_job_id(), target);
  }

  // string topic = 2;
  if (!this->_internal_topic().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_topic().data(), static_cast<int>(this->_internal_topic().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "coretex.agent.v1.PolicyCheckRequest.topic");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_topic(), target);
  }

  // string tenant = 3;
  if (!this->_internal_tenant().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_tenant().data(), static_cast<int>(this->_internal_tenant().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "coretex.agent.v1.PolicyCheckRequest.tenant");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_tenant(), target);
  }

  // .coretex.agent.v1.JobPriority priority = 4;
  if (this->_internal_priority() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      4, this->_internal_priority(), target);
  }

  // double estimated_cost = 5;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_estimated_cost = this->_internal_estimated_cost();
  uint64_t raw_estimated_cost;
  memcpy(&raw_estimated_cost, &tmp_estimated_cost, sizeof(tmp_estimated_cost));
  if (raw_estimated_cost != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(5, this->_internal_estimated_cost(), target);
  }

  // .coretex.agent.v1.Budget budget = 6;
  if (this->_internal_has_budget()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, _Internal::budget(this),
        _Internal::budget(this).GetCachedSize(), target, stream);
  }

  // string principal_id = 7;
  if (!this->_internal_principal_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_principal_id().data(), static_cast<int>(this->_internal_principal_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "coretex.agent.v1.PolicyCheckRequest.principal_id");
    target = stream->WriteStringMaybeAliased(
        7, this->_internal_principal_id(), target);
  }

  // map<string, string> labels = 8;
  if (!this->_internal_labels().empty()) {
    using MapType = ::_pb::Map<std::string, std::string>;
    using WireHelper = PolicyCheckRequest_LabelsEntry_DoNotUse::Funcs;
    const auto& map_field = this->_internal_labels();
    auto check_utf8 = [](const MapType::value_type& entry) {
      (void)entry;
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        entry.first.data(), static_cast<int>(entry.first.length()),
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
        "coretex.agent.v1.PolicyCheckRequest.LabelsEntry.key");
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        entry.second.data(), static_cast<int>(entry.second.length()),
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
        "coretex.agent.v1.PolicyCheckRequest.LabelsEntry.value");
    };

    if (stream->IsSerializationDeterministic() && map_field.size() > 1) {
      for (const auto& entry : ::_pbi::MapSorterPtr<MapType>(map_field)) {
        target = WireHelper::InternalSerialize(8, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    } else {
      for (const auto& entry : map_field) {
        target = WireHelper::InternalSerialize(8, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    }
  }

  // string memory_id = 9;
  if (!this->_internal_memory_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_memory_id().data(), static_cast<int>(this->_internal_memory_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "coretex.agent.v1.PolicyCheckRequest.memory_id");
    target = stream->WriteStringMaybeAliased(
        9, this->_internal_memory_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:coretex.agent.v1.PolicyCheckRequest)
  return target;
}

size_t PolicyCheckRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:coretex.agent.v1.PolicyCheckRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<string, string> labels = 8;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_labels_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
      it = this->_internal_labels().begin();
      it != this->_internal_labels().end(); ++it) {
    total_size += PolicyCheckRequest_LabelsEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // string job_id = 1;
  if (!this->_internal_job_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_job_id());
  }

  // string topic = 2;
  if (!this->_internal_topic().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_topic());
  }

  // string tenant = 3;
  if (!this->_internal_tenant().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_tenant());
  }

  // string principal_id = 7;
  if (!this->_internal_principal_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_principal_id());
  }

  // string memory_id = 9;
  if (!this->_internal_memory_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_memory_id());
  }

  // .coretex.agent.v1.Budget budget = 6;
  if (this->_internal_has_budget()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.budget_);
  }

  // double estimated_cost = 5;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_estimated_cost = this->_internal_estimated_cost();
  uint64_t raw_estimated_cost;
  memcpy(&raw_estimated_cost, &tmp_estimated_cost, sizeof(tmp_estimated_cost));
  if (raw_estimated_cost != 0) {
    total_size += 1 + 8;
  }

  // .coretex.agent.v1.JobPriority priority = 4;
  if (this->_internal_priority() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_priority());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PolicyCheckRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PolicyCheckRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PolicyCheckRequest::GetClassData() const { return &_class_data_; }


void PolicyCheckRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PolicyCheckRequest*>(&to_msg);
  auto& from = static_cast<const PolicyCheckRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:coretex.agent.v1.PolicyCheckRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.labels_.MergeFrom(from._impl_.labels_);
  if (!from._internal_job_id().empty()) {
    _this->_internal_set_job_id(from._internal_job_id());
  }
  if (!from._internal_topic().empty()) {
    _this->_internal_set_topic(from._internal_topic());
  }
  if (!from._internal_tenant().empty()) {
    _this->_internal_set_tenant(from._internal_tenant());
  }
  if (!from._internal_principal_id().empty()) {
    _this->_internal_set_principal_id(from._internal_principal_id());
  }
  if (!from._internal_memory_id().empty()) {
    _this->_internal_set_memory_id(from._internal_memory_id());
  }
  if (from._internal_has_budget()) {
    _this->_internal_mutable_budget()->::coretex::agent::v1::Budget::MergeFrom(
        from._internal_budget());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_estimated_cost = from._internal_estimated_cost();
  uint64_t raw_estimated_cost;
  memcpy(&raw_estimated_cost, &tmp_estimated_cost, sizeof(tmp_estimated_cost));
  if (raw_estimated_cost != 0) {
    _this->_internal_set_estimated_cost(from._internal_estimated_cost());
  }
  if (from._internal_priority() != 0) {
    _this->_internal_set_priority(from._internal_priority());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PolicyCheckRequest::CopyFrom(const PolicyCheckRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:coretex.agent.v1.PolicyCheckRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PolicyCheckRequest::IsInitialized() const {
  return true;
}

void PolicyCheckRequest::InternalSwap(PolicyCheckRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.labels_.InternalSwap(&other->_impl_.labels_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.job_id_, lhs_arena,
      &other->_impl_.job_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.topic_, lhs_arena,
      &other->_impl_.topic_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.tenant_, lhs_arena,
      &other->_impl_.tenant_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.principal_id_, lhs_arena,
      &other->_impl_.principal_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.memory_id_, lhs_arena,
      &other->_impl_.memory_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PolicyCheckRequest, _impl_.priority_)
      + sizeof(PolicyCheckRequest::_impl_.priority_)
      - PROTOBUF_FIELD_OFFSET(PolicyCheckRequest, _impl_.budget_)>(
          reinterpret_cast<char*>(&_impl_.budget_),
          reinterpret_cast<char*>(&other->_impl_.budget_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PolicyCheckRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_coretex_2fagent_2fv1_2fsafety_2eproto_getter, &descriptor_table_coretex_2fagent_2fv1_2fsafety_2eproto_once,
      file_level_metadata_coretex_2fagent_2fv1_2fsafety_2eproto[1]);
}

// ===================================================================

class PolicyCheckResponse::_Internal {
 public:
};

PolicyCheckResponse::PolicyCheckResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:coretex.agent.v1.PolicyCheckResponse)
}
PolicyCheckResponse::PolicyCheckResponse(const PolicyCheckResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PolicyCheckResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.reason_){}
    , decltype(_impl_.redacted_context_ptr_){}
    , decltype(_impl_.decision_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.reason_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.reason_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_reason().empty()) {
    _this->_impl_.reason_.Set(from._internal_reason(), 
      _this->GetArenaForAllocation());
  }
  _impl_.redacted_context_ptr_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.redacted_context_ptr_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_redacted_context_ptr().empty()) {
    _this->_impl_.redacted_context_ptr_.Set(from._internal_redacted_context_ptr(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.decision_ = from._impl_.decision_;
  // @@protoc_insertion_point(copy_constructor:coretex.agent.v1.PolicyCheckResponse)
}

inline void PolicyCheckResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.reason_){}
    , decltype(_impl_.redacted_context_ptr_){}
    , decltype(_impl_.decision_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.reason_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.reason_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.redacted_context_ptr_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.redacted_context_ptr_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

PolicyCheckResponse::~PolicyCheckResponse() {
  // @@protoc_insertion_point(destructor:coretex.agent.v1.PolicyCheckResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PolicyCheckResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.reason_.Destroy();
  _impl_.redacted_context_ptr_.Destroy();
}

void PolicyCheckResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PolicyCheckResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:coretex.agent.v1.PolicyCheckResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.reason_.ClearToEmpty();
  _impl_.redacted_context_ptr_.ClearToEmpty();
  _impl_.decision_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PolicyCheckResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .coretex.agent.v1.DecisionType decision = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_decision(static_cast<::coretex::agent::v1::DecisionType>(val));
        } else
          goto handle_unusual;
        continue;
      // string reason = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_reason();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "coretex.agent.v1.PolicyCheckResponse.reason"));
        } else
          goto handle_unusual;
        continue;
      // string redacted_context_ptr = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_redacted_context_ptr();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "coretex.agent.v1.PolicyCheckResponse.redacted_context_ptr"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PolicyCheckResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:coretex.agent.v1.PolicyCheckResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .coretex.agent.v1.DecisionType decision = 1;
  if (this->_internal_decision() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_decision(), target);
  }

  // string reason = 2;
  if (!this->_internal_reason().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_reason().data(), static_cast<int>(this->_internal_reason().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "coretex.agent.v1.PolicyCheckResponse.reason");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_reason(), target);
  }

  // string redacted_context_ptr = 3;
  if (!this->_internal_redacted_context_ptr().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_redacted_context_ptr().data(), static_cast<int>(this->_internal_redacted_context_ptr().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "coretex.agent.v1.PolicyCheckResponse.redacted_context_ptr");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_redacted_context_ptr(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:coretex.agent.v1.PolicyCheckResponse)
  return target;
}

size_t PolicyCheckResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:coretex.agent.v1.PolicyCheckResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string reason = 2;
  if (!this->_internal_reason().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_reason());
  }

  // string redacted_context_ptr = 3;
  if (!this->_internal_redacted_context_ptr().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_redacted_context_ptr());
  }

  // .coretex.agent.v1.DecisionType decision = 1;
  if (this->_internal_decision() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_decision());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PolicyCheckResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PolicyCheckResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PolicyCheckResponse::GetClassData() const { return &_class_data_; }


void PolicyCheckResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PolicyCheckResponse*>(&to_msg);
  auto& from = static_cast<const PolicyCheckResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:coretex.agent.v1.PolicyCheckResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_reason().empty()) {
    _this->_internal_set_reason(from._internal_reason());
  }
  if (!from._internal_redacted_context_ptr().empty()) {
    _this->_internal_set_redacted_context_ptr(from._internal_redacted_context_ptr());
  }
  if (from._internal_decision() != 0) {
    _this->_internal_set_decision(from._internal_decision());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PolicyCheckResponse::CopyFrom(const PolicyCheckResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:coretex.agent.v1.PolicyCheckResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PolicyCheckResponse::IsInitialized() const {
  return true;
}

void PolicyCheckResponse::InternalSwap(PolicyCheckResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.reason_, lhs_arena,
      &other->_impl_.reason_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.redacted_context_ptr_, lhs_arena,
      &other->_impl_.redacted_context_ptr_, rhs_arena
  );
  swap(_impl_.decision_, other->_impl_.decision_);
}

::PROTOBUF_NAMESPACE_ID::Metadata PolicyCheckResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_coretex_2fagent_2fv1_2fsafety_2eproto_getter, &descriptor_table_coretex_2fagent_2fv1_2fsafety_2eproto_once,
      file_level_metadata_coretex_2fagent_2fv1_2fsafety_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace agent
}  // namespace coretex
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::coretex::agent::v1::PolicyCheckRequest_LabelsEntry_DoNotUse*
Arena::CreateMaybeMessage< ::coretex::agent::v1::PolicyCheckRequest_LabelsEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::coretex::agent::v1::PolicyCheckRequest_LabelsEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::coretex::agent::v1::PolicyCheckRequest*
Arena::CreateMaybeMessage< ::coretex::agent::v1::PolicyCheckRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::coretex::agent::v1::PolicyCheckRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::coretex::agent::v1::PolicyCheckResponse*
Arena::CreateMaybeMessage< ::coretex::agent::v1::PolicyCheckResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::coretex::agent::v1::PolicyCheckResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
