// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: cordum/agent/v1/buspacket.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BusPacket is the envelope for all traffic on the bus.
type BusPacket struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TraceId         string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`                          // correlates related packets
	SenderId        string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`                       // emitting agent id
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                    // emission time
	ProtocolVersion int32                  `protobuf:"varint,4,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"` // CAP wire version
	// Types that are valid to be assigned to Payload:
	//
	//	*BusPacket_JobRequest
	//	*BusPacket_JobResult
	//	*BusPacket_Heartbeat
	//	*BusPacket_Alert
	//	*BusPacket_JobProgress
	//	*BusPacket_JobCancel
	Payload       isBusPacket_Payload `protobuf_oneof:"payload"`
	Signature     []byte              `protobuf:"bytes,14,opt,name=signature,proto3" json:"signature,omitempty"` // digital signature of the serialized BusPacket
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BusPacket) Reset() {
	*x = BusPacket{}
	mi := &file_cordum_agent_v1_buspacket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusPacket) ProtoMessage() {}

func (x *BusPacket) ProtoReflect() protoreflect.Message {
	mi := &file_cordum_agent_v1_buspacket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusPacket.ProtoReflect.Descriptor instead.
func (*BusPacket) Descriptor() ([]byte, []int) {
	return file_cordum_agent_v1_buspacket_proto_rawDescGZIP(), []int{0}
}

func (x *BusPacket) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *BusPacket) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *BusPacket) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BusPacket) GetProtocolVersion() int32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *BusPacket) GetPayload() isBusPacket_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BusPacket) GetJobRequest() *JobRequest {
	if x != nil {
		if x, ok := x.Payload.(*BusPacket_JobRequest); ok {
			return x.JobRequest
		}
	}
	return nil
}

func (x *BusPacket) GetJobResult() *JobResult {
	if x != nil {
		if x, ok := x.Payload.(*BusPacket_JobResult); ok {
			return x.JobResult
		}
	}
	return nil
}

func (x *BusPacket) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*BusPacket_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *BusPacket) GetAlert() *SystemAlert {
	if x != nil {
		if x, ok := x.Payload.(*BusPacket_Alert); ok {
			return x.Alert
		}
	}
	return nil
}

func (x *BusPacket) GetJobProgress() *JobProgress {
	if x != nil {
		if x, ok := x.Payload.(*BusPacket_JobProgress); ok {
			return x.JobProgress
		}
	}
	return nil
}

func (x *BusPacket) GetJobCancel() *JobCancel {
	if x != nil {
		if x, ok := x.Payload.(*BusPacket_JobCancel); ok {
			return x.JobCancel
		}
	}
	return nil
}

func (x *BusPacket) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type isBusPacket_Payload interface {
	isBusPacket_Payload()
}

type BusPacket_JobRequest struct {
	JobRequest *JobRequest `protobuf:"bytes,10,opt,name=job_request,json=jobRequest,proto3,oneof"`
}

type BusPacket_JobResult struct {
	JobResult *JobResult `protobuf:"bytes,11,opt,name=job_result,json=jobResult,proto3,oneof"`
}

type BusPacket_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,12,opt,name=heartbeat,proto3,oneof"`
}

type BusPacket_Alert struct {
	Alert *SystemAlert `protobuf:"bytes,13,opt,name=alert,proto3,oneof"`
}

type BusPacket_JobProgress struct {
	JobProgress *JobProgress `protobuf:"bytes,15,opt,name=job_progress,json=jobProgress,proto3,oneof"`
}

type BusPacket_JobCancel struct {
	JobCancel *JobCancel `protobuf:"bytes,16,opt,name=job_cancel,json=jobCancel,proto3,oneof"`
}

func (*BusPacket_JobRequest) isBusPacket_Payload() {}

func (*BusPacket_JobResult) isBusPacket_Payload() {}

func (*BusPacket_Heartbeat) isBusPacket_Payload() {}

func (*BusPacket_Alert) isBusPacket_Payload() {}

func (*BusPacket_JobProgress) isBusPacket_Payload() {}

func (*BusPacket_JobCancel) isBusPacket_Payload() {}

var File_cordum_agent_v1_buspacket_proto protoreflect.FileDescriptor

const file_cordum_agent_v1_buspacket_proto_rawDesc = "" +
	"\n" +
	"\x1fcordum/agent/v1/buspacket.proto\x12\x0fcordum.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19cordum/agent/v1/job.proto\x1a\x1fcordum/agent/v1/heartbeat.proto\x1a\x1bcordum/agent/v1/alert.proto\"\xc1\x04\n" +
	"\tBusPacket\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12)\n" +
	"\x10protocol_version\x18\x04 \x01(\x05R\x0fprotocolVersion\x12>\n" +
	"\vjob_request\x18\n" +
	" \x01(\v2\x1b.cordum.agent.v1.JobRequestH\x00R\n" +
	"jobRequest\x12;\n" +
	"\n" +
	"job_result\x18\v \x01(\v2\x1a.cordum.agent.v1.JobResultH\x00R\tjobResult\x12:\n" +
	"\theartbeat\x18\f \x01(\v2\x1a.cordum.agent.v1.HeartbeatH\x00R\theartbeat\x124\n" +
	"\x05alert\x18\r \x01(\v2\x1c.cordum.agent.v1.SystemAlertH\x00R\x05alert\x12A\n" +
	"\fjob_progress\x18\x0f \x01(\v2\x1c.cordum.agent.v1.JobProgressH\x00R\vjobProgress\x12;\n" +
	"\n" +
	"job_cancel\x18\x10 \x01(\v2\x1a.cordum.agent.v1.JobCancelH\x00R\tjobCancel\x12\x1c\n" +
	"\tsignature\x18\x0e \x01(\fR\tsignatureB\t\n" +
	"\apayloadB\x7f\n" +
	"\x16io.cordum.cap.agent.v1P\x01Z+github.com/cordum-io/cap/v2/cordum/agent/v1\xaa\x02\x0fCordum.Agent.V1\xca\x02\x0fcordum\\Agent\\V1\xea\x02\x11Cordum::Agent::V1b\x06proto3"

var (
	file_cordum_agent_v1_buspacket_proto_rawDescOnce sync.Once
	file_cordum_agent_v1_buspacket_proto_rawDescData []byte
)

func file_cordum_agent_v1_buspacket_proto_rawDescGZIP() []byte {
	file_cordum_agent_v1_buspacket_proto_rawDescOnce.Do(func() {
		file_cordum_agent_v1_buspacket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cordum_agent_v1_buspacket_proto_rawDesc), len(file_cordum_agent_v1_buspacket_proto_rawDesc)))
	})
	return file_cordum_agent_v1_buspacket_proto_rawDescData
}

var file_cordum_agent_v1_buspacket_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cordum_agent_v1_buspacket_proto_goTypes = []any{
	(*BusPacket)(nil),             // 0: cordum.agent.v1.BusPacket
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*JobRequest)(nil),            // 2: cordum.agent.v1.JobRequest
	(*JobResult)(nil),             // 3: cordum.agent.v1.JobResult
	(*Heartbeat)(nil),             // 4: cordum.agent.v1.Heartbeat
	(*SystemAlert)(nil),           // 5: cordum.agent.v1.SystemAlert
	(*JobProgress)(nil),           // 6: cordum.agent.v1.JobProgress
	(*JobCancel)(nil),             // 7: cordum.agent.v1.JobCancel
}
var file_cordum_agent_v1_buspacket_proto_depIdxs = []int32{
	1, // 0: cordum.agent.v1.BusPacket.created_at:type_name -> google.protobuf.Timestamp
	2, // 1: cordum.agent.v1.BusPacket.job_request:type_name -> cordum.agent.v1.JobRequest
	3, // 2: cordum.agent.v1.BusPacket.job_result:type_name -> cordum.agent.v1.JobResult
	4, // 3: cordum.agent.v1.BusPacket.heartbeat:type_name -> cordum.agent.v1.Heartbeat
	5, // 4: cordum.agent.v1.BusPacket.alert:type_name -> cordum.agent.v1.SystemAlert
	6, // 5: cordum.agent.v1.BusPacket.job_progress:type_name -> cordum.agent.v1.JobProgress
	7, // 6: cordum.agent.v1.BusPacket.job_cancel:type_name -> cordum.agent.v1.JobCancel
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_cordum_agent_v1_buspacket_proto_init() }
func file_cordum_agent_v1_buspacket_proto_init() {
	if File_cordum_agent_v1_buspacket_proto != nil {
		return
	}
	file_cordum_agent_v1_job_proto_init()
	file_cordum_agent_v1_heartbeat_proto_init()
	file_cordum_agent_v1_alert_proto_init()
	file_cordum_agent_v1_buspacket_proto_msgTypes[0].OneofWrappers = []any{
		(*BusPacket_JobRequest)(nil),
		(*BusPacket_JobResult)(nil),
		(*BusPacket_Heartbeat)(nil),
		(*BusPacket_Alert)(nil),
		(*BusPacket_JobProgress)(nil),
		(*BusPacket_JobCancel)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cordum_agent_v1_buspacket_proto_rawDesc), len(file_cordum_agent_v1_buspacket_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cordum_agent_v1_buspacket_proto_goTypes,
		DependencyIndexes: file_cordum_agent_v1_buspacket_proto_depIdxs,
		MessageInfos:      file_cordum_agent_v1_buspacket_proto_msgTypes,
	}.Build()
	File_cordum_agent_v1_buspacket_proto = out.File
	file_cordum_agent_v1_buspacket_proto_goTypes = nil
	file_cordum_agent_v1_buspacket_proto_depIdxs = nil
}
