// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: cordum/agent/v1/job.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JobPriority represents scheduling hints.
type JobPriority int32

const (
	JobPriority_JOB_PRIORITY_UNSPECIFIED JobPriority = 0
	JobPriority_JOB_PRIORITY_INTERACTIVE JobPriority = 1
	JobPriority_JOB_PRIORITY_BATCH       JobPriority = 2
	JobPriority_JOB_PRIORITY_CRITICAL    JobPriority = 3
)

// Enum value maps for JobPriority.
var (
	JobPriority_name = map[int32]string{
		0: "JOB_PRIORITY_UNSPECIFIED",
		1: "JOB_PRIORITY_INTERACTIVE",
		2: "JOB_PRIORITY_BATCH",
		3: "JOB_PRIORITY_CRITICAL",
	}
	JobPriority_value = map[string]int32{
		"JOB_PRIORITY_UNSPECIFIED": 0,
		"JOB_PRIORITY_INTERACTIVE": 1,
		"JOB_PRIORITY_BATCH":       2,
		"JOB_PRIORITY_CRITICAL":    3,
	}
)

func (x JobPriority) Enum() *JobPriority {
	p := new(JobPriority)
	*p = x
	return p
}

func (x JobPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_cordum_agent_v1_job_proto_enumTypes[0].Descriptor()
}

func (JobPriority) Type() protoreflect.EnumType {
	return &file_cordum_agent_v1_job_proto_enumTypes[0]
}

func (x JobPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobPriority.Descriptor instead.
func (JobPriority) EnumDescriptor() ([]byte, []int) {
	return file_cordum_agent_v1_job_proto_rawDescGZIP(), []int{0}
}

// JobStatus captures lifecycle states for a job.
type JobStatus int32

const (
	JobStatus_JOB_STATUS_UNSPECIFIED JobStatus = 0
	JobStatus_JOB_STATUS_PENDING     JobStatus = 1
	JobStatus_JOB_STATUS_SCHEDULED   JobStatus = 2
	JobStatus_JOB_STATUS_DISPATCHED  JobStatus = 3
	JobStatus_JOB_STATUS_RUNNING     JobStatus = 4
	JobStatus_JOB_STATUS_SUCCEEDED   JobStatus = 5
	JobStatus_JOB_STATUS_FAILED      JobStatus = 6
	JobStatus_JOB_STATUS_CANCELLED   JobStatus = 7
	JobStatus_JOB_STATUS_DENIED      JobStatus = 8
	JobStatus_JOB_STATUS_TIMEOUT     JobStatus = 9
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_UNSPECIFIED",
		1: "JOB_STATUS_PENDING",
		2: "JOB_STATUS_SCHEDULED",
		3: "JOB_STATUS_DISPATCHED",
		4: "JOB_STATUS_RUNNING",
		5: "JOB_STATUS_SUCCEEDED",
		6: "JOB_STATUS_FAILED",
		7: "JOB_STATUS_CANCELLED",
		8: "JOB_STATUS_DENIED",
		9: "JOB_STATUS_TIMEOUT",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_UNSPECIFIED": 0,
		"JOB_STATUS_PENDING":     1,
		"JOB_STATUS_SCHEDULED":   2,
		"JOB_STATUS_DISPATCHED":  3,
		"JOB_STATUS_RUNNING":     4,
		"JOB_STATUS_SUCCEEDED":   5,
		"JOB_STATUS_FAILED":      6,
		"JOB_STATUS_CANCELLED":   7,
		"JOB_STATUS_DENIED":      8,
		"JOB_STATUS_TIMEOUT":     9,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_cordum_agent_v1_job_proto_enumTypes[1].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_cordum_agent_v1_job_proto_enumTypes[1]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_cordum_agent_v1_job_proto_rawDescGZIP(), []int{1}
}

// ActorType identifies the origin of a request.
type ActorType int32

const (
	ActorType_ACTOR_TYPE_UNSPECIFIED ActorType = 0
	ActorType_ACTOR_TYPE_HUMAN       ActorType = 1
	ActorType_ACTOR_TYPE_SERVICE     ActorType = 2
)

// Enum value maps for ActorType.
var (
	ActorType_name = map[int32]string{
		0: "ACTOR_TYPE_UNSPECIFIED",
		1: "ACTOR_TYPE_HUMAN",
		2: "ACTOR_TYPE_SERVICE",
	}
	ActorType_value = map[string]int32{
		"ACTOR_TYPE_UNSPECIFIED": 0,
		"ACTOR_TYPE_HUMAN":       1,
		"ACTOR_TYPE_SERVICE":     2,
	}
)

func (x ActorType) Enum() *ActorType {
	p := new(ActorType)
	*p = x
	return p
}

func (x ActorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActorType) Descriptor() protoreflect.EnumDescriptor {
	return file_cordum_agent_v1_job_proto_enumTypes[2].Descriptor()
}

func (ActorType) Type() protoreflect.EnumType {
	return &file_cordum_agent_v1_job_proto_enumTypes[2]
}

func (x ActorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActorType.Descriptor instead.
func (ActorType) EnumDescriptor() ([]byte, []int) {
	return file_cordum_agent_v1_job_proto_rawDescGZIP(), []int{2}
}

// ContextHints describe how a worker may fetch or adapt context.
type ContextHints struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MaxInputTokens     int32                  `protobuf:"varint,1,opt,name=max_input_tokens,json=maxInputTokens,proto3" json:"max_input_tokens,omitempty"`           // per-call token budget
	AllowSummarization bool                   `protobuf:"varint,2,opt,name=allow_summarization,json=allowSummarization,proto3" json:"allow_summarization,omitempty"` // worker may summarize input to fit
	AllowRetrieval     bool                   `protobuf:"varint,3,opt,name=allow_retrieval,json=allowRetrieval,proto3" json:"allow_retrieval,omitempty"`             // worker may retrieve using memory_id
	Tags               []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`                                                        // optional retrieval scope: logs/code/etc.
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ContextHints) Reset() {
	*x = ContextHints{}
	mi := &file_cordum_agent_v1_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextHints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextHints) ProtoMessage() {}

func (x *ContextHints) ProtoReflect() protoreflect.Message {
	mi := &file_cordum_agent_v1_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextHints.ProtoReflect.Descriptor instead.
func (*ContextHints) Descriptor() ([]byte, []int) {
	return file_cordum_agent_v1_job_proto_rawDescGZIP(), []int{0}
}

func (x *ContextHints) GetMaxInputTokens() int32 {
	if x != nil {
		return x.MaxInputTokens
	}
	return 0
}

func (x *ContextHints) GetAllowSummarization() bool {
	if x != nil {
		return x.AllowSummarization
	}
	return false
}

func (x *ContextHints) GetAllowRetrieval() bool {
	if x != nil {
		return x.AllowRetrieval
	}
	return false
}

func (x *ContextHints) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// Budget carries soft limits for execution.
type Budget struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MaxInputTokens  int64                  `protobuf:"varint,1,opt,name=max_input_tokens,json=maxInputTokens,proto3" json:"max_input_tokens,omitempty"`    // total input token budget for the job
	MaxOutputTokens int64                  `protobuf:"varint,2,opt,name=max_output_tokens,json=maxOutputTokens,proto3" json:"max_output_tokens,omitempty"` // total output token budget for the job
	MaxTotalTokens  int64                  `protobuf:"varint,3,opt,name=max_total_tokens,json=maxTotalTokens,proto3" json:"max_total_tokens,omitempty"`    // combined in/out ceiling
	DeadlineMs      int64                  `protobuf:"varint,4,opt,name=deadline_ms,json=deadlineMs,proto3" json:"deadline_ms,omitempty"`                  // soft deadline for completion
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Budget) Reset() {
	*x = Budget{}
	mi := &file_cordum_agent_v1_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Budget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Budget) ProtoMessage() {}

func (x *Budget) ProtoReflect() protoreflect.Message {
	mi := &file_cordum_agent_v1_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Budget.ProtoReflect.Descriptor instead.
func (*Budget) Descriptor() ([]byte, []int) {
	return file_cordum_agent_v1_job_proto_rawDescGZIP(), []int{1}
}

func (x *Budget) GetMaxInputTokens() int64 {
	if x != nil {
		return x.MaxInputTokens
	}
	return 0
}

func (x *Budget) GetMaxOutputTokens() int64 {
	if x != nil {
		return x.MaxOutputTokens
	}
	return 0
}

func (x *Budget) GetMaxTotalTokens() int64 {
	if x != nil {
		return x.MaxTotalTokens
	}
	return 0
}

func (x *Budget) GetDeadlineMs() int64 {
	if x != nil {
		return x.DeadlineMs
	}
	return 0
}

// JobMetadata captures structured identity and capability metadata.
type JobMetadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ActorId        string                 `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	ActorType      ActorType              `protobuf:"varint,3,opt,name=actor_type,json=actorType,proto3,enum=cordum.agent.v1.ActorType" json:"actor_type,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Capability     string                 `protobuf:"bytes,5,opt,name=capability,proto3" json:"capability,omitempty"`                                                                   // semantic action label
	RiskTags       []string               `protobuf:"bytes,6,rep,name=risk_tags,json=riskTags,proto3" json:"risk_tags,omitempty"`                                                       // prod/write/network/secrets/exec/etc.
	Requires       []string               `protobuf:"bytes,7,rep,name=requires,proto3" json:"requires,omitempty"`                                                                       // docker/git/kubectl/network-egress/etc.
	PackId         string                 `protobuf:"bytes,8,opt,name=pack_id,json=packId,proto3" json:"pack_id,omitempty"`                                                             // empty for platform-only jobs
	Labels         map[string]string      `protobuf:"bytes,9,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // freeform metadata
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JobMetadata) Reset() {
	*x = JobMetadata{}
	mi := &file_cordum_agent_v1_job_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobMetadata) ProtoMessage() {}

func (x *JobMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_cordum_agent_v1_job_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobMetadata.ProtoReflect.Descriptor instead.
func (*JobMetadata) Descriptor() ([]byte, []int) {
	return file_cordum_agent_v1_job_proto_rawDescGZIP(), []int{2}
}

func (x *JobMetadata) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *JobMetadata) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *JobMetadata) GetActorType() ActorType {
	if x != nil {
		return x.ActorType
	}
	return ActorType_ACTOR_TYPE_UNSPECIFIED
}

func (x *JobMetadata) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *JobMetadata) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *JobMetadata) GetRiskTags() []string {
	if x != nil {
		return x.RiskTags
	}
	return nil
}

func (x *JobMetadata) GetRequires() []string {
	if x != nil {
		return x.Requires
	}
	return nil
}

func (x *JobMetadata) GetPackId() string {
	if x != nil {
		return x.PackId
	}
	return ""
}

func (x *JobMetadata) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// JobRequest represents a schedulable unit of work.
type JobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`                                                                 // globally unique job identifier
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`                                                                              // bus subject, e.g. job.chat.simple
	Priority      JobPriority            `protobuf:"varint,3,opt,name=priority,proto3,enum=cordum.agent.v1.JobPriority" json:"priority,omitempty"`                                      // scheduling hint
	ContextPtr    string                 `protobuf:"bytes,4,opt,name=context_ptr,json=contextPtr,proto3" json:"context_ptr,omitempty"`                                                  // opaque pointer to input payload
	AdapterId     string                 `protobuf:"bytes,5,opt,name=adapter_id,json=adapterId,proto3" json:"adapter_id,omitempty"`                                                     // optional specialization hint
	Env           map[string]string      `protobuf:"bytes,6,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`        // tenant, locale, sandbox flags, etc.
	ParentJobId   string                 `protobuf:"bytes,7,opt,name=parent_job_id,json=parentJobId,proto3" json:"parent_job_id,omitempty"`                                             // optional parent link
	WorkflowId    string                 `protobuf:"bytes,8,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`                                                  // optional workflow identifier
	StepIndex     int32                  `protobuf:"varint,9,opt,name=step_index,json=stepIndex,proto3" json:"step_index,omitempty"`                                                    // optional ordering within a workflow
	MemoryId      string                 `protobuf:"bytes,10,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`                                                       // logical corpus id (repo/chat/kb/etc.)
	ContextHints  *ContextHints          `protobuf:"bytes,11,opt,name=context_hints,json=contextHints,proto3" json:"context_hints,omitempty"`                                           // guidance for retrieval/summarization
	Budget        *Budget                `protobuf:"bytes,12,opt,name=budget,proto3" json:"budget,omitempty"`                                                                           // soft limits for cost/time
	TenantId      string                 `protobuf:"bytes,13,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`                                                       // tenant or organization id
	PrincipalId   string                 `protobuf:"bytes,14,opt,name=principal_id,json=principalId,proto3" json:"principal_id,omitempty"`                                              // end-user or service identity
	Labels        map[string]string      `protobuf:"bytes,15,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // arbitrary routing/placement labels
	Meta          *JobMetadata           `protobuf:"bytes,16,opt,name=meta,proto3" json:"meta,omitempty"`                                                                               // structured identity/capability metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobRequest) Reset() {
	*x = JobRequest{}
	mi := &file_cordum_agent_v1_job_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRequest) ProtoMessage() {}

func (x *JobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cordum_agent_v1_job_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRequest.ProtoReflect.Descriptor instead.
func (*JobRequest) Descriptor() ([]byte, []int) {
	return file_cordum_agent_v1_job_proto_rawDescGZIP(), []int{3}
}

func (x *JobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *JobRequest) GetPriority() JobPriority {
	if x != nil {
		return x.Priority
	}
	return JobPriority_JOB_PRIORITY_UNSPECIFIED
}

func (x *JobRequest) GetContextPtr() string {
	if x != nil {
		return x.ContextPtr
	}
	return ""
}

func (x *JobRequest) GetAdapterId() string {
	if x != nil {
		return x.AdapterId
	}
	return ""
}

func (x *JobRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *JobRequest) GetParentJobId() string {
	if x != nil {
		return x.ParentJobId
	}
	return ""
}

func (x *JobRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *JobRequest) GetStepIndex() int32 {
	if x != nil {
		return x.StepIndex
	}
	return 0
}

func (x *JobRequest) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

func (x *JobRequest) GetContextHints() *ContextHints {
	if x != nil {
		return x.ContextHints
	}
	return nil
}

func (x *JobRequest) GetBudget() *Budget {
	if x != nil {
		return x.Budget
	}
	return nil
}

func (x *JobRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *JobRequest) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

func (x *JobRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *JobRequest) GetMeta() *JobMetadata {
	if x != nil {
		return x.Meta
	}
	return nil
}

// JobResult conveys the outcome of a job.
type JobResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`                      // originating job identifier
	Status        JobStatus              `protobuf:"varint,2,opt,name=status,proto3,enum=cordum.agent.v1.JobStatus" json:"status,omitempty"` // terminal or transitional state
	ResultPtr     string                 `protobuf:"bytes,3,opt,name=result_ptr,json=resultPtr,proto3" json:"result_ptr,omitempty"`          // pointer to output payload
	WorkerId      string                 `protobuf:"bytes,4,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`             // emitting worker
	ExecutionMs   int64                  `protobuf:"varint,5,opt,name=execution_ms,json=executionMs,proto3" json:"execution_ms,omitempty"`   // elapsed processing time in milliseconds
	ErrorCode     string                 `protobuf:"bytes,6,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`          // optional machine-readable error
	ErrorMessage  string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // optional human-readable error
	ArtifactPtrs  []string               `protobuf:"bytes,8,rep,name=artifact_ptrs,json=artifactPtrs,proto3" json:"artifact_ptrs,omitempty"` // pointers to artifacts (logs/diffs/evidence)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResult) Reset() {
	*x = JobResult{}
	mi := &file_cordum_agent_v1_job_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResult) ProtoMessage() {}

func (x *JobResult) ProtoReflect() protoreflect.Message {
	mi := &file_cordum_agent_v1_job_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResult.ProtoReflect.Descriptor instead.
func (*JobResult) Descriptor() ([]byte, []int) {
	return file_cordum_agent_v1_job_proto_rawDescGZIP(), []int{4}
}

func (x *JobResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobResult) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *JobResult) GetResultPtr() string {
	if x != nil {
		return x.ResultPtr
	}
	return ""
}

func (x *JobResult) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *JobResult) GetExecutionMs() int64 {
	if x != nil {
		return x.ExecutionMs
	}
	return 0
}

func (x *JobResult) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *JobResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *JobResult) GetArtifactPtrs() []string {
	if x != nil {
		return x.ArtifactPtrs
	}
	return nil
}

// JobProgress conveys incremental progress for a job.
type JobProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`                      // originating job identifier
	StepId        string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`                   // optional workflow step identifier
	Percent       int32                  `protobuf:"varint,3,opt,name=percent,proto3" json:"percent,omitempty"`                              // 0-100 progress indicator
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                               // human-readable progress update
	ResultPtr     string                 `protobuf:"bytes,5,opt,name=result_ptr,json=resultPtr,proto3" json:"result_ptr,omitempty"`          // optional partial result pointer
	ArtifactPtrs  []string               `protobuf:"bytes,6,rep,name=artifact_ptrs,json=artifactPtrs,proto3" json:"artifact_ptrs,omitempty"` // optional artifacts emitted so far
	Status        JobStatus              `protobuf:"varint,7,opt,name=status,proto3,enum=cordum.agent.v1.JobStatus" json:"status,omitempty"` // optional status hint
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobProgress) Reset() {
	*x = JobProgress{}
	mi := &file_cordum_agent_v1_job_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobProgress) ProtoMessage() {}

func (x *JobProgress) ProtoReflect() protoreflect.Message {
	mi := &file_cordum_agent_v1_job_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobProgress.ProtoReflect.Descriptor instead.
func (*JobProgress) Descriptor() ([]byte, []int) {
	return file_cordum_agent_v1_job_proto_rawDescGZIP(), []int{5}
}

func (x *JobProgress) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobProgress) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *JobProgress) GetPercent() int32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *JobProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JobProgress) GetResultPtr() string {
	if x != nil {
		return x.ResultPtr
	}
	return ""
}

func (x *JobProgress) GetArtifactPtrs() []string {
	if x != nil {
		return x.ArtifactPtrs
	}
	return nil
}

func (x *JobProgress) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

// JobCancel requests cancellation of a running job.
type JobCancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	RequestedBy   string                 `protobuf:"bytes,3,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobCancel) Reset() {
	*x = JobCancel{}
	mi := &file_cordum_agent_v1_job_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobCancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobCancel) ProtoMessage() {}

func (x *JobCancel) ProtoReflect() protoreflect.Message {
	mi := &file_cordum_agent_v1_job_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobCancel.ProtoReflect.Descriptor instead.
func (*JobCancel) Descriptor() ([]byte, []int) {
	return file_cordum_agent_v1_job_proto_rawDescGZIP(), []int{6}
}

func (x *JobCancel) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobCancel) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *JobCancel) GetRequestedBy() string {
	if x != nil {
		return x.RequestedBy
	}
	return ""
}

var File_cordum_agent_v1_job_proto protoreflect.FileDescriptor

const file_cordum_agent_v1_job_proto_rawDesc = "" +
	"\n" +
	"\x19cordum/agent/v1/job.proto\x12\x0fcordum.agent.v1\"\xa6\x01\n" +
	"\fContextHints\x12(\n" +
	"\x10max_input_tokens\x18\x01 \x01(\x05R\x0emaxInputTokens\x12/\n" +
	"\x13allow_summarization\x18\x02 \x01(\bR\x12allowSummarization\x12'\n" +
	"\x0fallow_retrieval\x18\x03 \x01(\bR\x0eallowRetrieval\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"\xa9\x01\n" +
	"\x06Budget\x12(\n" +
	"\x10max_input_tokens\x18\x01 \x01(\x03R\x0emaxInputTokens\x12*\n" +
	"\x11max_output_tokens\x18\x02 \x01(\x03R\x0fmaxOutputTokens\x12(\n" +
	"\x10max_total_tokens\x18\x03 \x01(\x03R\x0emaxTotalTokens\x12\x1f\n" +
	"\vdeadline_ms\x18\x04 \x01(\x03R\n" +
	"deadlineMs\"\x98\x03\n" +
	"\vJobMetadata\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bactor_id\x18\x02 \x01(\tR\aactorId\x129\n" +
	"\n" +
	"actor_type\x18\x03 \x01(\x0e2\x1a.cordum.agent.v1.ActorTypeR\tactorType\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x12\x1e\n" +
	"\n" +
	"capability\x18\x05 \x01(\tR\n" +
	"capability\x12\x1b\n" +
	"\trisk_tags\x18\x06 \x03(\tR\briskTags\x12\x1a\n" +
	"\brequires\x18\a \x03(\tR\brequires\x12\x17\n" +
	"\apack_id\x18\b \x01(\tR\x06packId\x12@\n" +
	"\x06labels\x18\t \x03(\v2(.cordum.agent.v1.JobMetadata.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x06\n" +
	"\n" +
	"JobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x128\n" +
	"\bpriority\x18\x03 \x01(\x0e2\x1c.cordum.agent.v1.JobPriorityR\bpriority\x12\x1f\n" +
	"\vcontext_ptr\x18\x04 \x01(\tR\n" +
	"contextPtr\x12\x1d\n" +
	"\n" +
	"adapter_id\x18\x05 \x01(\tR\tadapterId\x126\n" +
	"\x03env\x18\x06 \x03(\v2$.cordum.agent.v1.JobRequest.EnvEntryR\x03env\x12\"\n" +
	"\rparent_job_id\x18\a \x01(\tR\vparentJobId\x12\x1f\n" +
	"\vworkflow_id\x18\b \x01(\tR\n" +
	"workflowId\x12\x1d\n" +
	"\n" +
	"step_index\x18\t \x01(\x05R\tstepIndex\x12\x1b\n" +
	"\tmemory_id\x18\n" +
	" \x01(\tR\bmemoryId\x12B\n" +
	"\rcontext_hints\x18\v \x01(\v2\x1d.cordum.agent.v1.ContextHintsR\fcontextHints\x12/\n" +
	"\x06budget\x18\f \x01(\v2\x17.cordum.agent.v1.BudgetR\x06budget\x12\x1b\n" +
	"\ttenant_id\x18\r \x01(\tR\btenantId\x12!\n" +
	"\fprincipal_id\x18\x0e \x01(\tR\vprincipalId\x12?\n" +
	"\x06labels\x18\x0f \x03(\v2'.cordum.agent.v1.JobRequest.LabelsEntryR\x06labels\x120\n" +
	"\x04meta\x18\x10 \x01(\v2\x1c.cordum.agent.v1.JobMetadataR\x04meta\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9e\x02\n" +
	"\tJobResult\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x122\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1a.cordum.agent.v1.JobStatusR\x06status\x12\x1d\n" +
	"\n" +
	"result_ptr\x18\x03 \x01(\tR\tresultPtr\x12\x1b\n" +
	"\tworker_id\x18\x04 \x01(\tR\bworkerId\x12!\n" +
	"\fexecution_ms\x18\x05 \x01(\x03R\vexecutionMs\x12\x1d\n" +
	"\n" +
	"error_code\x18\x06 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\x12#\n" +
	"\rartifact_ptrs\x18\b \x03(\tR\fartifactPtrs\"\xe9\x01\n" +
	"\vJobProgress\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\x12\x18\n" +
	"\apercent\x18\x03 \x01(\x05R\apercent\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"result_ptr\x18\x05 \x01(\tR\tresultPtr\x12#\n" +
	"\rartifact_ptrs\x18\x06 \x03(\tR\fartifactPtrs\x122\n" +
	"\x06status\x18\a \x01(\x0e2\x1a.cordum.agent.v1.JobStatusR\x06status\"]\n" +
	"\tJobCancel\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12!\n" +
	"\frequested_by\x18\x03 \x01(\tR\vrequestedBy*|\n" +
	"\vJobPriority\x12\x1c\n" +
	"\x18JOB_PRIORITY_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18JOB_PRIORITY_INTERACTIVE\x10\x01\x12\x16\n" +
	"\x12JOB_PRIORITY_BATCH\x10\x02\x12\x19\n" +
	"\x15JOB_PRIORITY_CRITICAL\x10\x03*\x86\x02\n" +
	"\tJobStatus\x12\x1a\n" +
	"\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12JOB_STATUS_PENDING\x10\x01\x12\x18\n" +
	"\x14JOB_STATUS_SCHEDULED\x10\x02\x12\x19\n" +
	"\x15JOB_STATUS_DISPATCHED\x10\x03\x12\x16\n" +
	"\x12JOB_STATUS_RUNNING\x10\x04\x12\x18\n" +
	"\x14JOB_STATUS_SUCCEEDED\x10\x05\x12\x15\n" +
	"\x11JOB_STATUS_FAILED\x10\x06\x12\x18\n" +
	"\x14JOB_STATUS_CANCELLED\x10\a\x12\x15\n" +
	"\x11JOB_STATUS_DENIED\x10\b\x12\x16\n" +
	"\x12JOB_STATUS_TIMEOUT\x10\t*U\n" +
	"\tActorType\x12\x1a\n" +
	"\x16ACTOR_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ACTOR_TYPE_HUMAN\x10\x01\x12\x16\n" +
	"\x12ACTOR_TYPE_SERVICE\x10\x02B\x7f\n" +
	"\x16io.cordum.cap.agent.v1P\x01Z+github.com/cordum-io/cap/v2/cordum/agent/v1\xaa\x02\x0fCordum.Agent.V1\xca\x02\x0fcordum\\Agent\\V1\xea\x02\x11Cordum::Agent::V1b\x06proto3"

var (
	file_cordum_agent_v1_job_proto_rawDescOnce sync.Once
	file_cordum_agent_v1_job_proto_rawDescData []byte
)

func file_cordum_agent_v1_job_proto_rawDescGZIP() []byte {
	file_cordum_agent_v1_job_proto_rawDescOnce.Do(func() {
		file_cordum_agent_v1_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cordum_agent_v1_job_proto_rawDesc), len(file_cordum_agent_v1_job_proto_rawDesc)))
	})
	return file_cordum_agent_v1_job_proto_rawDescData
}

var file_cordum_agent_v1_job_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_cordum_agent_v1_job_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_cordum_agent_v1_job_proto_goTypes = []any{
	(JobPriority)(0),     // 0: cordum.agent.v1.JobPriority
	(JobStatus)(0),       // 1: cordum.agent.v1.JobStatus
	(ActorType)(0),       // 2: cordum.agent.v1.ActorType
	(*ContextHints)(nil), // 3: cordum.agent.v1.ContextHints
	(*Budget)(nil),       // 4: cordum.agent.v1.Budget
	(*JobMetadata)(nil),  // 5: cordum.agent.v1.JobMetadata
	(*JobRequest)(nil),   // 6: cordum.agent.v1.JobRequest
	(*JobResult)(nil),    // 7: cordum.agent.v1.JobResult
	(*JobProgress)(nil),  // 8: cordum.agent.v1.JobProgress
	(*JobCancel)(nil),    // 9: cordum.agent.v1.JobCancel
	nil,                  // 10: cordum.agent.v1.JobMetadata.LabelsEntry
	nil,                  // 11: cordum.agent.v1.JobRequest.EnvEntry
	nil,                  // 12: cordum.agent.v1.JobRequest.LabelsEntry
}
var file_cordum_agent_v1_job_proto_depIdxs = []int32{
	2,  // 0: cordum.agent.v1.JobMetadata.actor_type:type_name -> cordum.agent.v1.ActorType
	10, // 1: cordum.agent.v1.JobMetadata.labels:type_name -> cordum.agent.v1.JobMetadata.LabelsEntry
	0,  // 2: cordum.agent.v1.JobRequest.priority:type_name -> cordum.agent.v1.JobPriority
	11, // 3: cordum.agent.v1.JobRequest.env:type_name -> cordum.agent.v1.JobRequest.EnvEntry
	3,  // 4: cordum.agent.v1.JobRequest.context_hints:type_name -> cordum.agent.v1.ContextHints
	4,  // 5: cordum.agent.v1.JobRequest.budget:type_name -> cordum.agent.v1.Budget
	12, // 6: cordum.agent.v1.JobRequest.labels:type_name -> cordum.agent.v1.JobRequest.LabelsEntry
	5,  // 7: cordum.agent.v1.JobRequest.meta:type_name -> cordum.agent.v1.JobMetadata
	1,  // 8: cordum.agent.v1.JobResult.status:type_name -> cordum.agent.v1.JobStatus
	1,  // 9: cordum.agent.v1.JobProgress.status:type_name -> cordum.agent.v1.JobStatus
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_cordum_agent_v1_job_proto_init() }
func file_cordum_agent_v1_job_proto_init() {
	if File_cordum_agent_v1_job_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cordum_agent_v1_job_proto_rawDesc), len(file_cordum_agent_v1_job_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cordum_agent_v1_job_proto_goTypes,
		DependencyIndexes: file_cordum_agent_v1_job_proto_depIdxs,
		EnumInfos:         file_cordum_agent_v1_job_proto_enumTypes,
		MessageInfos:      file_cordum_agent_v1_job_proto_msgTypes,
	}.Build()
	File_cordum_agent_v1_job_proto = out.File
	file_cordum_agent_v1_job_proto_goTypes = nil
	file_cordum_agent_v1_job_proto_depIdxs = nil
}
